/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pendaftaran;

import MenuPegawai.*;
import MenuUtama.*;
import Koneksi.GlobalVar;
import java.awt.Color;
import java.awt.Frame;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author donih
 */
public class DataPendaftaran extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    String NoPasien;
    String NoPendaftaran;
    String TglPendaftaran;
    DefaultTableModel table = new DefaultTableModel();
    DefaultTableModel table2 = new DefaultTableModel();
    DefaultTableModel table3 = new DefaultTableModel();
    public DataPendaftaran() {
        initComponents();
       
        TableDataPasien.setModel(table);
        table.addColumn("No Pendaftaran");
        table.addColumn("No Pasien");
        table.addColumn("Nama Pasien");
        table.addColumn("Tanggal Pendaftaran");
        table.addColumn("No Antrian");
        tampilData();
        TableKeranjang.setModel(table2);
        table2.addColumn("Id");
        table2.addColumn("Nama Jenis Biaya");
        table2.addColumn("Tarif");
        TableBiaya.setModel(table3);
        table3.addColumn("Id");
        table3.addColumn("Nama Jenis Biaya");
        table3.addColumn("Tarif");
        this.setBackground(new Color(0,0,0,0));
        txtUser.setText("Hi!, " + GlobalVar.nama);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tambahData = new javax.swing.JDialog();
        CLOSE2 = new javax.swing.JButton();
        CLOSE3 = new javax.swing.JButton();
        MIN1 = new javax.swing.JButton();
        MAX1 = new javax.swing.JButton();
        CLOSE1 = new javax.swing.JButton();
        NoPas = new javax.swing.JComboBox<>();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableKeranjang = new javax.swing.JTable();
        NoUrut = new javax.swing.JTextField();
        NIP = new javax.swing.JLabel();
        NIP1 = new javax.swing.JLabel();
        NIP2 = new javax.swing.JLabel();
        header1 = new javax.swing.JLabel();
        bg1 = new javax.swing.JLabel();
        btngroupJK = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        Biaya = new javax.swing.JDialog();
        btnPilihBiaya = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableBiaya = new javax.swing.JTable();
        MIN2 = new javax.swing.JButton();
        MAX2 = new javax.swing.JButton();
        CLOSE4 = new javax.swing.JButton();
        header2 = new javax.swing.JLabel();
        bg2 = new javax.swing.JLabel();
        btnInput = new javax.swing.JButton();
        MIN = new javax.swing.JButton();
        MAX = new javax.swing.JButton();
        CLOSE = new javax.swing.JButton();
        btnPembayaran = new javax.swing.JButton();
        btnObat = new javax.swing.JButton();
        btnJadwalPraktek = new javax.swing.JButton();
        btnPemeriksaan = new javax.swing.JButton();
        btnPoli = new javax.swing.JButton();
        btnDokter = new javax.swing.JButton();
        btnPegawai = new javax.swing.JButton();
        btnPendaftaran = new javax.swing.JButton();
        btnSubPendaftaran = new javax.swing.JButton();
        btnSubDataPasien = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        navi = new javax.swing.JLabel();
        btnUser = new javax.swing.JButton();
        txtUser = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        userPanel = new javax.swing.JLabel();
        Table = new javax.swing.JScrollPane();
        TableDataPasien = new javax.swing.JTable();
        BgPanel = new javax.swing.JLabel();
        BgSubMenu = new javax.swing.JLabel();
        editDataPasien = new javax.swing.JLabel();

        tambahData.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        tambahData.setMinimumSize(new java.awt.Dimension(874, 520));
        tambahData.setUndecorated(true);
        tambahData.setOpacity(0.0F);
        tambahData.setSize(new java.awt.Dimension(874, 520));
        tambahData.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                tambahDataWindowOpened(evt);
            }
        });
        tambahData.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CLOSE2.setBackground(new Color(0,0,0,0));
        CLOSE2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dokter/Asset/Group 11.png"))); // NOI18N
        CLOSE2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CLOSE2.setBorderPainted(false);
        CLOSE2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CLOSE2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/deleteaktif.png"))); // NOI18N
        CLOSE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLOSE2ActionPerformed(evt);
            }
        });
        tambahData.getContentPane().add(CLOSE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, 100, 90));

        CLOSE3.setBackground(new Color(0,0,0,0));
        CLOSE3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dokter/Asset/input.png"))); // NOI18N
        CLOSE3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CLOSE3.setBorderPainted(false);
        CLOSE3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CLOSE3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/inputaktif.png"))); // NOI18N
        CLOSE3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLOSE3ActionPerformed(evt);
            }
        });
        tambahData.getContentPane().add(CLOSE3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, 100, 90));

        MIN1.setBackground(new Color(0,0,0,0));
        MIN1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/-Off.png"))); // NOI18N
        MIN1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MIN1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Min.png"))); // NOI18N
        MIN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIN1ActionPerformed(evt);
            }
        });
        tambahData.getContentPane().add(MIN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 0, 30, 30));

        MAX1.setBackground(new Color(0,0,0,0));
        MAX1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/maxOff.png"))); // NOI18N
        MAX1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MAX1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Max.png"))); // NOI18N
        tambahData.getContentPane().add(MAX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 30, 30));

        CLOSE1.setBackground(new Color(0,0,0,0));
        CLOSE1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/xOff.png"))); // NOI18N
        CLOSE1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CLOSE1.setBorderPainted(false);
        CLOSE1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CLOSE1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Close.png"))); // NOI18N
        CLOSE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLOSE1ActionPerformed(evt);
            }
        });
        tambahData.getContentPane().add(CLOSE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 30, 30));

        NoPas.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        NoPas.setBorder(null);
        NoPas.setPreferredSize(new java.awt.Dimension(5, 28));
        NoPas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoPasActionPerformed(evt);
            }
        });
        tambahData.getContentPane().add(NoPas, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 210, 30));

        btnBatal.setBackground(new Color (0,0,0,0));
        btnBatal.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/TmblBatal.png"))); // NOI18N
        btnBatal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBatal.setBorderPainted(false);
        btnBatal.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/TmblBatalAktif.png"))); // NOI18N
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        tambahData.getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 130, -1));

        btnSimpan.setBackground(new Color (0,0,0,0));
        btnSimpan.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/tmblSimpan.png"))); // NOI18N
        btnSimpan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSimpan.setBorderPainted(false);
        btnSimpan.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/tmblSimpanAktif.png"))); // NOI18N
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        tambahData.getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 130, -1));

        TableKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TableKeranjang);

        tambahData.getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 340, 140));

        NoUrut.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        NoUrut.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NoUrut.setText("01");
        NoUrut.setToolTipText("Username");
        NoUrut.setAlignmentX(1.0F);
        NoUrut.setAlignmentY(1.0F);
        NoUrut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 174, 152), 2));
        NoUrut.setCaretColor(new java.awt.Color(30, 174, 152));
        NoUrut.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        NoUrut.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        NoUrut.setEnabled(false);
        NoUrut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoUrutActionPerformed(evt);
            }
        });
        tambahData.getContentPane().add(NoUrut, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 210, 120));

        NIP.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        NIP.setForeground(new java.awt.Color(30, 174, 152));
        NIP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pendaftaran/Asset/mdi_human-queue.png"))); // NOI18N
        NIP.setText("No Antrian");
        tambahData.getContentPane().add(NIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 180, -1));

        NIP1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        NIP1.setForeground(new java.awt.Color(30, 174, 152));
        NIP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pendaftaran/Asset/Vector (5).png"))); // NOI18N
        NIP1.setText("Biaya");
        tambahData.getContentPane().add(NIP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 180, -1));

        NIP2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        NIP2.setForeground(new java.awt.Color(30, 174, 152));
        NIP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/entypo_v-card.png"))); // NOI18N
        NIP2.setText("No Pasien");
        tambahData.getContentPane().add(NIP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 180, -1));

        header1.setBackground(new Color(0,0,0,0));
        header1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pendaftaran/Asset/Tambah Data (2).png"))); // NOI18N
        tambahData.getContentPane().add(header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 30));

        bg1.setBackground(new Color(0,0,0,0));
        bg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pendaftaran/Asset/Tambah.png"))); // NOI18N
        bg1.setToolTipText("");
        tambahData.getContentPane().add(bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 530));

        Biaya.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Biaya.setUndecorated(true);
        Biaya.setOpacity(0.0F);
        Biaya.setSize(new java.awt.Dimension(600, 600));
        Biaya.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                BiayaWindowOpened(evt);
            }
        });
        Biaya.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPilihBiaya.setBackground(new Color (0,0,0,0));
        btnPilihBiaya.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnPilihBiaya.setForeground(new java.awt.Color(255, 255, 255));
        btnPilihBiaya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pendaftaran/Asset/tmblSimpanAktif.png"))); // NOI18N
        btnPilihBiaya.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPilihBiaya.setBorderPainted(false);
        btnPilihBiaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihBiayaActionPerformed(evt);
            }
        });
        Biaya.getContentPane().add(btnPilihBiaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 130, -1));

        TableBiaya.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TableBiaya.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableBiayaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableBiaya);

        Biaya.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 480, 260));

        MIN2.setBackground(new Color(0,0,0,0));
        MIN2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/-Off.png"))); // NOI18N
        MIN2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MIN2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Min.png"))); // NOI18N
        MIN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIN2ActionPerformed(evt);
            }
        });
        Biaya.getContentPane().add(MIN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 30, 30));

        MAX2.setBackground(new Color(0,0,0,0));
        MAX2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/maxOff.png"))); // NOI18N
        MAX2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MAX2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Max.png"))); // NOI18N
        Biaya.getContentPane().add(MAX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 30, 30));

        CLOSE4.setBackground(new Color(0,0,0,0));
        CLOSE4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/xOff.png"))); // NOI18N
        CLOSE4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CLOSE4.setBorderPainted(false);
        CLOSE4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CLOSE4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Close.png"))); // NOI18N
        CLOSE4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLOSE4ActionPerformed(evt);
            }
        });
        Biaya.getContentPane().add(CLOSE4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 30, 30));

        header2.setBackground(new Color(0,0,0,0));
        header2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pendaftaran/Asset/pilihdata.png"))); // NOI18N
        Biaya.getContentPane().add(header2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 40));

        bg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/BgEditPegawai.png"))); // NOI18N
        bg2.setToolTipText("");
        Biaya.getContentPane().add(bg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 520));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        setOpacity(0.0F);
        setPreferredSize(new java.awt.Dimension(1280, 730));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInput.setBackground(new Color(0,0,0,0));
        btnInput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/input.png"))); // NOI18N
        btnInput.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnInput.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/inputaktif.png"))); // NOI18N
        btnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputActionPerformed(evt);
            }
        });
        getContentPane().add(btnInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 190, 90, 80));

        MIN.setBackground(new Color(0,0,0,0));
        MIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/-Off.png"))); // NOI18N
        MIN.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MIN.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Min.png"))); // NOI18N
        MIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MINActionPerformed(evt);
            }
        });
        getContentPane().add(MIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 0, 30, 30));

        MAX.setBackground(new Color(0,0,0,0));
        MAX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/maxOff.png"))); // NOI18N
        MAX.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MAX.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Max.png"))); // NOI18N
        getContentPane().add(MAX, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 0, 30, 30));

        CLOSE.setBackground(new Color(0,0,0,0));
        CLOSE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/xOff.png"))); // NOI18N
        CLOSE.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CLOSE.setBorderPainted(false);
        CLOSE.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CLOSE.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Close.png"))); // NOI18N
        CLOSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLOSEActionPerformed(evt);
            }
        });
        getContentPane().add(CLOSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 0, 30, 30));

        btnPembayaran.setBackground(new Color(0,0,0,0));
        btnPembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/pembayaran.png"))); // NOI18N
        btnPembayaran.setBorder(null);
        btnPembayaran.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/PembayaranAktif.png"))); // NOI18N
        btnPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembayaranActionPerformed(evt);
            }
        });
        getContentPane().add(btnPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 588, -1, -1));

        btnObat.setBackground(new Color(0,0,0,0));
        btnObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Obat.png"))); // NOI18N
        btnObat.setBorder(null);
        btnObat.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/ObatAktif.png"))); // NOI18N
        btnObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObatActionPerformed(evt);
            }
        });
        getContentPane().add(btnObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 514, -1, -1));

        btnJadwalPraktek.setBackground(new Color(0,0,0,0));
        btnJadwalPraktek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/JadwalPraktek.png"))); // NOI18N
        btnJadwalPraktek.setBorder(null);
        btnJadwalPraktek.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/JadwalPraktekAktif.png"))); // NOI18N
        btnJadwalPraktek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalPraktekActionPerformed(evt);
            }
        });
        getContentPane().add(btnJadwalPraktek, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 440, -1, -1));

        btnPemeriksaan.setBackground(new Color(0,0,0,0));
        btnPemeriksaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Pemeriksaan.png"))); // NOI18N
        btnPemeriksaan.setBorder(null);
        btnPemeriksaan.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/PemeriksaanAktif.png"))); // NOI18N
        btnPemeriksaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPemeriksaanActionPerformed(evt);
            }
        });
        getContentPane().add(btnPemeriksaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 366, -1, -1));

        btnPoli.setBackground(new Color(0,0,0,0));
        btnPoli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Poli.png"))); // NOI18N
        btnPoli.setBorder(null);
        btnPoli.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/PoliAktif.png"))); // NOI18N
        btnPoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoliActionPerformed(evt);
            }
        });
        getContentPane().add(btnPoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 292, -1, -1));

        btnDokter.setBackground(new Color(0,0,0,0));
        btnDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Dokter.png"))); // NOI18N
        btnDokter.setBorder(null);
        btnDokter.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/DokterAktif.png"))); // NOI18N
        btnDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDokterActionPerformed(evt);
            }
        });
        getContentPane().add(btnDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 218, -1, -1));

        btnPegawai.setBackground(new Color(0,0,0,0));
        btnPegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Pegawai.png"))); // NOI18N
        btnPegawai.setBorder(null);
        btnPegawai.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/PegawaiAktif.png"))); // NOI18N
        btnPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPegawaiActionPerformed(evt);
            }
        });
        getContentPane().add(btnPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 144, -1, -1));

        btnPendaftaran.setBackground(new Color(0,0,0,0));
        btnPendaftaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Pendaftaran.png"))); // NOI18N
        btnPendaftaran.setBorder(null);
        btnPendaftaran.setSelected(true);
        btnPendaftaran.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/PendaftaranAktif.png"))); // NOI18N
        btnPendaftaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendaftaranActionPerformed(evt);
            }
        });
        getContentPane().add(btnPendaftaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 70, -1, -1));

        btnSubPendaftaran.setBackground(new Color(0,0,0,0));
        btnSubPendaftaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pendaftaran/Asset/subPendaftaran.png"))); // NOI18N
        btnSubPendaftaran.setBorder(null);
        btnSubPendaftaran.setSelected(true);
        btnSubPendaftaran.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Pendaftaran/Asset/SubPendaftaranAktif.png"))); // NOI18N
        getContentPane().add(btnSubPendaftaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 196, -1, 40));

        btnSubDataPasien.setBackground(new Color (0,0,0,0));
        btnSubDataPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pendaftaran/Asset/SubDatapasien.png"))); // NOI18N
        btnSubDataPasien.setBorder(null);
        btnSubDataPasien.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Pendaftaran/Asset/SubDatapasienAktif.png"))); // NOI18N
        btnSubDataPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubDataPasienActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubDataPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 147, -1, 40));

        btnHome.setBackground(new Color(0,0,0,0));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hospital.png"))); // NOI18N
        btnHome.setToolTipText("Home");
        btnHome.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hospitalAktif.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 20, -1, -1));

        Title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pendaftaran/Asset/DATA PENDAFTARAN.png"))); // NOI18N
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, -1, -1));

        navi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/navi.png"))); // NOI18N
        getContentPane().add(navi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        btnUser.setBackground(new Color(0,0,0,0));
        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/akun.png"))); // NOI18N
        btnUser.setToolTipText("Log Out");
        btnUser.setBorder(null);
        btnUser.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/akun1.png"))); // NOI18N
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 34, -1, -1));

        txtUser.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtUser.setText("Hi!, User");
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 40, 200, 20));

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/header.png"))); // NOI18N
        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        userPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dokter/Asset/Acc (1).png"))); // NOI18N
        userPanel.setToolTipText("");
        getContentPane().add(userPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 27, -1, -1));

        TableDataPasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Table.setViewportView(TableDataPasien);

        getContentPane().add(Table, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 187, 830, 480));

        BgPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/panel.png"))); // NOI18N
        BgPanel.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(BgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 171, 980, -1));

        BgSubMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BgSubMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pendaftaran/Asset/SubMenu.png"))); // NOI18N
        BgSubMenu.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BgSubMenu.setPreferredSize(new java.awt.Dimension(150, 651));
        getContentPane().add(BgSubMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 65, 160, 650));

        editDataPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/bgmenupegawai.png"))); // NOI18N
        getContentPane().add(editDataPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tampilData(){
        //untuk mengahapus baris setelah input
        int row = TableDataPasien.getRowCount();
        for(int a = 0 ; a < row ; a++){
            table.removeRow(0);
        }
        
        String query = 
                "SELECT NoPendaftaran,pendaftaran.NoPasien,NamaPas,TglPendaftaran,NoUrut FROM pendaftaran INNER JOIN pasien ON pendaftaran.NoPasien = pasien.NoPasien";
                
        
        try{
            Connection connect = Koneksi.Koneksi.getKoneksi();//memanggil koneksi
            Statement sttmnt = connect.createStatement();//membuat statement
            ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
            
            while (rslt.next()){
                //menampung data sementara
                   
                    String noPen = rslt.getString("NoPendaftaran");
                    String noPas = rslt.getString("NoPasien");
                    String namaPas = rslt.getString("NamaPas");
                    String tglPen = rslt.getString("TglPendaftaran");
                    String urut = rslt.getString("NoUrut");
                    
                    
                //masukan semua data kedalam array
                String[] data = {noPen,noPas,namaPas,tglPen,urut};
                //menambahakan baris sesuai dengan data yang tersimpan diarray
                table.addRow(data);
            }
                //mengeset nilai yang ditampung agar muncul di table
                TableDataPasien.setModel(table);
            
        }catch(Exception e){
            System.out.println(e);
        }
       
    }
    private void tampilDataBiaya(){
        //untuk mengahapus baris setelah input
        int row = TableBiaya.getRowCount();
        for(int a = 0 ; a < row ; a++){
            table3.removeRow(0);
        }
        
        String query = 
                "SELECT * FROM jenisbiaya";
                
        
        try{
            Connection connect = Koneksi.Koneksi.getKoneksi();//memanggil koneksi
            Statement sttmnt = connect.createStatement();//membuat statement
            ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
            
            while (rslt.next()){
                //menampung data sementara
                   
                    String noPas = rslt.getString("IDJenisBiaya");
                    String namapas = rslt.getString("NamaBiaya");
                    String Tarif = rslt.getString("Tarif");
                    
                    
                //masukan semua data kedalam array
                String[] data = {noPas,namapas,Tarif};
                //menambahakan baris sesuai dengan data yang tersimpan diarray
                table3.addRow(data);
            }
                //mengeset nilai yang ditampung agar muncul di table
                TableBiaya.setModel(table3);
            
        }catch(Exception e){
            System.out.println(e);
        }
       
    }
    private void TampilComboBox(){      
        String query = "SELECT * FROM pasien ";
        
        try{
            Connection connect = Koneksi.Koneksi.getKoneksi();//memanggil koneksi
            Statement sttmnt = connect.createStatement();//membuat statement
            ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
            
            while (rslt.next()){
                String nama = rslt.getString("NamaPas");
                String kode = rslt.getString("NoPasien");
                NoPas.addItem(kode+ " " + nama);
            } 
        }catch(Exception e){
            
            System.out.println(e);
        } 
    }
    private void AntrianOtomatis(){
        String query = "SELECT * FROM pendaftaran WHERE TglPendaftaran = CURDATE() ORDER BY NoUrut DESC";
        try{
            Connection connect = Koneksi.Koneksi.getKoneksi();//memanggil koneksi
            Statement sttmnt = connect.createStatement();//membuat statement
            ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
            
            if (rslt.next()){
                String NoUrut = rslt.getString("NoUrut");
                this.NoUrut.setText(String.valueOf(Integer.parseInt(NoUrut)+1));
            }else{
                this.NoUrut.setText("1");
            }
        rslt.close();
        connect.close();
        }catch(Exception e){
            System.out.println(e);
        }
    }
    private void KodePendaftaranOtomatis(){
        String query = "SELECT * FROM pendaftaran  ORDER BY NoPendaftaran DESC";
        try{
            Connection connect = Koneksi.Koneksi.getKoneksi();//memanggil koneksi
            Statement sttmnt = connect.createStatement();//membuat statement
            ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
            
            if (rslt.next()){
                String NoPen = rslt.getString("NoPendaftaran").substring(1);
                String AN = "" + (Integer.parseInt(NoPen)+1);
                String NOL = "";
                if(AN.length()==1){
                    NOL = "000";
                }else if(AN.length()==2){
                    NOL = "00";
                }else if(AN.length()==3){
                    NOL = "0";
                }else if(AN.length()==4){
                    NOL = "";
                }
                NoPendaftaran = ("R" + NOL + AN);
            }else{
                NoPendaftaran = ("R0001");
            }
        rslt.close();
        connect.close();
        }catch(Exception e){
            System.out.println(e);
        }
    }
    private void hapusData(){
        //ambill data no pendaftaran
           
        Connection connect = Koneksi.Koneksi.getKoneksi();
        int baris = TableDataPasien.getSelectedRow();
        int jawab;
        String kode = table.getValueAt(baris,0).toString();
        
        String query = "DELETE FROM pasien WHERE NoPasien = '"+kode+"';";
        try{
            if ((jawab = JOptionPane.showConfirmDialog(null, "Ingin menghapus data?", "konfirmasi", JOptionPane.YES_NO_OPTION)) == 0) {
            PreparedStatement ps = (PreparedStatement) connect.prepareStatement(query);
            ps.execute();
            JOptionPane.showMessageDialog(null , "Data Berhasil Dihapus");
        }
        }catch(SQLException | HeadlessException e){
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Data Gagal Dihapus");
        }finally{
            tampilData();
        }
        
    }    
    
   
    private void MINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MINActionPerformed
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_MINActionPerformed

    private void CLOSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLOSEActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CLOSEActionPerformed

    private void btnPendaftaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendaftaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPendaftaranActionPerformed

    private void btnPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPegawaiActionPerformed
        // TODO add your handling code here:
        new MenuPegawai().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPegawaiActionPerformed

    private void btnDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDokterActionPerformed
        // TODO add your handling code here:
        new Dokter.MenuDokter().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDokterActionPerformed

    private void btnPoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoliActionPerformed
        // TODO add your handling code here:
        new MenuPoli.MenuPoli().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPoliActionPerformed

    private void btnPemeriksaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPemeriksaanActionPerformed
        // TODO add your handling code here:
        new MenuPemeriksaan.Pemeriksaan().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPemeriksaanActionPerformed

    private void btnJadwalPraktekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadwalPraktekActionPerformed
        // TODO add your handling code here:
        new MenuJadwal.MenuJadwal().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnJadwalPraktekActionPerformed

    private void btnObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnObatActionPerformed

    private void btnPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembayaranActionPerformed
        // TODO add your handling code here:
        new MenuPembayaran.JenisBiaya().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPembayaranActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        for(double i = 0.0; i <= 1.0; i = i + 0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(20);
            }
           catch(Exception e){
            }
        }
    }//GEN-LAST:event_formWindowOpened
    private void TambahData(){
     
    String NoPas = this.NoPas.getSelectedItem().toString().substring(0,6);
            
    
    
    String query = "SELECT DATE_FORMAT(NOW(), '%Y-%m-%d') AS tanggal";
        
        try{
            Connection connect = Koneksi.Koneksi.getKoneksi();//memanggil koneksi
            Statement sttmnt = connect.createStatement();//membuat statement
            ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
            
            while (rslt.next()){
                TglPendaftaran = rslt.getString("tanggal");
                
            } 
        }catch(Exception e){
            
            System.out.println(e);
        }
    String NoAntrian = NoUrut.getText();
    Connection connect = Koneksi.Koneksi.getKoneksi();
        String query2 = "INSERT INTO pendaftaran (NoPendaftaran, NoPasien, TglPendaftaran, NoUrut) "
                         + "VALUES ('"+NoPendaftaran+"', '"+NoPas+"','"+TglPendaftaran+"','"+NoAntrian+"')";
        
        try{
            PreparedStatement ps2 = (PreparedStatement) connect.prepareStatement(query2);
            ps2.executeUpdate(query2);
            for(int i = 0;i<=TableKeranjang.getColumnCount();i++){
                String IdBiaya = TableKeranjang.getValueAt(i, 0).toString();
                String query3 = "INSERT INTO detail_biaya (IDJenisBiaya, NoPendaftaran) "
                         + "VALUES ('"+IdBiaya+"', '"+NoPendaftaran+"')";
                try{
                    //menyiapkan statement untuk di eksekusi
                    PreparedStatement ps3 = (PreparedStatement) connect.prepareStatement(query3);
                    ps3.executeUpdate(query3);
                }catch(SQLException | HeadlessException e){
                    System.out.println(e);
                }
            }
            
        }catch(Exception e){
            System.out.println(e);
        }finally{
            JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
            tambahData.dispose();
            int a  = TableKeranjang.getRowCount();
            for(int i = a-1;i>=0;i--){
                table2.removeRow(i);
            }
            AntrianOtomatis();
            KodePendaftaranOtomatis();
        }}
    private void MIN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIN1ActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_MIN1ActionPerformed

    private void CLOSE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLOSE1ActionPerformed
        // TODO add your handling code here:
        tambahData.dispose();
        for(int i = 0; i < TableBiaya.getRowCount();i++){
            table3.removeRow(i);
        }
    }//GEN-LAST:event_CLOSE1ActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        tambahData.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if(TableKeranjang.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Isi Tabel Biaya");
        }else{            
            TambahData();
            tampilData();
        }
        
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void tambahDataWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_tambahDataWindowOpened
        // TODO add your handling code here:
        for(double i = 0.0; i <= 1.0; i = i + 0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
//            this.setOpacity(f);
            tambahData.setOpacity(f);
            try{
                Thread.sleep(20);
            }
           catch(Exception e){
            }
        }
    }//GEN-LAST:event_tambahDataWindowOpened

    private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputActionPerformed
        // TODO add your handling code here:
        tambahData.setVisible(true);
        tambahData.setBounds(360, 120, 874, 520);
        KodePendaftaranOtomatis();
        AntrianOtomatis();
        TampilComboBox();
        
        tampilDataBiaya();
    }//GEN-LAST:event_btnInputActionPerformed

    private void NoUrutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoUrutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoUrutActionPerformed

    private void NoPasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoPasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoPasActionPerformed

    private void CLOSE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLOSE2ActionPerformed
        // TODO add your handling code here:
        table2.removeRow(TableKeranjang.getSelectedRow());
    }//GEN-LAST:event_CLOSE2ActionPerformed

    private void CLOSE3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLOSE3ActionPerformed
        // TODO add your handling code here:
        Biaya.setVisible(true);
        Biaya.setBounds(450, 120, 600, 520);
    }//GEN-LAST:event_CLOSE3ActionPerformed

    private void MIN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIN2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_MIN2ActionPerformed

    private void CLOSE4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLOSE4ActionPerformed
        // TODO add your handling code here:
        Biaya.dispose();
    }//GEN-LAST:event_CLOSE4ActionPerformed

    private void BiayaWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_BiayaWindowOpened
        // TODO add your handling code here:
        for(double i = 0.0; i <= 1.0; i = i + 0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            //            this.setOpacity(f);
            Biaya.setOpacity(f);
            try{
                Thread.sleep(20);
            }
            catch(Exception e){
            }
        }
    }//GEN-LAST:event_BiayaWindowOpened

    private void btnPilihBiayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihBiayaActionPerformed
        // TODO add your handling code here:
        Biaya.setVisible(false);
        table2.addRow(new Object[]{Koneksi.GlobalVar.id_jenis,Koneksi.GlobalVar.namajenis,Koneksi.GlobalVar.tarif});
        tambahData.setVisible(true); 
        
    }//GEN-LAST:event_btnPilihBiayaActionPerformed

    private void TableBiayaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableBiayaMouseClicked
        // TODO add your handling code here:
        int baris = TableBiaya.getSelectedRow();
        Koneksi.GlobalVar.id_jenis = table3.getValueAt(baris,0).toString();
        Koneksi.GlobalVar.namajenis = table3.getValueAt(baris,1).toString();
         Koneksi.GlobalVar.tarif = table3.getValueAt(baris,2).toString();
        
    }//GEN-LAST:event_TableBiayaMouseClicked

    private void btnSubDataPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubDataPasienActionPerformed
        // TODO add your handling code here:
        new Pendaftaran.DataPasien().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSubDataPasienActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        // TODO add your handling code here:
        int opsi = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan keluar?", "Log out!", JOptionPane.YES_NO_OPTION);
        if (opsi == JOptionPane.YES_OPTION){
            new Login.Login().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnUserActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        new MenuUtama().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPendaftaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPendaftaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BgPanel;
    private javax.swing.JLabel BgSubMenu;
    private javax.swing.JDialog Biaya;
    private javax.swing.JButton CLOSE;
    private javax.swing.JButton CLOSE1;
    private javax.swing.JButton CLOSE2;
    private javax.swing.JButton CLOSE3;
    private javax.swing.JButton CLOSE4;
    private javax.swing.JButton MAX;
    private javax.swing.JButton MAX1;
    private javax.swing.JButton MAX2;
    private javax.swing.JButton MIN;
    private javax.swing.JButton MIN1;
    private javax.swing.JButton MIN2;
    private javax.swing.JLabel NIP;
    private javax.swing.JLabel NIP1;
    private javax.swing.JLabel NIP2;
    private javax.swing.JComboBox<String> NoPas;
    private javax.swing.JTextField NoUrut;
    private javax.swing.JScrollPane Table;
    private javax.swing.JTable TableBiaya;
    private javax.swing.JTable TableDataPasien;
    private javax.swing.JTable TableKeranjang;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel bg1;
    private javax.swing.JLabel bg2;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnDokter;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnInput;
    private javax.swing.JButton btnJadwalPraktek;
    private javax.swing.JButton btnObat;
    private javax.swing.JButton btnPegawai;
    private javax.swing.JButton btnPembayaran;
    private javax.swing.JButton btnPemeriksaan;
    private javax.swing.JButton btnPendaftaran;
    private javax.swing.JButton btnPilihBiaya;
    private javax.swing.JButton btnPoli;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnSubDataPasien;
    private javax.swing.JButton btnSubPendaftaran;
    private javax.swing.JButton btnUser;
    private javax.swing.ButtonGroup btngroupJK;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel editDataPasien;
    private javax.swing.JLabel header;
    private javax.swing.JLabel header1;
    private javax.swing.JLabel header2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel navi;
    private javax.swing.JDialog tambahData;
    private javax.swing.JLabel txtUser;
    private javax.swing.JLabel userPanel;
    // End of variables declaration//GEN-END:variables
}
