/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pendaftaran;

import MenuPegawai.*;
import MenuUtama.*;
import Koneksi.GlobalVar;
import MenuObat.MenuObat;
import java.awt.Color;
import java.awt.Frame;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author donih
 */
public class DataPasien extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    String NoPasien;
    String tglREGISTRASI;
    DefaultTableModel table = new DefaultTableModel();
    public DataPasien() {
        initComponents();
        TableDataPasien.setModel(table);
        table.addColumn("No Pasien");
        table.addColumn("Nama Pasien");
        table.addColumn("Alamat");
        table.addColumn("Telepon");
        table.addColumn("Tanggal Lahir");
        table.addColumn("Jenis Kelamin");
        table.addColumn("Tanggal Registrasi");
        tampilData();
        txtUser.setText("Hi!, "+ GlobalVar.nama);
        this.setBackground(new Color(0,0,0,0));
        if(Koneksi.GlobalVar.hak_akses.equals("Pegawai")){
            btnPegawai.setEnabled(false);
            btnDokter.setEnabled(false);
            btnPemeriksaan.setEnabled(false);
        }else if(Koneksi.GlobalVar.hak_akses.equals("Dokter")){
            btnPegawai.setEnabled(false);
            btnPendaftaran.setEnabled(false);
            btnDokter.setEnabled(false);
            btnPoli.setEnabled(false);
            btnObat.setEnabled(false);
            btnPembayaran.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tambahDataPasien = new javax.swing.JDialog();
        MIN1 = new javax.swing.JButton();
        MAX1 = new javax.swing.JButton();
        CLOSE1 = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        txtAlamatscroll = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        alamat = new javax.swing.JLabel();
        pilihanTglLhr = new com.toedter.calendar.JDateChooser();
        Tgllahir = new javax.swing.JLabel();
        txtTelp = new javax.swing.JTextField();
        Telepon = new javax.swing.JLabel();
        jk_perempuan = new javax.swing.JRadioButton();
        jk_Laki = new javax.swing.JRadioButton();
        jnsKelamin = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        nama = new javax.swing.JLabel();
        lock = new javax.swing.JLabel();
        txtNopas = new javax.swing.JTextField();
        NIP = new javax.swing.JLabel();
        header1 = new javax.swing.JLabel();
        bg1 = new javax.swing.JLabel();
        btngroupJK = new javax.swing.ButtonGroup();
        editDataPas = new javax.swing.JDialog();
        MIN3 = new javax.swing.JButton();
        MAX3 = new javax.swing.JButton();
        CLOSE3 = new javax.swing.JButton();
        btnBatal1 = new javax.swing.JButton();
        btnSimpan1 = new javax.swing.JButton();
        PerempuanEdit = new javax.swing.JRadioButton();
        lakiedit = new javax.swing.JRadioButton();
        txtAlamat1 = new javax.swing.JScrollPane();
        txtAlamatEdit = new javax.swing.JTextArea();
        alamat1 = new javax.swing.JLabel();
        txtRegis = new javax.swing.JTextField();
        TglRegis = new javax.swing.JLabel();
        pilihanTglLhrEdit = new com.toedter.calendar.JDateChooser();
        Tgllahir1 = new javax.swing.JLabel();
        txtTelpEdit = new javax.swing.JTextField();
        Telepon1 = new javax.swing.JLabel();
        jnsKelamin1 = new javax.swing.JLabel();
        lock1 = new javax.swing.JLabel();
        txtNamaEdit = new javax.swing.JTextField();
        nama1 = new javax.swing.JLabel();
        txtNopasEdit = new javax.swing.JTextField();
        NIP1 = new javax.swing.JLabel();
        header2 = new javax.swing.JLabel();
        bg2 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        PopupSearch = new javax.swing.JDialog();
        CLOSE6 = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        cari = new javax.swing.JButton();
        titleSearch = new javax.swing.JLabel();
        bg3 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnInput = new javax.swing.JButton();
        MIN = new javax.swing.JButton();
        MAX = new javax.swing.JButton();
        CLOSE = new javax.swing.JButton();
        btnPembayaran = new javax.swing.JButton();
        btnObat = new javax.swing.JButton();
        btnJadwalPraktek = new javax.swing.JButton();
        btnPemeriksaan = new javax.swing.JButton();
        btnPoli = new javax.swing.JButton();
        btnDokter = new javax.swing.JButton();
        btnPegawai = new javax.swing.JButton();
        btnPendaftaran = new javax.swing.JButton();
        btnSubPendaftaran = new javax.swing.JButton();
        btnSubDataPasien = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        navi = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        btnUser = new javax.swing.JButton();
        txtUser = new javax.swing.JLabel();
        userPanel = new javax.swing.JLabel();
        Table = new javax.swing.JScrollPane();
        TableDataPasien = new javax.swing.JTable();
        BgPanel = new javax.swing.JLabel();
        BgSubMenu = new javax.swing.JLabel();
        editDataPasien = new javax.swing.JLabel();

        tambahDataPasien.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        tambahDataPasien.setUndecorated(true);
        tambahDataPasien.setOpacity(0.0F);
        tambahDataPasien.setSize(new java.awt.Dimension(600, 600));
        tambahDataPasien.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                tambahDataPasienWindowOpened(evt);
            }
        });
        tambahDataPasien.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MIN1.setBackground(new Color(0,0,0,0));
        MIN1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/-Off.png"))); // NOI18N
        MIN1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MIN1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Min.png"))); // NOI18N
        MIN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIN1ActionPerformed(evt);
            }
        });
        tambahDataPasien.getContentPane().add(MIN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 30, 30));

        MAX1.setBackground(new Color(0,0,0,0));
        MAX1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/maxOff.png"))); // NOI18N
        MAX1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MAX1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Max.png"))); // NOI18N
        tambahDataPasien.getContentPane().add(MAX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 30, 30));

        CLOSE1.setBackground(new Color(0,0,0,0));
        CLOSE1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/xOff.png"))); // NOI18N
        CLOSE1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CLOSE1.setBorderPainted(false);
        CLOSE1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CLOSE1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Close.png"))); // NOI18N
        CLOSE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLOSE1ActionPerformed(evt);
            }
        });
        tambahDataPasien.getContentPane().add(CLOSE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 30, 30));

        btnBatal.setBackground(new Color (0,0,0,0));
        btnBatal.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/TmblBatal.png"))); // NOI18N
        btnBatal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBatal.setBorderPainted(false);
        btnBatal.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/TmblBatalAktif.png"))); // NOI18N
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        tambahDataPasien.getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 130, -1));

        btnSimpan.setBackground(new Color (0,0,0,0));
        btnSimpan.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/tmblSimpan.png"))); // NOI18N
        btnSimpan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSimpan.setBorderPainted(false);
        btnSimpan.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/tmblSimpanAktif.png"))); // NOI18N
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        tambahDataPasien.getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 130, -1));

        txtAlamat.setColumns(20);
        txtAlamat.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtAlamat.setRows(5);
        txtAlamat.setToolTipText("Alamat Pasien");
        txtAlamat.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 174, 152), 2, true));
        txtAlamat.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtAlamat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAlamatFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAlamatFocusLost(evt);
            }
        });
        txtAlamatscroll.setViewportView(txtAlamat);

        tambahDataPasien.getContentPane().add(txtAlamatscroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 280, 100));

        alamat.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        alamat.setForeground(new java.awt.Color(30, 174, 152));
        alamat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/entypo_address.png"))); // NOI18N
        alamat.setText("Alamat");
        tambahDataPasien.getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 140, -1));

        pilihanTglLhr.setToolTipText("Tanggal Lahir Pasien");
        pilihanTglLhr.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                pilihanTglLhrPropertyChange(evt);
            }
        });
        tambahDataPasien.getContentPane().add(pilihanTglLhr, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 280, -1));

        Tgllahir.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Tgllahir.setForeground(new java.awt.Color(30, 174, 152));
        Tgllahir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/Group.png"))); // NOI18N
        Tgllahir.setText("Tanggal Lahir");
        tambahDataPasien.getContentPane().add(Tgllahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 140, -1));

        txtTelp.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtTelp.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTelp.setToolTipText("Telepon");
        txtTelp.setAlignmentX(1.0F);
        txtTelp.setAlignmentY(1.0F);
        txtTelp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 174, 152), 2, true));
        txtTelp.setCaretColor(new java.awt.Color(30, 174, 152));
        txtTelp.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTelp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelpFocusLost(evt);
            }
        });
        txtTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelpActionPerformed(evt);
            }
        });
        txtTelp.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtTelpPropertyChange(evt);
            }
        });
        tambahDataPasien.getContentPane().add(txtTelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 280, 30));

        Telepon.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Telepon.setForeground(new java.awt.Color(30, 174, 152));
        Telepon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/bi_telephone-fill.png"))); // NOI18N
        Telepon.setText("Telepon");
        tambahDataPasien.getContentPane().add(Telepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 140, -1));

        jk_perempuan.setBackground(new Color(0,0,0,0));
        btngroupJK.add(jk_perempuan);
        jk_perempuan.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jk_perempuan.setText("Perempuan");
        jk_perempuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jk_perempuanActionPerformed(evt);
            }
        });
        tambahDataPasien.getContentPane().add(jk_perempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        jk_Laki.setBackground(new Color(0,0,0,0));
        btngroupJK.add(jk_Laki);
        jk_Laki.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jk_Laki.setText("Laki - Laki");
        jk_Laki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jk_LakiActionPerformed(evt);
            }
        });
        tambahDataPasien.getContentPane().add(jk_Laki, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        jnsKelamin.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jnsKelamin.setForeground(new java.awt.Color(30, 174, 152));
        jnsKelamin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/fa-solid_transgender.png"))); // NOI18N
        jnsKelamin.setText("Jenis Kelamin");
        tambahDataPasien.getContentPane().add(jnsKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 140, -1));

        txtNama.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtNama.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNama.setToolTipText("Nama Pasien");
        txtNama.setAlignmentX(1.0F);
        txtNama.setAlignmentY(1.0F);
        txtNama.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 174, 152), 2, true));
        txtNama.setCaretColor(new java.awt.Color(30, 174, 152));
        txtNama.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNamaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNamaFocusLost(evt);
            }
        });
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        txtNama.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtNamaPropertyChange(evt);
            }
        });
        tambahDataPasien.getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 280, 30));

        nama.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        nama.setForeground(new java.awt.Color(30, 174, 152));
        nama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/mdi_account.png"))); // NOI18N
        nama.setText("Nama Pasien");
        tambahDataPasien.getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 140, -1));

        lock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pendaftaran/Asset/lock.png"))); // NOI18N
        tambahDataPasien.getContentPane().add(lock, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 95, -1, -1));

        txtNopas.setEditable(false);
        txtNopas.setBackground(new java.awt.Color(204, 204, 204));
        txtNopas.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtNopas.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNopas.setToolTipText("Nomor Pasien");
        txtNopas.setActionCommand("<Not Set>");
        txtNopas.setAlignmentX(1.0F);
        txtNopas.setAlignmentY(1.0F);
        txtNopas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 174, 152), 2, true));
        txtNopas.setCaretColor(new java.awt.Color(30, 174, 152));
        txtNopas.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNopas.setSelectedTextColor(new java.awt.Color(255, 204, 0));
        txtNopas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNopasActionPerformed(evt);
            }
        });
        tambahDataPasien.getContentPane().add(txtNopas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 280, 30));

        NIP.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        NIP.setForeground(new java.awt.Color(30, 174, 152));
        NIP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pendaftaran/Asset/nopasIcon.png"))); // NOI18N
        NIP.setText("Nomor Pasien");
        tambahDataPasien.getContentPane().add(NIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 180, -1));

        header1.setBackground(new Color(0,0,0,0));
        header1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pendaftaran/Asset/headerTambah.png"))); // NOI18N
        tambahDataPasien.getContentPane().add(header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 30));

        bg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/BgEditPegawai.png"))); // NOI18N
        bg1.setToolTipText("");
        tambahDataPasien.getContentPane().add(bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 520));

        editDataPas.setBackground(new java.awt.Color(255, 255, 255));
        editDataPas.setUndecorated(true);
        editDataPas.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                editDataPasWindowOpened(evt);
            }
        });
        editDataPas.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MIN3.setBackground(new Color(0,0,0,0));
        MIN3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/-Off.png"))); // NOI18N
        MIN3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MIN3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Min.png"))); // NOI18N
        MIN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIN3ActionPerformed(evt);
            }
        });
        editDataPas.getContentPane().add(MIN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 30, 30));

        MAX3.setBackground(new Color(0,0,0,0));
        MAX3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/maxOff.png"))); // NOI18N
        MAX3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MAX3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Max.png"))); // NOI18N
        MAX3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAX3ActionPerformed(evt);
            }
        });
        editDataPas.getContentPane().add(MAX3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 30, 30));

        CLOSE3.setBackground(new Color(0,0,0,0));
        CLOSE3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/xOff.png"))); // NOI18N
        CLOSE3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CLOSE3.setBorderPainted(false);
        CLOSE3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CLOSE3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Close.png"))); // NOI18N
        CLOSE3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLOSE3ActionPerformed(evt);
            }
        });
        editDataPas.getContentPane().add(CLOSE3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 30, 30));

        btnBatal1.setBackground(new Color (0,0,0,0));
        btnBatal1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnBatal1.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/TmblBatal.png"))); // NOI18N
        btnBatal1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBatal1.setBorderPainted(false);
        btnBatal1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/TmblBatalAktif.png"))); // NOI18N
        btnBatal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatal1ActionPerformed(evt);
            }
        });
        editDataPas.getContentPane().add(btnBatal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 130, -1));

        btnSimpan1.setBackground(new Color (0,0,0,0));
        btnSimpan1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnSimpan1.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/tmblSimpan.png"))); // NOI18N
        btnSimpan1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSimpan1.setBorderPainted(false);
        btnSimpan1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/tmblSimpanAktif.png"))); // NOI18N
        btnSimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpan1ActionPerformed(evt);
            }
        });
        editDataPas.getContentPane().add(btnSimpan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, 130, -1));

        buttonGroup1.add(PerempuanEdit);
        PerempuanEdit.setText("Perempuan");
        editDataPas.getContentPane().add(PerempuanEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        buttonGroup1.add(lakiedit);
        lakiedit.setText("Laki - Laki");
        lakiedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakieditActionPerformed(evt);
            }
        });
        editDataPas.getContentPane().add(lakiedit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, -1));

        txtAlamatEdit.setColumns(20);
        txtAlamatEdit.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtAlamatEdit.setRows(5);
        txtAlamatEdit.setToolTipText("Alamat Pasien");
        txtAlamatEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 174, 152), 2, true));
        txtAlamatEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtAlamat1.setViewportView(txtAlamatEdit);

        editDataPas.getContentPane().add(txtAlamat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 280, 100));

        alamat1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        alamat1.setForeground(new java.awt.Color(30, 174, 152));
        alamat1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/entypo_address.png"))); // NOI18N
        alamat1.setText("Alamat");
        editDataPas.getContentPane().add(alamat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 140, -1));

        txtRegis.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtRegis.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtRegis.setToolTipText("Username");
        txtRegis.setAlignmentX(1.0F);
        txtRegis.setAlignmentY(1.0F);
        txtRegis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 174, 152), 2));
        txtRegis.setCaretColor(new java.awt.Color(30, 174, 152));
        txtRegis.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRegisActionPerformed(evt);
            }
        });
        editDataPas.getContentPane().add(txtRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 280, 30));

        TglRegis.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        TglRegis.setForeground(new java.awt.Color(30, 174, 152));
        TglRegis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pendaftaran/Asset/tglregisicon.png"))); // NOI18N
        TglRegis.setText("Tanggal Registrasi");
        editDataPas.getContentPane().add(TglRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 170, -1));

        pilihanTglLhrEdit.setToolTipText("Tanggal Lahir Pasien");
        pilihanTglLhrEdit.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                pilihanTglLhrEditPropertyChange(evt);
            }
        });
        editDataPas.getContentPane().add(pilihanTglLhrEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 280, -1));

        Tgllahir1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Tgllahir1.setForeground(new java.awt.Color(30, 174, 152));
        Tgllahir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/Group.png"))); // NOI18N
        Tgllahir1.setText("Tanggal Lahir");
        editDataPas.getContentPane().add(Tgllahir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 140, -1));

        txtTelpEdit.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtTelpEdit.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTelpEdit.setToolTipText("Username");
        txtTelpEdit.setAlignmentX(1.0F);
        txtTelpEdit.setAlignmentY(1.0F);
        txtTelpEdit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 174, 152), 2));
        txtTelpEdit.setCaretColor(new java.awt.Color(30, 174, 152));
        txtTelpEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTelpEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelpEditActionPerformed(evt);
            }
        });
        editDataPas.getContentPane().add(txtTelpEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 280, 30));

        Telepon1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Telepon1.setForeground(new java.awt.Color(30, 174, 152));
        Telepon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/bi_telephone-fill.png"))); // NOI18N
        Telepon1.setText("Telepon");
        editDataPas.getContentPane().add(Telepon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 140, -1));

        jnsKelamin1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jnsKelamin1.setForeground(new java.awt.Color(30, 174, 152));
        jnsKelamin1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/fa-solid_transgender.png"))); // NOI18N
        jnsKelamin1.setText("Jenis Kelamin");
        editDataPas.getContentPane().add(jnsKelamin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 140, -1));

        lock1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pendaftaran/Asset/lock.png"))); // NOI18N
        editDataPas.getContentPane().add(lock1, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 95, -1, -1));

        txtNamaEdit.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtNamaEdit.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNamaEdit.setToolTipText("Nama Pasie");
        txtNamaEdit.setAlignmentX(1.0F);
        txtNamaEdit.setAlignmentY(1.0F);
        txtNamaEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 174, 152), 2, true));
        txtNamaEdit.setCaretColor(new java.awt.Color(30, 174, 152));
        txtNamaEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNamaEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaEditActionPerformed(evt);
            }
        });
        editDataPas.getContentPane().add(txtNamaEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 280, 30));

        nama1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        nama1.setForeground(new java.awt.Color(30, 174, 152));
        nama1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/mdi_account.png"))); // NOI18N
        nama1.setText("Nama Pasien");
        editDataPas.getContentPane().add(nama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 140, -1));

        txtNopasEdit.setEditable(false);
        txtNopasEdit.setBackground(new java.awt.Color(204, 204, 204));
        txtNopasEdit.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtNopasEdit.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtNopasEdit.setToolTipText("Nomor Pasien");
        txtNopasEdit.setAlignmentX(1.0F);
        txtNopasEdit.setAlignmentY(1.0F);
        txtNopasEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 174, 152), 2, true));
        txtNopasEdit.setCaretColor(new java.awt.Color(30, 174, 152));
        txtNopasEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNopasEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNopasEditActionPerformed(evt);
            }
        });
        editDataPas.getContentPane().add(txtNopasEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 280, 30));

        NIP1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        NIP1.setForeground(new java.awt.Color(30, 174, 152));
        NIP1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pendaftaran/Asset/nopasIcon.png"))); // NOI18N
        NIP1.setText("Nomor Pasien");
        editDataPas.getContentPane().add(NIP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 180, -1));

        header2.setBackground(new Color(0,0,0,0));
        header2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pendaftaran/Asset/headerEdit.png"))); // NOI18N
        editDataPas.getContentPane().add(header2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 30));

        bg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/BgEditPegawai.png"))); // NOI18N
        bg2.setToolTipText("");
        editDataPas.getContentPane().add(bg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 520));

        PopupSearch.setUndecorated(true);
        PopupSearch.setOpacity(0.0F);
        PopupSearch.setResizable(false);
        PopupSearch.setSize(new java.awt.Dimension(251, 116));
        PopupSearch.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                PopupSearchWindowOpened(evt);
            }
        });
        PopupSearch.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CLOSE6.setBackground(new Color(0,0,0,0));
        CLOSE6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/xOff.png"))); // NOI18N
        CLOSE6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CLOSE6.setBorderPainted(false);
        CLOSE6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CLOSE6.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Close.png"))); // NOI18N
        CLOSE6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLOSE6ActionPerformed(evt);
            }
        });
        PopupSearch.getContentPane().add(CLOSE6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 30, 30));

        txtCari.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtCari.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCari.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 173, 152), 2, true));
        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        PopupSearch.getContentPane().add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 170, 30));

        cari.setBackground(new Color(0,0,0,0));
        cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/SearchAktif.png"))); // NOI18N
        cari.setBorder(null);
        cari.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search.png"))); // NOI18N
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        PopupSearch.getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, 50));

        titleSearch.setFont(new java.awt.Font("SansSerif", 2, 11)); // NOI18N
        titleSearch.setForeground(new java.awt.Color(255, 255, 255));
        titleSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleSearch.setText("Search");
        PopupSearch.getContentPane().add(titleSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 30));

        bg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPembayaran/Asset/SearchPopup.png"))); // NOI18N
        PopupSearch.getContentPane().add(bg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 730));
        setUndecorated(true);
        setOpacity(0.0F);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDelete.setBackground(new Color(0,0,0,0));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/delete.png"))); // NOI18N
        btnDelete.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDelete.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/deleteaktif.png"))); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 350, 90, 80));

        btnEdit.setBackground(new Color(0,0,0,0));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/edit.png"))); // NOI18N
        btnEdit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnEdit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/editaktif.png"))); // NOI18N
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 270, 90, 80));

        btnInput.setBackground(new Color(0,0,0,0));
        btnInput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/input.png"))); // NOI18N
        btnInput.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnInput.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/inputaktif.png"))); // NOI18N
        btnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputActionPerformed(evt);
            }
        });
        getContentPane().add(btnInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 190, 90, 80));

        MIN.setBackground(new Color(0,0,0,0));
        MIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/-Off.png"))); // NOI18N
        MIN.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MIN.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Min.png"))); // NOI18N
        MIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MINActionPerformed(evt);
            }
        });
        getContentPane().add(MIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 0, 30, 30));

        MAX.setBackground(new Color(0,0,0,0));
        MAX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/maxOff.png"))); // NOI18N
        MAX.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MAX.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Max.png"))); // NOI18N
        getContentPane().add(MAX, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 0, 30, 30));

        CLOSE.setBackground(new Color(0,0,0,0));
        CLOSE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/xOff.png"))); // NOI18N
        CLOSE.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CLOSE.setBorderPainted(false);
        CLOSE.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CLOSE.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Close.png"))); // NOI18N
        CLOSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLOSEActionPerformed(evt);
            }
        });
        getContentPane().add(CLOSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 0, 30, 30));

        btnPembayaran.setBackground(new Color(0,0,0,0));
        btnPembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/pembayaran.png"))); // NOI18N
        btnPembayaran.setBorder(null);
        btnPembayaran.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/PembayaranAktif.png"))); // NOI18N
        btnPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembayaranActionPerformed(evt);
            }
        });
        getContentPane().add(btnPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 588, -1, -1));

        btnObat.setBackground(new Color(0,0,0,0));
        btnObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Obat.png"))); // NOI18N
        btnObat.setBorder(null);
        btnObat.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/ObatAktif.png"))); // NOI18N
        btnObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObatActionPerformed(evt);
            }
        });
        getContentPane().add(btnObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 514, -1, -1));

        btnJadwalPraktek.setBackground(new Color(0,0,0,0));
        btnJadwalPraktek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/JadwalPraktek.png"))); // NOI18N
        btnJadwalPraktek.setBorder(null);
        btnJadwalPraktek.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/JadwalPraktekAktif.png"))); // NOI18N
        btnJadwalPraktek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalPraktekActionPerformed(evt);
            }
        });
        getContentPane().add(btnJadwalPraktek, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 440, -1, -1));

        btnPemeriksaan.setBackground(new Color(0,0,0,0));
        btnPemeriksaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Pemeriksaan.png"))); // NOI18N
        btnPemeriksaan.setBorder(null);
        btnPemeriksaan.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/PemeriksaanAktif.png"))); // NOI18N
        btnPemeriksaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPemeriksaanActionPerformed(evt);
            }
        });
        getContentPane().add(btnPemeriksaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 366, -1, -1));

        btnPoli.setBackground(new Color(0,0,0,0));
        btnPoli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Poli.png"))); // NOI18N
        btnPoli.setBorder(null);
        btnPoli.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/PoliAktif.png"))); // NOI18N
        btnPoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoliActionPerformed(evt);
            }
        });
        getContentPane().add(btnPoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 292, -1, -1));

        btnDokter.setBackground(new Color(0,0,0,0));
        btnDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Dokter.png"))); // NOI18N
        btnDokter.setBorder(null);
        btnDokter.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/DokterAktif.png"))); // NOI18N
        btnDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDokterActionPerformed(evt);
            }
        });
        getContentPane().add(btnDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 218, -1, -1));

        btnPegawai.setBackground(new Color(0,0,0,0));
        btnPegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Pegawai.png"))); // NOI18N
        btnPegawai.setBorder(null);
        btnPegawai.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/PegawaiAktif.png"))); // NOI18N
        btnPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPegawaiActionPerformed(evt);
            }
        });
        getContentPane().add(btnPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 144, -1, -1));

        btnPendaftaran.setBackground(new Color(0,0,0,0));
        btnPendaftaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Pendaftaran.png"))); // NOI18N
        btnPendaftaran.setBorder(null);
        btnPendaftaran.setSelected(true);
        btnPendaftaran.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/PendaftaranAktif.png"))); // NOI18N
        btnPendaftaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendaftaranActionPerformed(evt);
            }
        });
        getContentPane().add(btnPendaftaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 70, -1, -1));

        btnSubPendaftaran.setBackground(new Color(0,0,0,0));
        btnSubPendaftaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pendaftaran/Asset/subPendaftaran.png"))); // NOI18N
        btnSubPendaftaran.setBorder(null);
        btnSubPendaftaran.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Pendaftaran/Asset/SubPendaftaranAktif.png"))); // NOI18N
        btnSubPendaftaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubPendaftaranActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubPendaftaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 196, -1, 40));

        btnSubDataPasien.setBackground(new Color(0,0,0,0));
        btnSubDataPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pendaftaran/Asset/SubDatapasien.png"))); // NOI18N
        btnSubDataPasien.setBorder(null);
        btnSubDataPasien.setSelected(true);
        btnSubDataPasien.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Pendaftaran/Asset/SubDatapasienAktif.png"))); // NOI18N
        btnSubDataPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubDataPasienActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubDataPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 147, -1, 40));

        Search.setBackground(new Color(0,0,0,0));
        Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPembayaran/Asset/Search.png"))); // NOI18N
        Search.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Search.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Search.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPembayaran/Asset/seachAktif.png"))); // NOI18N
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SearchMouseEntered(evt);
            }
        });
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 165, 150, 80));

        btnHome.setBackground(new Color(0,0,0,0));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hospital.png"))); // NOI18N
        btnHome.setToolTipText("Home");
        btnHome.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hospitalAktif.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 20, -1, -1));

        Title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pendaftaran/Asset/titledatapasien.png"))); // NOI18N
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 93, -1, -1));

        navi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/navi.png"))); // NOI18N
        getContentPane().add(navi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/header.png"))); // NOI18N
        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnUser.setBackground(new Color(0,0,0,0));
        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/akun.png"))); // NOI18N
        btnUser.setToolTipText("Log Out");
        btnUser.setBorder(null);
        btnUser.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/akun1.png"))); // NOI18N
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 34, -1, -1));

        txtUser.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtUser.setText("Hi!, User");
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 40, 200, 20));

        userPanel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        userPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dokter/Asset/Acc (1).png"))); // NOI18N
        userPanel.setToolTipText("");
        getContentPane().add(userPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 27, -1, -1));

        TableDataPasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableDataPasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableDataPasienMouseClicked(evt);
            }
        });
        Table.setViewportView(TableDataPasien);

        getContentPane().add(Table, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 237, 830, 430));

        BgPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/panel.png"))); // NOI18N
        BgPanel.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(BgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 171, 980, -1));

        BgSubMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BgSubMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pendaftaran/Asset/SubMenu.png"))); // NOI18N
        BgSubMenu.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BgSubMenu.setPreferredSize(new java.awt.Dimension(150, 651));
        getContentPane().add(BgSubMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 65, 160, 650));

        editDataPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/bgmenupegawai.png"))); // NOI18N
        getContentPane().add(editDataPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tampilData(){
        //untuk mengahapus baris setelah input
        int row = TableDataPasien.getRowCount();
        for(int a = 0 ; a < row ; a++){
            table.removeRow(0);
        }
        
        String query = 
                "SELECT NoPasien,NamaPas,AlmPas,TelpPas,TglLahirPas,JenisKelPas,TglRegistrasi FROM pasien ORDER BY NoPasien";
                
        
        try{
            Connection connect = Koneksi.Koneksi.getKoneksi();//memanggil koneksi
            Statement sttmnt = connect.createStatement();//membuat statement
            ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
            
            while (rslt.next()){
                //menampung data sementara
                   
                    String noPas = rslt.getString("NoPasien");
                    String namapas = rslt.getString("NamaPas");
                    String alamat = rslt.getString("AlmPas");
                    String tlp = rslt.getString("TelpPas");
                    String tgllhr = rslt.getString("TglLahirPas");
                    String jnskel = rslt.getString("JenisKelPas");
                    String tglregis = rslt.getString("TglRegistrasi");
                    
                    
                //masukan semua data kedalam array
                String[] data = {noPas,namapas,alamat,tlp,tgllhr,jnskel,tglregis};
                //menambahakan baris sesuai dengan data yang tersimpan diarray
                table.addRow(data);
            }
                //mengeset nilai yang ditampung agar muncul di table
                TableDataPasien.setModel(table);
            
        }catch(Exception e){
            System.out.println(e);
        }
       
    }
    
    private void hapusData(){
        //ambill data no pendaftaran
           
        Connection connect = Koneksi.Koneksi.getKoneksi();
        int baris = TableDataPasien.getSelectedRow();
        int jawab;
        String kode = table.getValueAt(baris,0).toString();
        
        String query = "DELETE FROM pasien WHERE NoPasien = '"+kode+"';";
        try{
            if ((jawab = JOptionPane.showConfirmDialog(null, "Ingin menghapus data?", "konfirmasi", JOptionPane.YES_NO_OPTION)) == 0) {
            PreparedStatement ps = (PreparedStatement) connect.prepareStatement(query);
            ps.execute();
            JOptionPane.showMessageDialog(null , "Data Berhasil Dihapus");
        }
        }catch(SQLException | HeadlessException e){
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Data Gagal Dihapus");
        }finally{
            tampilData();
        }
        
    }
    
    private void tambahData(){
        jk_Laki.setActionCommand("L");
        jk_perempuan.setActionCommand("P");
        
        String nopas = txtNopas.getText();
        String nama = txtNama.getText();
        String jnsklm = btngroupJK.getSelection().getActionCommand();
        String tlp = txtTelp.getText();
        String tgllhr = pilihanTglLhr.getDateFormatString();
        String alamat = txtAlamat.getText();
        
        
        Connection connect = Koneksi.Koneksi.getKoneksi();
        String tglRegis = "SELECT DATE_FORMAT(NOW(), '%Y-%m-%d') AS tanggal";
        try{
            Statement sttmnt = connect.createStatement();//membuat statement
            ResultSet rslt = sttmnt.executeQuery(tglRegis);//menjalanakn query
            
            while (rslt.next()){
                //menampung data sementara
                   
                    tglREGISTRASI = rslt.getString("tanggal");
                                    
            }
        }catch(Exception e){
            System.out.println(e);
        }
        
        String query = "INSERT INTO pasien (NoPasien, NamaPas, AlmPas, TelpPas, TglLahirPas, JenisKelPas, TglRegistrasi ) "
                         + "VALUES ('"+nopas+"', '"+nama+"','"+alamat+"', '"+tlp+"', '"+TGL_Lahir+"', '"+jnsklm+"', '"+tglREGISTRASI+"')";
        
                       
        try{
            PreparedStatement ps = (PreparedStatement) connect.prepareStatement(query);
            ps.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
        }catch(Exception e){
            System.out.println(e);
        }finally{
            tambahDataPasien.dispose();
            txtNopas.setText(null);
            txtNama.setText(null);
            btngroupJK.clearSelection();
            txtTelp.setText(null);
            pilihanTglLhr.setDate(null);
            txtAlamat.setText(null);
        }
    }
    
    String TGL_Lahir;
    public void tanggal(){
        if (pilihanTglLhr.getDate() != null){
            String pattern = "yyyy-MM-dd";
            SimpleDateFormat format = new SimpleDateFormat(pattern);
            TGL_Lahir = String.valueOf(format.format(pilihanTglLhr.getDate()));
            
        }
    }
    String TGL_Lahir1;
    public void tanggal2(){
        if (pilihanTglLhrEdit.getDate() != null){
            String pattern = "yyyy-MM-dd";
            SimpleDateFormat format = new SimpleDateFormat(pattern);
            TGL_Lahir1 = String.valueOf(format.format(pilihanTglLhrEdit.getDate()));
            
        }
    }
    
    private void LoadData(){      
        String query = "SELECT * FROM pasien WHERE NoPasien = '"+NoPasien+"' ";
        
        try{
            Connection connect = Koneksi.Koneksi.getKoneksi();//memanggil koneksi
            Statement sttmnt = connect.createStatement();//membuat statement
            ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
            
            while (rslt.next()){
                String nopas = rslt.getString("NoPasien");
                String namapas = rslt.getString("NamaPas");
                String alamat = rslt.getString("AlmPas");
                String tlp = rslt.getString("TelpPas");
                String tgllhr = rslt.getString("TglLahirPas");
                String jnskel = rslt.getString("JenisKelPas");
                String tglRegis = rslt.getString("TglRegistrasi");
                
                txtNopasEdit.setText(nopas);
                txtNamaEdit.setText(namapas);
                txtTelpEdit.setText(tlp);
//              pilihanTglLhrEdit.setDate(tgllhr);
                txtAlamatEdit.setText(alamat);
                if(jnskel.equals("L")){
                    lakiedit.setSelected(true);
                }else{
                    PerempuanEdit.setSelected(true);
                }
                txtRegis.setText(tglRegis);
                txtRegis.setEditable(false);
            } 
        }catch(Exception e){
            
            System.out.println(e);
        } 
    }
  
    private void UpdateData(){
        lakiedit.setActionCommand("L");
        PerempuanEdit.setActionCommand("P");
        
        String nopasedit = NoPasien;
        String namaedit = txtNamaEdit.getText();
        String jnsklmedit = buttonGroup1.getSelection().getActionCommand();
        String tlpedit = txtTelpEdit.getText();
        String tgllhredit = pilihanTglLhrEdit.getDateFormatString();
        String alamatedit = txtAlamatEdit.getText();
        String tglRegis = txtRegis.getText();
        txtRegis.setEditable(false);
                 
        Connection connect = Koneksi.Koneksi.getKoneksi();
        
            String query2 = "UPDATE pasien SET NoPasien = '"+nopasedit+"', NamaPas = '"+namaedit+"', AlmPas = '"+alamatedit+"', `TelpPas` = '"+tlpedit+"', `TglLahirPas` = '"+TGL_Lahir1+"', `JenisKelPas` = '"+jnsklmedit+"', `TglRegistrasi` = '"+tglRegis+"' "
                    + "WHERE NoPasien = '"+nopasedit+"';";
            

            try{
                PreparedStatement ps = (PreparedStatement) connect.prepareStatement(query2);
                ps.executeUpdate(query2);
                JOptionPane.showMessageDialog(null , "Data  Berhasil diUpdate");
            }catch(SQLException | HeadlessException e){
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "Data Gagal diUpdate");
            }finally{
                editDataPas.dispose();
                txtNopasEdit.setText(null);
                txtNamaEdit.setText(null);
                buttonGroup1.clearSelection();
                txtTelpEdit.setText(null);
                txtAlamatEdit.setText(null);
                txtRegis.setText(null);
                
                tampilData();
            }
    }
    
    private void kodepasienotomatis(){
        String query = "SELECT * FROM pasien ORDER BY NoPasien DESC ";
        try{
            Connection connect = Koneksi.Koneksi.getKoneksi();//memanggil koneksi
            Statement sttmnt = connect.createStatement();//membuat statement
            ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
            
            if (rslt.next()){
                String Nopas = rslt.getString("NoPasien").substring(3,6);
                String AN = "" + (Integer.parseInt(Nopas)+1);
                String NOL = "";
                if(AN.length()==1){
                    NOL = "000";
                }else if(AN.length()==2){
                    NOL = "00";
                }else if(AN.length()==3){
                    NOL = "0";
                }else if(AN.length()==4){
                    NOL = "";
                }
                txtNopas.setText("PA" + NOL + AN);
            }else{
                txtNopas.setText("PA0001");
            }
        rslt.close();
        connect.close();
        }catch(Exception e){
            System.out.println(e);
        }
    }
    private void cari(){
        int row = TableDataPasien.getRowCount();
        for(int a = 0 ; a < row ; a++){
            table.removeRow(0);
        }
        
        String cari = txtCari.getText();
        
        String query = "SELECT NoPasien,NamaPas,AlmPas,TelpPas,TglLahirPas,JenisKelPas,TglRegistrasi FROM pasien WHERE NamaPas LIKE '%"+cari+"%' ORDER BY NoPasien";
                
       try{
           Connection connect = Koneksi.Koneksi.getKoneksi();//memanggil koneksi
           Statement sttmnt = connect.createStatement();//membuat statement
           ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
           
           while (rslt.next()){
                //menampung data sementara
                   
                    String noPas = rslt.getString("NoPasien");
                    String namapas = rslt.getString("NamaPas");
                    String alamat = rslt.getString("AlmPas");
                    String tlp = rslt.getString("TelpPas");
                    String tgllhr = rslt.getString("TglLahirPas");
                    String jnskel = rslt.getString("JenisKelPas");
                    String tglregis = rslt.getString("TglRegistrasi");
                    
                    
                //masukan semua data kedalam array
                String[] data = {noPas,namapas,alamat,tlp,tgllhr,jnskel,tglregis};
                //menambahakan baris sesuai dengan data yang tersimpan diarray
                table.addRow(data);
            }
                //mengeset nilai yang ditampung agar muncul di table
                TableDataPasien.setModel(table);
           
        
        }catch(Exception e){
               System.out.println(e);
        }
    }
    private void MINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MINActionPerformed
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_MINActionPerformed

    private void CLOSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLOSEActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CLOSEActionPerformed

    private void btnPendaftaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendaftaranActionPerformed
        // TODO add your handling code here:
        new Pendaftaran.DataPasien().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnPendaftaranActionPerformed

    private void btnPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPegawaiActionPerformed
        // TODO add your handling code here:
        new MenuPegawai().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPegawaiActionPerformed

    private void btnDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDokterActionPerformed
        // TODO add your handling code here:
        new Dokter.MenuDokter().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDokterActionPerformed

    private void btnPoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoliActionPerformed
        // TODO add your handling code here:
        new MenuPoli.MenuPoli().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPoliActionPerformed

    private void btnPemeriksaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPemeriksaanActionPerformed
        // TODO add your handling code here:
        new MenuPemeriksaan.Pemeriksaan().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPemeriksaanActionPerformed

    private void btnJadwalPraktekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadwalPraktekActionPerformed
        // TODO add your handling code here:
        new MenuJadwal.MenuJadwal().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnJadwalPraktekActionPerformed

    private void btnObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObatActionPerformed
        // TODO add your handling code here:
        new MenuObat().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnObatActionPerformed

    private void btnPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembayaranActionPerformed
        // TODO add your handling code here:
        new MenuPembayaran.JenisBiaya().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPembayaranActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        editDataPas.setVisible(true);
        editDataPas.setBounds(450, 120, 600, 520);
        LoadData();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        hapusData();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        for(double i = 0.0; i <= 1.0; i = i + 0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(20);
            }
           catch(Exception e){
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void MIN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIN1ActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_MIN1ActionPerformed

    private void CLOSE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLOSE1ActionPerformed
        // TODO add your handling code here:
        txtNopas.setText(null);
        txtNama.setText(null);
        txtTelp.setText(null);
        txtAlamat.setText(null);
        btngroupJK.clearSelection();
        tambahDataPasien.dispose();
    }//GEN-LAST:event_CLOSE1ActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        txtNopas.setText(null);
        txtNama.setText(null);
        txtTelp.setText(null);
        txtAlamat.setText(null);
        btngroupJK.clearSelection();
        tambahDataPasien.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        tambahData();
        tampilData();

    }//GEN-LAST:event_btnSimpanActionPerformed

    private void pilihanTglLhrPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_pilihanTglLhrPropertyChange
        // TODO add your handling code here:
        tanggal();
    }//GEN-LAST:event_pilihanTglLhrPropertyChange

    private void jk_perempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jk_perempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jk_perempuanActionPerformed

    private void jk_LakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jk_LakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jk_LakiActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtNopasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNopasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNopasActionPerformed

    private void tambahDataPasienWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_tambahDataPasienWindowOpened
        // TODO add your handling code here:
        for(double i = 0.0; i <= 1.0; i = i + 0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
//            this.setOpacity(f);
            tambahDataPasien.setOpacity(f);
            try{
                Thread.sleep(20);
            }
           catch(Exception e){
            }
        }
    }//GEN-LAST:event_tambahDataPasienWindowOpened

    private void btnBatal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatal1ActionPerformed
        // TODO add your handling code here:
        editDataPas.dispose();
    }//GEN-LAST:event_btnBatal1ActionPerformed

    private void btnSimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpan1ActionPerformed
        // TODO add your handling code here:
        UpdateData();
        tampilData();
        editDataPas.dispose();
    }//GEN-LAST:event_btnSimpan1ActionPerformed

    private void txtTelpEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelpEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelpEditActionPerformed

    private void txtNamaEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaEditActionPerformed

    private void txtNopasEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNopasEditActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNopasEditActionPerformed

    private void pilihanTglLhrEditPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_pilihanTglLhrEditPropertyChange
        // TODO add your handling code here:
        tanggal2();
    }//GEN-LAST:event_pilihanTglLhrEditPropertyChange

    private void MIN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIN3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_MIN3ActionPerformed

    private void CLOSE3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLOSE3ActionPerformed
        // TODO add your handling code here:
        editDataPas.dispose();
    }//GEN-LAST:event_CLOSE3ActionPerformed

    private void MAX3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAX3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MAX3ActionPerformed

    private void lakieditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakieditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakieditActionPerformed

    private void editDataPasWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_editDataPasWindowOpened
        // TODO add your handling code here:
    }//GEN-LAST:event_editDataPasWindowOpened

    private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputActionPerformed
        // TODO add your handling code here:
        tambahDataPasien.setVisible(true);
        tambahDataPasien.setBounds(450, 120, 600, 520);
        kodepasienotomatis();
    }//GEN-LAST:event_btnInputActionPerformed

    private void txtRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRegisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRegisActionPerformed

    private void TableDataPasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableDataPasienMouseClicked
        // TODO add your handling code here:
        String kode = table.getValueAt(TableDataPasien.getSelectedRow(),0).toString();
        NoPasien = kode;
    }//GEN-LAST:event_TableDataPasienMouseClicked

    private void btnSubDataPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubDataPasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubDataPasienActionPerformed

    private void btnSubPendaftaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubPendaftaranActionPerformed
        // TODO add your handling code here:
        new Pendaftaran.DataPendaftaran().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSubPendaftaranActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        // TODO add your handling code here:
        int opsi = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan keluar?", "Log out!", JOptionPane.YES_NO_OPTION);
        if (opsi == JOptionPane.YES_OPTION){
            new Login.Login().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnUserActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        new MenuUtama().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void txtNamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNamaFocusGained
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_txtNamaFocusGained

    private void txtNamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNamaFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtNamaFocusLost

    private void txtAlamatFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAlamatFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtAlamatFocusGained

    private void txtAlamatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAlamatFocusLost
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtAlamatFocusLost

    private void txtNamaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtNamaPropertyChange
        // TODO add your handling code here:
//        txtNama.setText(txtNama.getText());
    }//GEN-LAST:event_txtNamaPropertyChange

    private void txtTelpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelpFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTelpFocusGained

    private void txtTelpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelpFocusLost
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtTelpFocusLost

    private void txtTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelpActionPerformed

    private void txtTelpPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtTelpPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelpPropertyChange

    private void SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseClicked
        //TODO add your handling code here:
        PopupSearch.setVisible(true);
        PopupSearch.setLocation(930, 250);
    }//GEN-LAST:event_SearchMouseClicked

    private void SearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchMouseEntered

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    private void CLOSE6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLOSE6ActionPerformed
        // TODO add your handling code here:
        tampilData();
        txtCari.setText(null);
        PopupSearch.setVisible(false);
    }//GEN-LAST:event_CLOSE6ActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
        cari();
        PopupSearch.setVisible(false);
    }//GEN-LAST:event_cariActionPerformed

    private void PopupSearchWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_PopupSearchWindowOpened
        // TODO add your handling code here:
        for(double i = 0.0; i <= 1.0; i = i + 0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            //            this.setOpacity(f);
            PopupSearch.setOpacity(f);
            try{
                Thread.sleep(20);
            }
            catch(Exception e){
            }
        }
    }//GEN-LAST:event_PopupSearchWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataPasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BgPanel;
    private javax.swing.JLabel BgSubMenu;
    private javax.swing.JButton CLOSE;
    private javax.swing.JButton CLOSE1;
    private javax.swing.JButton CLOSE3;
    private javax.swing.JButton CLOSE6;
    private javax.swing.JButton MAX;
    private javax.swing.JButton MAX1;
    private javax.swing.JButton MAX3;
    private javax.swing.JButton MIN;
    private javax.swing.JButton MIN1;
    private javax.swing.JButton MIN3;
    private javax.swing.JLabel NIP;
    private javax.swing.JLabel NIP1;
    private javax.swing.JRadioButton PerempuanEdit;
    private javax.swing.JDialog PopupSearch;
    private javax.swing.JButton Search;
    private javax.swing.JScrollPane Table;
    private javax.swing.JTable TableDataPasien;
    private javax.swing.JLabel Telepon;
    private javax.swing.JLabel Telepon1;
    private javax.swing.JLabel TglRegis;
    private javax.swing.JLabel Tgllahir;
    private javax.swing.JLabel Tgllahir1;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel alamat;
    private javax.swing.JLabel alamat1;
    private javax.swing.JLabel bg1;
    private javax.swing.JLabel bg2;
    private javax.swing.JLabel bg3;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnBatal1;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDokter;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnInput;
    private javax.swing.JButton btnJadwalPraktek;
    private javax.swing.JButton btnObat;
    private javax.swing.JButton btnPegawai;
    private javax.swing.JButton btnPembayaran;
    private javax.swing.JButton btnPemeriksaan;
    private javax.swing.JButton btnPendaftaran;
    private javax.swing.JButton btnPoli;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnSimpan1;
    private javax.swing.JButton btnSubDataPasien;
    private javax.swing.JButton btnSubPendaftaran;
    private javax.swing.JButton btnUser;
    private javax.swing.ButtonGroup btngroupJK;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cari;
    private javax.swing.JDialog editDataPas;
    private javax.swing.JLabel editDataPasien;
    private javax.swing.JLabel header;
    private javax.swing.JLabel header1;
    private javax.swing.JLabel header2;
    private javax.swing.JRadioButton jk_Laki;
    private javax.swing.JRadioButton jk_perempuan;
    private javax.swing.JLabel jnsKelamin;
    private javax.swing.JLabel jnsKelamin1;
    private javax.swing.JRadioButton lakiedit;
    private javax.swing.JLabel lock;
    private javax.swing.JLabel lock1;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nama1;
    private javax.swing.JLabel navi;
    private com.toedter.calendar.JDateChooser pilihanTglLhr;
    private com.toedter.calendar.JDateChooser pilihanTglLhrEdit;
    private javax.swing.JDialog tambahDataPasien;
    private javax.swing.JLabel titleSearch;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JScrollPane txtAlamat1;
    private javax.swing.JTextArea txtAlamatEdit;
    private javax.swing.JScrollPane txtAlamatscroll;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNamaEdit;
    private javax.swing.JTextField txtNopas;
    private javax.swing.JTextField txtNopasEdit;
    private javax.swing.JTextField txtRegis;
    private javax.swing.JTextField txtTelp;
    private javax.swing.JTextField txtTelpEdit;
    private javax.swing.JLabel txtUser;
    private javax.swing.JLabel userPanel;
    // End of variables declaration//GEN-END:variables
}
