/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MenuPemeriksaan;

import Dokter.*;
import Koneksi.GlobalVar;
import Koneksi.Koneksi;
import java.awt.Color;
import java.awt.Frame;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author donih
 */
public class Pemeriksaan extends javax.swing.JFrame {
    
    /**
     * Creates new form MenuUtama
     */
    String KodeResep;
    String KodePemeriksaan;
    int i = 0;
    String Nama;
    String Keluhn;
    String BeratB;
    String Tensid;
    String Tensis;
    String TGLPeriksa;
    DefaultTableModel table = new DefaultTableModel();
    DefaultTableModel table2 = new DefaultTableModel();
    DefaultTableModel table3 = new DefaultTableModel();
    public Pemeriksaan() {
        initComponents();
        txtUser.setText("Hi!, " + GlobalVar.nama);
        this.setBackground(new Color(0,0,0,0));
        
        TableRiwayat.setModel(table);
        table.addColumn("No");
        table.addColumn("Tanggal Pemeriksaan");
        table.addColumn("Nama Pasien");
        table.addColumn("Keluhan");
        table.addColumn("Berat Badan");
        table.addColumn("Tensi Diastolik");
        table.addColumn("Tensi Sistolik");
        TableResep.setModel(table2);
        table2.addColumn("No");
        table2.addColumn("Kode Obat");
        table2.addColumn("Nama Obat");
        table2.addColumn("Dosis");
        table2.addColumn("Jumlah");
        TableObat.setModel(table3);
        table3.addColumn("Kode");
        table3.addColumn("Nama");
        table3.addColumn("Merk");
        table3.addColumn("Stock");
        table3.addColumn("Harga");
        kodeotomatisResep();
        kodeotomatisPemeriksaan();
        TampilComboBox();
        if(GlobalVar.hak_akses.equals("Pegawai")){
            btnPegawai.setEnabled(false);
            btnDokter.setEnabled(false);
            btnPemeriksaan.setEnabled(false);
        }else if(GlobalVar.hak_akses.equals("Dokter")){
            btnPegawai.setEnabled(false);
            btnPendaftaran.setEnabled(false);
            btnDokter.setEnabled(false);
            btnPoli.setEnabled(false);
            btnObat.setEnabled(false);
            btnPembayaran.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnResep = new javax.swing.ButtonGroup();
        Obat = new javax.swing.JDialog();
        btnPilihBiaya = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableObat = new javax.swing.JTable();
        MIN2 = new javax.swing.JButton();
        MAX2 = new javax.swing.JButton();
        CLOSE4 = new javax.swing.JButton();
        JUMLAH = new javax.swing.JTextField();
        D1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        D2 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        header2 = new javax.swing.JLabel();
        DetailRiwayat = new javax.swing.JDialog();
        MIN3 = new javax.swing.JButton();
        MAX3 = new javax.swing.JButton();
        CLOSE5 = new javax.swing.JButton();
        Ts = new javax.swing.JLabel();
        Keluh = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Bb = new javax.swing.JLabel();
        Td = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TglRiwayat = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Namaa = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        header3 = new javax.swing.JLabel();
        bg3 = new javax.swing.JLabel();
        bg2 = new javax.swing.JLabel();
        MIN = new javax.swing.JButton();
        MAX = new javax.swing.JButton();
        CLOSE = new javax.swing.JButton();
        btnPembayaran = new javax.swing.JButton();
        btnObat = new javax.swing.JButton();
        btnJadwalPraktek = new javax.swing.JButton();
        btnPemeriksaan = new javax.swing.JButton();
        btnPoli = new javax.swing.JButton();
        btnDokter = new javax.swing.JButton();
        btnPegawai = new javax.swing.JButton();
        btnPendaftaran = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnUser = new javax.swing.JButton();
        NoPendaftaran = new javax.swing.JComboBox<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        Perawatan = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        Diagnosis = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        Keluhan = new javax.swing.JTextArea();
        BeratBadan = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        TensiD = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        TensiS = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        TableRiwayat = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableResep = new javax.swing.JTable();
        RBTidakPerl = new javax.swing.JRadioButton();
        RBPerlu = new javax.swing.JRadioButton();
        HapusResep = new javax.swing.JButton();
        TambahResep = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        txtUser = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        navi = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        Obat.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Obat.setUndecorated(true);
        Obat.setOpacity(0.0F);
        Obat.setSize(new java.awt.Dimension(600, 600));
        Obat.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                ObatWindowOpened(evt);
            }
        });
        Obat.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPilihBiaya.setBackground(new Color (0,0,0,0));
        btnPilihBiaya.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnPilihBiaya.setForeground(new java.awt.Color(255, 255, 255));
        btnPilihBiaya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pendaftaran/Asset/tmblSimpanAktif.png"))); // NOI18N
        btnPilihBiaya.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPilihBiaya.setBorderPainted(false);
        btnPilihBiaya.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/tmblSimpanAktif.png"))); // NOI18N
        btnPilihBiaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihBiayaActionPerformed(evt);
            }
        });
        Obat.getContentPane().add(btnPilihBiaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 170, -1));

        TableObat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TableObat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableObatMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableObat);

        Obat.getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 480, 260));

        MIN2.setBackground(new Color(0,0,0,0));
        MIN2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/-Off.png"))); // NOI18N
        MIN2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MIN2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Min.png"))); // NOI18N
        MIN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIN2ActionPerformed(evt);
            }
        });
        Obat.getContentPane().add(MIN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 30, 30));

        MAX2.setBackground(new Color(0,0,0,0));
        MAX2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/maxOff.png"))); // NOI18N
        MAX2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MAX2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Max.png"))); // NOI18N
        Obat.getContentPane().add(MAX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 30, 30));

        CLOSE4.setBackground(new Color(0,0,0,0));
        CLOSE4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/xOff.png"))); // NOI18N
        CLOSE4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CLOSE4.setBorderPainted(false);
        CLOSE4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CLOSE4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Close.png"))); // NOI18N
        CLOSE4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLOSE4ActionPerformed(evt);
            }
        });
        Obat.getContentPane().add(CLOSE4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 30, 30));

        JUMLAH.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        JUMLAH.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        JUMLAH.setToolTipText("");
        JUMLAH.setAlignmentX(1.0F);
        JUMLAH.setAlignmentY(1.0F);
        JUMLAH.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 174, 152), 2));
        JUMLAH.setCaretColor(new java.awt.Color(30, 174, 152));
        JUMLAH.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        JUMLAH.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JUMLAHFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JUMLAHFocusLost(evt);
            }
        });
        JUMLAH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JUMLAHActionPerformed(evt);
            }
        });
        Obat.getContentPane().add(JUMLAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 130, 30));

        D1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        D1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        D1.setToolTipText("");
        D1.setAlignmentX(1.0F);
        D1.setAlignmentY(1.0F);
        D1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 174, 152), 2));
        D1.setCaretColor(new java.awt.Color(30, 174, 152));
        D1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        D1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                D1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                D1FocusLost(evt);
            }
        });
        Obat.getContentPane().add(D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 50, 30));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setText("X");
        Obat.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));

        D2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        D2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        D2.setToolTipText("");
        D2.setAlignmentX(1.0F);
        D2.setAlignmentY(1.0F);
        D2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 174, 152), 2));
        D2.setCaretColor(new java.awt.Color(30, 174, 152));
        D2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        D2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                D2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                D2FocusLost(evt);
            }
        });
        Obat.getContentPane().add(D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 50, 30));

        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(30, 174, 152));
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/Asset/bx_bxs-user.png"))); // NOI18N
        jLabel23.setText("Jumlah");
        Obat.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        jLabel22.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(30, 174, 152));
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/Asset/bx_bxs-user.png"))); // NOI18N
        jLabel22.setText("Dosis");
        Obat.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        header2.setBackground(new Color(0,0,0,0));
        header2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pendaftaran/Asset/pilihdata.png"))); // NOI18N
        Obat.getContentPane().add(header2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 40));

        DetailRiwayat.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        DetailRiwayat.setUndecorated(true);
        DetailRiwayat.setOpacity(0.0F);
        DetailRiwayat.setSize(new java.awt.Dimension(600, 600));
        DetailRiwayat.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                DetailRiwayatWindowOpened(evt);
            }
        });
        DetailRiwayat.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MIN3.setBackground(new Color(0,0,0,0));
        MIN3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/-Off.png"))); // NOI18N
        MIN3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MIN3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Min.png"))); // NOI18N
        MIN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIN3ActionPerformed(evt);
            }
        });
        DetailRiwayat.getContentPane().add(MIN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 30, 30));

        MAX3.setBackground(new Color(0,0,0,0));
        MAX3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/maxOff.png"))); // NOI18N
        MAX3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MAX3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Max.png"))); // NOI18N
        DetailRiwayat.getContentPane().add(MAX3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 30, 30));

        CLOSE5.setBackground(new Color(0,0,0,0));
        CLOSE5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/xOff.png"))); // NOI18N
        CLOSE5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CLOSE5.setBorderPainted(false);
        CLOSE5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CLOSE5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Close.png"))); // NOI18N
        CLOSE5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLOSE5ActionPerformed(evt);
            }
        });
        DetailRiwayat.getContentPane().add(CLOSE5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 30, 30));

        Ts.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Ts.setText("[]");
        DetailRiwayat.getContentPane().add(Ts, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 110, 30));

        Keluh.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Keluh.setText("[]");
        DetailRiwayat.getContentPane().add(Keluh, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 150, 90));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel7.setText("Tensi Sistolik   :");
        DetailRiwayat.getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, 110, 30));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel8.setText("Berat Badan    :");
        DetailRiwayat.getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 110, 40));

        Bb.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Bb.setText("[]");
        DetailRiwayat.getContentPane().add(Bb, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 160, 40));

        Td.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Td.setText("[]");
        DetailRiwayat.getContentPane().add(Td, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 110, 30));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel5.setText("Tanggal Diperiksa");
        DetailRiwayat.getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 130, 40));

        TglRiwayat.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        TglRiwayat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TglRiwayat.setText("[]");
        DetailRiwayat.getContentPane().add(TglRiwayat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 200, 40));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel6.setText("Tensi Diastolik :");
        DetailRiwayat.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 110, 30));

        Namaa.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Namaa.setText("[]");
        DetailRiwayat.getContentPane().add(Namaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 160, 40));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setText("Nama               :");
        DetailRiwayat.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 110, 40));

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel9.setText("Keluhan           :");
        DetailRiwayat.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 110, 40));

        header3.setBackground(new Color(0,0,0,0));
        header3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPemeriksaan/Asset/Tambah Data (4).png"))); // NOI18N
        DetailRiwayat.getContentPane().add(header3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 30));

        bg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPemeriksaan/Asset/Detail Riwayat Pemeriksaan.png"))); // NOI18N
        bg3.setToolTipText("");
        DetailRiwayat.getContentPane().add(bg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 500));

        bg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/BgEditPegawai.png"))); // NOI18N
        bg2.setToolTipText("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        setOpacity(0.0F);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MIN.setBackground(new Color(0,0,0,0));
        MIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/-Off.png"))); // NOI18N
        MIN.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MIN.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Min.png"))); // NOI18N
        MIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MINActionPerformed(evt);
            }
        });
        getContentPane().add(MIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 0, 30, 30));

        MAX.setBackground(new Color(0,0,0,0));
        MAX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/maxOff.png"))); // NOI18N
        MAX.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MAX.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Max.png"))); // NOI18N
        getContentPane().add(MAX, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 0, 30, 30));

        CLOSE.setBackground(new Color(0,0,0,0));
        CLOSE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/xOff.png"))); // NOI18N
        CLOSE.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CLOSE.setBorderPainted(false);
        CLOSE.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CLOSE.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Close.png"))); // NOI18N
        CLOSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLOSEActionPerformed(evt);
            }
        });
        getContentPane().add(CLOSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 0, 30, 30));

        btnPembayaran.setBackground(new Color(0,0,0,0));
        btnPembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/pembayaran.png"))); // NOI18N
        btnPembayaran.setBorder(null);
        btnPembayaran.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/PembayaranAktif.png"))); // NOI18N
        btnPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembayaranActionPerformed(evt);
            }
        });
        getContentPane().add(btnPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 588, -1, -1));

        btnObat.setBackground(new Color(0,0,0,0));
        btnObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Obat.png"))); // NOI18N
        btnObat.setBorder(null);
        btnObat.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/ObatAktif.png"))); // NOI18N
        btnObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObatActionPerformed(evt);
            }
        });
        getContentPane().add(btnObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 514, -1, -1));

        btnJadwalPraktek.setBackground(new Color(0,0,0,0));
        btnJadwalPraktek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/JadwalPraktek.png"))); // NOI18N
        btnJadwalPraktek.setBorder(null);
        btnJadwalPraktek.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/JadwalPraktekAktif.png"))); // NOI18N
        btnJadwalPraktek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalPraktekActionPerformed(evt);
            }
        });
        getContentPane().add(btnJadwalPraktek, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 440, -1, -1));

        btnPemeriksaan.setBackground(new Color(0,0,0,0));
        btnPemeriksaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Pemeriksaan.png"))); // NOI18N
        btnPemeriksaan.setBorder(null);
        btnPemeriksaan.setSelected(true);
        btnPemeriksaan.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/PemeriksaanAktif.png"))); // NOI18N
        btnPemeriksaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPemeriksaanActionPerformed(evt);
            }
        });
        getContentPane().add(btnPemeriksaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 366, -1, -1));

        btnPoli.setBackground(new Color(0,0,0,0));
        btnPoli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Poli.png"))); // NOI18N
        btnPoli.setBorder(null);
        btnPoli.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/PoliAktif.png"))); // NOI18N
        btnPoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoliActionPerformed(evt);
            }
        });
        getContentPane().add(btnPoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 292, -1, -1));

        btnDokter.setBackground(new Color(0,0,0,0));
        btnDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Dokter.png"))); // NOI18N
        btnDokter.setBorder(null);
        btnDokter.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/DokterAktif.png"))); // NOI18N
        btnDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDokterActionPerformed(evt);
            }
        });
        getContentPane().add(btnDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 218, -1, -1));

        btnPegawai.setBackground(new Color(0,0,0,0));
        btnPegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Pegawai.png"))); // NOI18N
        btnPegawai.setBorder(null);
        btnPegawai.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/PegawaiAktif.png"))); // NOI18N
        btnPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPegawaiActionPerformed(evt);
            }
        });
        getContentPane().add(btnPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 144, -1, -1));

        btnPendaftaran.setBackground(new Color(0,0,0,0));
        btnPendaftaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Pendaftaran.png"))); // NOI18N
        btnPendaftaran.setBorder(null);
        btnPendaftaran.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/PendaftaranAktif.png"))); // NOI18N
        btnPendaftaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendaftaranActionPerformed(evt);
            }
        });
        getContentPane().add(btnPendaftaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 70, -1, -1));

        btnHome.setBackground(new Color(0,0,0,0));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hospital.png"))); // NOI18N
        btnHome.setToolTipText("Home");
        btnHome.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hospitalAktif.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 20, -1, -1));

        btnUser.setBackground(new Color(0,0,0,0));
        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/akun.png"))); // NOI18N
        btnUser.setToolTipText("Log Out");
        btnUser.setBorder(null);
        btnUser.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/akun1.png"))); // NOI18N
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 34, -1, -1));

        NoPendaftaran.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        NoPendaftaran.setBorder(null);
        NoPendaftaran.setPreferredSize(new java.awt.Dimension(5, 28));
        NoPendaftaran.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                NoPendaftaranItemStateChanged(evt);
            }
        });
        NoPendaftaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NoPendaftaranMouseClicked(evt);
            }
        });
        NoPendaftaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoPendaftaranActionPerformed(evt);
            }
        });
        getContentPane().add(NoPendaftaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 250, 260, 30));

        jScrollPane6.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jScrollPane6FocusGained(evt);
            }
        });

        Perawatan.setColumns(20);
        Perawatan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Perawatan.setRows(5);
        Perawatan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 174, 152), 2));
        Perawatan.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Perawatan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PerawatanFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PerawatanFocusLost(evt);
            }
        });
        jScrollPane6.setViewportView(Perawatan);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 420, 260, 40));

        jScrollPane5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jScrollPane5FocusGained(evt);
            }
        });

        Diagnosis.setColumns(20);
        Diagnosis.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Diagnosis.setRows(5);
        Diagnosis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 174, 152), 2));
        Diagnosis.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Diagnosis.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DiagnosisFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DiagnosisFocusLost(evt);
            }
        });
        jScrollPane5.setViewportView(Diagnosis);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 360, 260, 40));

        jScrollPane4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jScrollPane4FocusGained(evt);
            }
        });

        Keluhan.setColumns(20);
        Keluhan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Keluhan.setRows(5);
        Keluhan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 174, 152), 2));
        Keluhan.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Keluhan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                KeluhanFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                KeluhanFocusLost(evt);
            }
        });
        jScrollPane4.setViewportView(Keluhan);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 300, 260, 40));

        BeratBadan.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        BeratBadan.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        BeratBadan.setToolTipText("");
        BeratBadan.setAlignmentX(1.0F);
        BeratBadan.setAlignmentY(1.0F);
        BeratBadan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 174, 152), 2));
        BeratBadan.setCaretColor(new java.awt.Color(30, 174, 152));
        BeratBadan.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        BeratBadan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BeratBadanFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                BeratBadanFocusLost(evt);
            }
        });
        getContentPane().add(BeratBadan, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 480, 210, 30));

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(30, 174, 152));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPemeriksaan/Asset/medical-icon_outpatient.png"))); // NOI18N
        jLabel13.setText("Keluhan");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, -1, -1));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(30, 174, 152));
        jLabel12.setText("KG");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 480, -1, 30));

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(30, 174, 152));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPemeriksaan/Asset/medical-icon_intensive-care.png"))); // NOI18N
        jLabel14.setText("Diagnosa");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 370, -1, -1));

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(30, 174, 152));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPemeriksaan/Asset/medical-icon_intensive-care.png"))); // NOI18N
        jLabel15.setText("Perawatan");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, -1, -1));

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(30, 174, 152));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPemeriksaan/Asset/carbon_add-filled.png"))); // NOI18N
        jLabel16.setText("Tambah Resep ?");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 430, -1, -1));

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(30, 174, 152));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPemeriksaan/Asset/fa-solid_weight.png"))); // NOI18N
        jLabel17.setText("Berat Badan");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 480, -1, -1));

        TensiD.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        TensiD.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TensiD.setToolTipText("");
        TensiD.setAlignmentX(1.0F);
        TensiD.setAlignmentY(1.0F);
        TensiD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 174, 152), 2));
        TensiD.setCaretColor(new java.awt.Color(30, 174, 152));
        TensiD.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TensiD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TensiDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TensiDFocusLost(evt);
            }
        });
        getContentPane().add(TensiD, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 530, 210, 30));

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(30, 174, 152));
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPemeriksaan/Asset/la_file-medical-alt.png"))); // NOI18N
        jLabel18.setText("Tensi Diastolik");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 530, -1, -1));

        TensiS.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        TensiS.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        TensiS.setToolTipText("");
        TensiS.setAlignmentX(1.0F);
        TensiS.setAlignmentY(1.0F);
        TensiS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 174, 152), 2));
        TensiS.setCaretColor(new java.awt.Color(30, 174, 152));
        TensiS.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TensiS.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TensiSFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TensiSFocusLost(evt);
            }
        });
        getContentPane().add(TensiS, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 580, 210, 30));

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(30, 174, 152));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPemeriksaan/Asset/la_file-medical-alt.png"))); // NOI18N
        jLabel19.setText("Tensi Sistolik");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 580, -1, -1));

        TableRiwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableRiwayat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableRiwayatMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TableRiwayatMousePressed(evt);
            }
        });
        jScrollPane7.setViewportView(TableRiwayat);

        getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 460, 120));

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(30, 174, 152));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPemeriksaan/Asset/fluent_book-number-16-filled.png"))); // NOI18N
        jLabel20.setText("No Pendaftran");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 250, -1, -1));

        jLabel21.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(30, 174, 152));
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPemeriksaan/Asset/fa-solid_clipboard-list.png"))); // NOI18N
        jLabel21.setText("Riwayat Pemeriksaan");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, -1, -1));

        TableResep.setAutoCreateRowSorter(true);
        TableResep.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableResep);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 400, 100));

        btnResep.add(RBTidakPerl);
        RBTidakPerl.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        RBTidakPerl.setText("Tidak");
        RBTidakPerl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBTidakPerlActionPerformed(evt);
            }
        });
        getContentPane().add(RBTidakPerl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, -1, -1));

        btnResep.add(RBPerlu);
        RBPerlu.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        RBPerlu.setText("Ya");
        RBPerlu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBPerluActionPerformed(evt);
            }
        });
        getContentPane().add(RBPerlu, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, -1, -1));

        HapusResep.setBackground(new Color(0,0,0,0));
        HapusResep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPemeriksaan/Asset/Group 19.png"))); // NOI18N
        HapusResep.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        HapusResep.setBorderPainted(false);
        HapusResep.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        HapusResep.setEnabled(false);
        HapusResep.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPemeriksaan/Asset/Group 18.png"))); // NOI18N
        HapusResep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusResepActionPerformed(evt);
            }
        });
        getContentPane().add(HapusResep, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 540, 50, 50));

        TambahResep.setBackground(new Color(0,0,0,0));
        TambahResep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPemeriksaan/Asset/Group 17.png"))); // NOI18N
        TambahResep.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TambahResep.setBorderPainted(false);
        TambahResep.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TambahResep.setEnabled(false);
        TambahResep.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPemeriksaan/Asset/Group 16 (1).png"))); // NOI18N
        TambahResep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahResepActionPerformed(evt);
            }
        });
        getContentPane().add(TambahResep, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 490, 50, 50));

        btnBatal.setBackground(new Color (0,0,0,0));
        btnBatal.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/TmblBatal.png"))); // NOI18N
        btnBatal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBatal.setBorderPainted(false);
        btnBatal.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/TmblBatalAktif.png"))); // NOI18N
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 620, 130, -1));

        btnSimpan.setBackground(new Color (0,0,0,0));
        btnSimpan.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/tmblSimpan.png"))); // NOI18N
        btnSimpan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSimpan.setBorderPainted(false);
        btnSimpan.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/tmblSimpanAktif.png"))); // NOI18N
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 620, 130, -1));

        txtUser.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtUser.setText("Hi!, User");
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 40, 200, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dokter/Asset/Acc (1).png"))); // NOI18N
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 27, -1, -1));

        navi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/navi.png"))); // NOI18N
        getContentPane().add(navi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/header.png"))); // NOI18N
        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPemeriksaan/Asset/Tambah Data (3).png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void SimpanData(){
        String NoPen = NoPendaftaran.getSelectedItem().toString().substring(0,5);
        String Keluhan = this.Keluhan.getText();
        String diagn = Diagnosis.getText();
        String prwt = Perawatan.getText();
        String BB = BeratBadan.getText();
        String TD = TensiD.getText();
        String TS = TensiS.getText();
        
        Connection connect = Koneksi.getKoneksi();
            //query untuk memasukan data
        String query2 = "INSERT INTO pemeriksaan (NoPemeriksaan, NoPendaftaran, KodeDokter, Keluhan, Diagnosa,Perawatan,BeratBadan,TensiDiastolik,TensiSistolik) "+"VALUES ('"+KodePemeriksaan+"','"+NoPen+"','"+GlobalVar.id_user+"','"+Keluhan+"','"+diagn+"','"+prwt+"','"+BB+"','"+TD+"','"+TS+"')";
        try{
                //menyiapkan statement untuk di eksekusi

                PreparedStatement ps = (PreparedStatement) connect.prepareStatement(query2);
                ps.executeUpdate(query2);
                if (RBPerlu.isSelected()==true) {
                    String query3 = "INSERT INTO resep (NoResep,NoPemeriksaan) "
                                 + "VALUES ('"+KodeResep+"', '"+KodePemeriksaan+"')";
                    
                    try{
                            //menyiapkan statement untuk di eksekusi
                        PreparedStatement ps3 = (PreparedStatement) connect.prepareStatement(query3);
                        ps3.executeUpdate(query3);
                        for(int a = 0;a<TableResep.getColumnCount();a++){
                            String KodeObat = TableResep.getValueAt(a, 1).toString();
                            String Dosis = TableResep.getValueAt(a, 3).toString();
                            String Jumlah = TableResep.getValueAt(a, 4).toString();
                            String query4 = "INSERT INTO detail_resep (NoResep, KodeObat,Dosis,Jumlah) "
                                     + "VALUES ('"+KodeResep+"', '"+KodeObat+"', '"+Dosis+"', '"+Jumlah+"')";
                            try{
                                //menyiapkan statement untuk di eksekusi
                                PreparedStatement ps4 = (PreparedStatement) connect.prepareStatement(query4);
                                ps4.executeUpdate(query4);
                            }catch(SQLException | HeadlessException e){
                                System.out.println(e);
                            }
                        }
                    }catch(SQLException | HeadlessException e){
                        System.out.println(e);
                   }
                }
            }catch(SQLException | HeadlessException e){
                System.out.println(e);
                JOptionPane.showMessageDialog(null,"Data Gagal Disimpan");
            }finally{
                JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
                this.Keluhan.setText(null);
                Diagnosis.setText(null);
                Perawatan.setText(null);
                BeratBadan.setText(null);
                TensiD.setText(null);
                TensiS.setText(null);
            }
    }
    private void TampilComboBox(){      
        String query = "SELECT NoPendaftaran,NamaPas FROM pendaftaran INNER JOIN pasien ON pendaftaran.NoPasien = pasien.NoPasien\n" +
        "WHERE TglPendaftaran = CURDATE()";
        
        try{
            Connection connect = Koneksi.getKoneksi();//memanggil koneksi
            Statement sttmnt = connect.createStatement();//membuat statement
            ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
            
            while (rslt.next()){
                String no = rslt.getString("NoPendaftaran");
                String nama = rslt.getString("NamaPas");
                NoPendaftaran.addItem(no + " " + nama);
                NoPendaftaran.setActionCommand(no);
            } 
        }catch(Exception e){
            
            System.out.println(e);
        } 
    }
    private void tampilDataRiwayat(){   
        //untuk mengahapus baris setelah input
        int row = TableRiwayat.getRowCount();
        for(int a = 0 ; a < row ; a++){
            table.removeRow(0);
        }
        
        String query = 
                "SELECT TglPendaftaran, NamaPas ,Keluhan, BeratBadan , TensiDiastolik ,TensiSistolik  FROM pemeriksaan\n" +
                "INNER JOIN pendaftaran ON pemeriksaan.NoPendaftaran = pendaftaran.NoPendaftaran \n" +
                "INNER JOIN pasien ON pendaftaran.NoPasien = pasien.NoPasien \n" +
                "WHERE Pendaftaran.NoPasien = pasien.NoPasien AND pemeriksaan.NoPendaftaran = '"+NoPendaftaran.getSelectedItem().toString().substring(0, 5)+"'";
                
        
        try{
            Connection connect = Koneksi.getKoneksi();//memanggil koneksi
            Statement sttmnt = connect.createStatement();//membuat statement
            ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
            int i = 1;
            while (rslt.next()){
                //menampung data sementara
                   
                   String tgl = rslt.getString("TglPendaftaran");
                    String Nama = rslt.getString("NamaPas");
                    String BB = rslt.getString("BeratBadan");
                    String Keluh = rslt.getString("Keluhan");
                    String TS = rslt.getString("TensiSistolik");
                    String TD = rslt.getString("TensiDiastolik");
                    
                    
                //masukan semua data kedalam array
                String[] data = {String.valueOf(i),tgl,Nama,Keluh,BB,TD,TS};
                //menambahakan baris sesuai dengan data yang tersimpan diarray
                table.addRow(data);
                i = i+1;
            }
                //mengeset nilai yang ditampung agar muncul di table
                TableRiwayat.setModel(table);
            
        }catch(Exception e){
            System.out.println(e);
        }
       
    }
    private void tampilDataObat(){
        //untuk mengahapus baris setelah input
        int row = TableObat.getRowCount();
        for(int a = 0 ; a < row ; a++){
            table.removeRow(0);
        }
        
        String query = 
                "SELECT * FROM obat ";
        
        try{
            Connection connect = Koneksi.getKoneksi();//memanggil koneksi
            Statement sttmnt = connect.createStatement();//membuat statement
            ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
            
            while (rslt.next()){
                //menampung data sementara
               Object[ ] obj = new Object[6];
                obj[0] = rslt.getString("KodeObat");
                obj[1] = rslt.getString("NmObat");
                obj[2] = rslt.getString("Merk");
                obj[3] = rslt.getInt("Stock");
                obj[4] = rslt.getInt("HargaJual");
                  
                //menambahakan baris sesuai dengan data yang tersimpan diarray
                table3.addRow(obj);
            }
                //mengeset nilai yang ditampung agar muncul di table
                TableObat.setModel(table3);
            
        }catch(Exception e){
            System.out.println(e);
        }
       
    }
    private void kodeotomatisPemeriksaan(){
        String query = "SELECT * FROM Pemeriksaan ORDER BY NoPemeriksaan DESC ";
        try{
            Connection connect = Koneksi.getKoneksi();//memanggil koneksi
            Statement sttmnt = connect.createStatement();//membuat statement
            ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
            
            if (rslt.next()){
                String NoPemeriksaan = rslt.getString("NoPemeriksaan").substring(4,7);
                String AN = "" + (Integer.parseInt(NoPemeriksaan)+1);
                String NOL = "";
                if(AN.length()==1){
                    NOL = "000";
                }else if(AN.length()==2){
                    NOL = "00";
                }else if(AN.length()==3){
                    NOL = "0";
                }else if(AN.length()==4){
                    NOL = "";
                }
                KodePemeriksaan = ("PMR" + NOL + AN);
            }else{
                KodePemeriksaan = ("PMR0001");
            }
        rslt.close();
        connect.close();
        }catch(Exception e){
            System.out.println(e);
        }
    }
    private void kodeotomatisResep(){
        String query = "SELECT * FROM resep ORDER BY NoResep DESC ";
        try{
            Connection connect = Koneksi.getKoneksi();//memanggil koneksi
            Statement sttmnt = connect.createStatement();//membuat statement
            ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
            
            if (rslt.next()){
                String kode_resep = rslt.getString("NoResep").substring(4,7);
                String AN = "" + (Integer.parseInt(kode_resep)+1);
                String NOL = "";
                if(AN.length()==1){
                    NOL = "000";
                }else if(AN.length()==2){
                    NOL = "00";
                }else if(AN.length()==3){
                    NOL = "0";
                }else if(AN.length()==4){
                    NOL = "";
                }
                KodeResep = ("RSP" + NOL + AN);
            }else{
                KodeResep = ("RSP0001");
            }
        rslt.close();
        connect.close();
        }catch(Exception e){
            System.out.println(e);
        }
    }
    
    
    
    private void MINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MINActionPerformed
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_MINActionPerformed

    private void CLOSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLOSEActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CLOSEActionPerformed

    private void btnPendaftaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendaftaranActionPerformed
        // TODO add your handling code here:
        new Pendaftaran.DataPasien().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPendaftaranActionPerformed

    private void btnPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPegawaiActionPerformed
        // TODO add your handling code here:
        new MenuPegawai.MenuPegawai().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPegawaiActionPerformed

    private void btnDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDokterActionPerformed
        // TODO add your handling code here:
        new MenuDokter().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDokterActionPerformed

    private void btnPoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoliActionPerformed
        // TODO add your handling code here:
        new MenuPoli.MenuPoli().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPoliActionPerformed

    private void btnPemeriksaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPemeriksaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPemeriksaanActionPerformed

    private void btnJadwalPraktekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadwalPraktekActionPerformed
        // TODO add your handling code here:
        new MenuJadwal.MenuJadwal().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnJadwalPraktekActionPerformed

    private void btnObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObatActionPerformed
        // TODO add your handling code here:
        new MenuObat.MenuObat().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnObatActionPerformed

    private void btnPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembayaranActionPerformed
        // TODO add your handling code here:
        new MenuPembayaran.JenisBiaya().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPembayaranActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        for(double i = 0.0; i <= 1.0; i = i + 0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(20);
            }
           catch(Exception e){
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        // TODO add your handling code here:
        int opsi = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan keluar?", "Log out!", JOptionPane.YES_NO_OPTION);
        if (opsi == JOptionPane.YES_OPTION){
            new Login.Login().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnUserActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        new MenuUtama.MenuUtama().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void NoPendaftaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoPendaftaranActionPerformed
        // TODO add your handling code here:
        tampilDataRiwayat();
    }//GEN-LAST:event_NoPendaftaranActionPerformed

    private void KeluhanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KeluhanFocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_KeluhanFocusGained

    private void KeluhanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_KeluhanFocusLost
        // TODO add your handling code here:
       
    }//GEN-LAST:event_KeluhanFocusLost

    private void jScrollPane4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jScrollPane4FocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jScrollPane4FocusGained

    private void DiagnosisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DiagnosisFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_DiagnosisFocusGained

    private void DiagnosisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DiagnosisFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_DiagnosisFocusLost

    private void jScrollPane5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jScrollPane5FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane5FocusGained

    private void PerawatanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PerawatanFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_PerawatanFocusGained

    private void PerawatanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PerawatanFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_PerawatanFocusLost

    private void jScrollPane6FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jScrollPane6FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane6FocusGained

    private void BeratBadanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BeratBadanFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BeratBadanFocusGained

    private void BeratBadanFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BeratBadanFocusLost
        // TODO add your handling code here:
       
    }//GEN-LAST:event_BeratBadanFocusLost

    private void TensiDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TensiDFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TensiDFocusGained

    private void TensiDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TensiDFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_TensiDFocusLost

    private void TensiSFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TensiSFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_TensiSFocusGained

    private void TensiSFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TensiSFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_TensiSFocusLost

    private void RBPerluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBPerluActionPerformed
        // TODO add your handling code here:
        if(RBPerlu.isSelected()==true){
            TambahResep.setEnabled(true);
            HapusResep.setEnabled(true);
        }else{
            TambahResep.setEnabled(false);
            HapusResep.setEnabled(false);
        }
    }//GEN-LAST:event_RBPerluActionPerformed

    private void RBTidakPerlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBTidakPerlActionPerformed
        // TODO add your handling code here:
        if(RBTidakPerl.isSelected()==true){
            TambahResep.setEnabled(false);
            HapusResep.setEnabled(false);
        }else{
             TambahResep.setEnabled(true);
            HapusResep.setEnabled(true);
        }
    }//GEN-LAST:event_RBTidakPerlActionPerformed

    private void TambahResepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahResepActionPerformed
        // TODO add your handling code here:
        Obat.setVisible(true);
        Obat.setBounds(450, 120, 600, 520);
        tampilDataObat();
    }//GEN-LAST:event_TambahResepActionPerformed

    private void HapusResepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusResepActionPerformed
        // TODO add your handling code here:
        table2.removeRow(TableResep.getSelectedRow());
    }//GEN-LAST:event_HapusResepActionPerformed

    private void btnPilihBiayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihBiayaActionPerformed
        // TODO add your handling code here:
      String Dosis = D1.getText() + " x " + D2.getText();
      String Jumlah = JUMLAH.getText();
      
      
      table2.addRow(new Object[]{i+1,GlobalVar.KodeObat,GlobalVar.NamaObat,Dosis,Jumlah});
      i = i+1;
      int row = TableObat.getRowCount();
        for(int a = 0 ; a < row ; a++){
            table3.removeRow(0);
        }
      D1.setText(null);
      D2.setText(null);
      JUMLAH.setText(null);
      Obat.dispose();
  
    }//GEN-LAST:event_btnPilihBiayaActionPerformed

    private void TableObatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableObatMouseClicked
        // TODO add your handling code here:
       GlobalVar.KodeObat = table3.getValueAt(TableObat.getSelectedRow(), 0).toString();
       GlobalVar.NamaObat = table3.getValueAt(TableObat.getSelectedRow(), 1).toString();
    }//GEN-LAST:event_TableObatMouseClicked

    private void MIN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIN2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MIN2ActionPerformed

    private void CLOSE4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLOSE4ActionPerformed
        // TODO add your handling code here:
        Obat.dispose();
    }//GEN-LAST:event_CLOSE4ActionPerformed

    private void ObatWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_ObatWindowOpened
        // TODO add your handling code here:
        for(double i = 0.0; i <= 1.0; i = i + 0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            //            this.setOpacity(f);
            Obat.setOpacity(f);
            try{
                Thread.sleep(20);
            }
            catch(Exception e){
            }
        }
    }//GEN-LAST:event_ObatWindowOpened

    private void JUMLAHFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JUMLAHFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_JUMLAHFocusGained

    private void JUMLAHFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JUMLAHFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_JUMLAHFocusLost

    private void D1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_D1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_D1FocusGained

    private void D1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_D1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_D1FocusLost

    private void D2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_D2FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_D2FocusGained

    private void D2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_D2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_D2FocusLost

    private void JUMLAHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JUMLAHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JUMLAHActionPerformed

    private void TableRiwayatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableRiwayatMouseClicked
        // TODO add your handling code here:
        TGLPeriksa = table.getValueAt(TableRiwayat.getSelectedRow(), 1).toString();
         Nama = table.getValueAt(TableRiwayat.getSelectedRow(), 2).toString();
        Keluhn =  table.getValueAt(TableRiwayat.getSelectedRow(), 3).toString();
        BeratB =  table.getValueAt(TableRiwayat.getSelectedRow(), 4).toString();
        Tensid =  table.getValueAt(TableRiwayat.getSelectedRow(), 5).toString();
        Tensis =  table.getValueAt(TableRiwayat.getSelectedRow(), 4).toString();
        
        TglRiwayat.setText(TGLPeriksa);
        Namaa.setText(Nama);
        Keluh.setText(Keluhn);
        Bb.setText(BeratB);
        this.Td.setText(Tensid);
        this.Ts.setText(Tensis);
        DetailRiwayat.setVisible(true);
        DetailRiwayat.setBounds(450, 120, 600, 520);
    }//GEN-LAST:event_TableRiwayatMouseClicked

    private void MIN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIN3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MIN3ActionPerformed

    private void CLOSE5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLOSE5ActionPerformed
        // TODO add your handling code here:
        DetailRiwayat.dispose();
    }//GEN-LAST:event_CLOSE5ActionPerformed

    private void DetailRiwayatWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_DetailRiwayatWindowOpened
        // TODO add your handling code here:
        for(double i = 0.0; i <= 1.0; i = i + 0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            //            this.setOpacity(f);
            DetailRiwayat.setOpacity(f);
            try{
                Thread.sleep(20);
            }
            catch(Exception e){
            }
        }
    }//GEN-LAST:event_DetailRiwayatWindowOpened

    private void TableRiwayatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableRiwayatMousePressed
        
    }//GEN-LAST:event_TableRiwayatMousePressed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        tampilDataRiwayat();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        SimpanData();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void NoPendaftaranItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NoPendaftaranItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_NoPendaftaranItemStateChanged

    private void NoPendaftaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoPendaftaranMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_NoPendaftaranMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pemeriksaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pemeriksaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pemeriksaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pemeriksaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pemeriksaan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bb;
    private javax.swing.JTextField BeratBadan;
    private javax.swing.JButton CLOSE;
    private javax.swing.JButton CLOSE4;
    private javax.swing.JButton CLOSE5;
    private javax.swing.JTextField D1;
    private javax.swing.JTextField D2;
    private javax.swing.JDialog DetailRiwayat;
    private javax.swing.JTextArea Diagnosis;
    private javax.swing.JButton HapusResep;
    private javax.swing.JTextField JUMLAH;
    private javax.swing.JLabel Keluh;
    private javax.swing.JTextArea Keluhan;
    private javax.swing.JButton MAX;
    private javax.swing.JButton MAX2;
    private javax.swing.JButton MAX3;
    private javax.swing.JButton MIN;
    private javax.swing.JButton MIN2;
    private javax.swing.JButton MIN3;
    private javax.swing.JLabel Namaa;
    private javax.swing.JComboBox<String> NoPendaftaran;
    private javax.swing.JDialog Obat;
    private javax.swing.JTextArea Perawatan;
    private javax.swing.JRadioButton RBPerlu;
    private javax.swing.JRadioButton RBTidakPerl;
    private javax.swing.JTable TableObat;
    private javax.swing.JTable TableResep;
    private javax.swing.JTable TableRiwayat;
    private javax.swing.JButton TambahResep;
    private javax.swing.JLabel Td;
    private javax.swing.JTextField TensiD;
    private javax.swing.JTextField TensiS;
    private javax.swing.JLabel TglRiwayat;
    private javax.swing.JLabel Ts;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bg2;
    private javax.swing.JLabel bg3;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnDokter;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnJadwalPraktek;
    private javax.swing.JButton btnObat;
    private javax.swing.JButton btnPegawai;
    private javax.swing.JButton btnPembayaran;
    private javax.swing.JButton btnPemeriksaan;
    private javax.swing.JButton btnPendaftaran;
    private javax.swing.JButton btnPilihBiaya;
    private javax.swing.JButton btnPoli;
    private javax.swing.ButtonGroup btnResep;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUser;
    private javax.swing.JLabel header;
    private javax.swing.JLabel header2;
    private javax.swing.JLabel header3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JLabel navi;
    private javax.swing.JLabel txtUser;
    // End of variables declaration//GEN-END:variables
}
