/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MenuPoli;

import MenuUtama.*;
import Koneksi.GlobalVar;
import Koneksi.Koneksi;
import java.awt.Color;
import java.awt.Frame;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author donih
 */
public class MenuPoli extends javax.swing.JFrame {
    /**
     * Creates new form MenuUtama
     */
    DefaultTableModel table = new DefaultTableModel();
    public MenuPoli() {
        initComponents();
        TabelPoli.setModel(table);
        table.addColumn("Kode Poli");
        table.addColumn("Nama Poli");
        tampilData();
        txtUser.setText("Hi!, " + GlobalVar.nama);
        this.setBackground(new Color(0,0,0,0));
        if(GlobalVar.hak_akses.equals("Pegawai")){
            btnPegawai.setEnabled(false);
            btnDokter.setEnabled(false);
            btnPemeriksaan.setEnabled(false);
        }else if(GlobalVar.hak_akses.equals("Dokter")){
            btnPegawai.setEnabled(false);
            btnPendaftaran.setEnabled(false);
            btnDokter.setEnabled(false);
            btnPoli.setEnabled(false);
            btnObat.setEnabled(false);
            btnPembayaran.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tambahData = new javax.swing.JDialog();
        MIN1 = new javax.swing.JButton();
        MAX1 = new javax.swing.JButton();
        CLOSE1 = new javax.swing.JButton();
        Batal = new javax.swing.JButton();
        Simpan = new javax.swing.JButton();
        IsiNama = new javax.swing.JTextField();
        NamaPoli = new javax.swing.JLabel();
        IsiKode = new javax.swing.JTextField();
        KodePoli = new javax.swing.JLabel();
        header1 = new javax.swing.JLabel();
        bg1 = new javax.swing.JLabel();
        editData = new javax.swing.JDialog();
        MIN2 = new javax.swing.JButton();
        MAX2 = new javax.swing.JButton();
        CLOSE2 = new javax.swing.JButton();
        Batal1 = new javax.swing.JButton();
        Simpan1 = new javax.swing.JButton();
        IsiNama1 = new javax.swing.JTextField();
        NamaPoli1 = new javax.swing.JLabel();
        IsiKode1 = new javax.swing.JTextField();
        KodePoli1 = new javax.swing.JLabel();
        header2 = new javax.swing.JLabel();
        bg2 = new javax.swing.JLabel();
        PopupSearch = new javax.swing.JDialog();
        CLOSE3 = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        cari = new javax.swing.JButton();
        titleSearch = new javax.swing.JLabel();
        bg3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelPoli = new javax.swing.JTable();
        Delete = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        Input = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        MIN = new javax.swing.JButton();
        MAX = new javax.swing.JButton();
        CLOSE = new javax.swing.JButton();
        btnPembayaran = new javax.swing.JButton();
        btnObat = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        btnPemeriksaan = new javax.swing.JButton();
        btnPoli = new javax.swing.JButton();
        btnDokter = new javax.swing.JButton();
        btnPegawai = new javax.swing.JButton();
        btnPendaftaran = new javax.swing.JButton();
        btnJadwalPraktek = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        txtUser = new javax.swing.JLabel();
        btnUser = new javax.swing.JButton();
        userPanel = new javax.swing.JLabel();
        navi = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        tambahData.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        tambahData.setUndecorated(true);
        tambahData.setOpacity(0.0F);
        tambahData.setSize(new java.awt.Dimension(600, 600));
        tambahData.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                tambahDataWindowOpened(evt);
            }
        });
        tambahData.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MIN1.setBackground(new Color(0,0,0,0));
        MIN1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/-Off.png"))); // NOI18N
        MIN1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MIN1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Min.png"))); // NOI18N
        MIN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIN1ActionPerformed(evt);
            }
        });
        tambahData.getContentPane().add(MIN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 30, 30));

        MAX1.setBackground(new Color(0,0,0,0));
        MAX1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/maxOff.png"))); // NOI18N
        MAX1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MAX1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Max.png"))); // NOI18N
        tambahData.getContentPane().add(MAX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 30, 30));

        CLOSE1.setBackground(new Color(0,0,0,0));
        CLOSE1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/xOff.png"))); // NOI18N
        CLOSE1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CLOSE1.setBorderPainted(false);
        CLOSE1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CLOSE1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Close.png"))); // NOI18N
        CLOSE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLOSE1ActionPerformed(evt);
            }
        });
        tambahData.getContentPane().add(CLOSE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 30, 30));

        Batal.setBackground(new Color (0,0,0,0));
        Batal.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        Batal.setForeground(new java.awt.Color(255, 255, 255));
        Batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/TmblBatal.png"))); // NOI18N
        Batal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Batal.setBorderPainted(false);
        Batal.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/TmblBatalAktif.png"))); // NOI18N
        Batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalActionPerformed(evt);
            }
        });
        tambahData.getContentPane().add(Batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 130, -1));

        Simpan.setBackground(new Color (0,0,0,0));
        Simpan.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        Simpan.setForeground(new java.awt.Color(255, 255, 255));
        Simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/tmblSimpan.png"))); // NOI18N
        Simpan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Simpan.setBorderPainted(false);
        Simpan.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/tmblSimpanAktif.png"))); // NOI18N
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });
        tambahData.getContentPane().add(Simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 130, -1));

        IsiNama.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        IsiNama.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        IsiNama.setToolTipText("Nama Poli");
        IsiNama.setAlignmentX(1.0F);
        IsiNama.setAlignmentY(1.0F);
        IsiNama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 174, 152), 2));
        IsiNama.setCaretColor(new java.awt.Color(30, 174, 152));
        IsiNama.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        IsiNama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IsiNamaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                IsiNamaFocusLost(evt);
            }
        });
        IsiNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsiNamaActionPerformed(evt);
            }
        });
        tambahData.getContentPane().add(IsiNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 280, 30));

        NamaPoli.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        NamaPoli.setForeground(new java.awt.Color(30, 174, 152));
        NamaPoli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPoli/Asset/NamaPoli.png"))); // NOI18N
        NamaPoli.setText("Nama Poli");
        tambahData.getContentPane().add(NamaPoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 140, 30));

        IsiKode.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        IsiKode.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        IsiKode.setToolTipText("Username");
        IsiKode.setAlignmentX(1.0F);
        IsiKode.setAlignmentY(1.0F);
        IsiKode.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 174, 152), 2));
        IsiKode.setCaretColor(new java.awt.Color(30, 174, 152));
        IsiKode.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        IsiKode.setEnabled(false);
        IsiKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsiKodeActionPerformed(evt);
            }
        });
        tambahData.getContentPane().add(IsiKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 280, 30));

        KodePoli.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        KodePoli.setForeground(new java.awt.Color(30, 174, 152));
        KodePoli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPoli/Asset/KodePoli.png"))); // NOI18N
        KodePoli.setText("Kode Poli");
        tambahData.getContentPane().add(KodePoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 150, 30));

        header1.setBackground(new Color(0,0,0,0));
        header1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPoli/Asset/Tambah Data (1).png"))); // NOI18N
        tambahData.getContentPane().add(header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 30));

        bg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/BgEditPegawai.png"))); // NOI18N
        bg1.setToolTipText("");
        tambahData.getContentPane().add(bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 520));

        editData.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        editData.setUndecorated(true);
        editData.setOpacity(0.0F);
        editData.setSize(new java.awt.Dimension(600, 600));
        editData.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                editDataWindowOpened(evt);
            }
        });
        editData.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MIN2.setBackground(new Color(0,0,0,0));
        MIN2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/-Off.png"))); // NOI18N
        MIN2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MIN2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Min.png"))); // NOI18N
        MIN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIN2ActionPerformed(evt);
            }
        });
        editData.getContentPane().add(MIN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 30, 30));

        MAX2.setBackground(new Color(0,0,0,0));
        MAX2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/maxOff.png"))); // NOI18N
        MAX2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MAX2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Max.png"))); // NOI18N
        editData.getContentPane().add(MAX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 30, 30));

        CLOSE2.setBackground(new Color(0,0,0,0));
        CLOSE2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/xOff.png"))); // NOI18N
        CLOSE2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CLOSE2.setBorderPainted(false);
        CLOSE2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CLOSE2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Close.png"))); // NOI18N
        CLOSE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLOSE2ActionPerformed(evt);
            }
        });
        editData.getContentPane().add(CLOSE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 30, 30));

        Batal1.setBackground(new Color (0,0,0,0));
        Batal1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        Batal1.setForeground(new java.awt.Color(255, 255, 255));
        Batal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/TmblBatal.png"))); // NOI18N
        Batal1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Batal1.setBorderPainted(false);
        Batal1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/TmblBatalAktif.png"))); // NOI18N
        Batal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Batal1ActionPerformed(evt);
            }
        });
        editData.getContentPane().add(Batal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 130, -1));

        Simpan1.setBackground(new Color (0,0,0,0));
        Simpan1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        Simpan1.setForeground(new java.awt.Color(255, 255, 255));
        Simpan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/tmblSimpan.png"))); // NOI18N
        Simpan1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Simpan1.setBorderPainted(false);
        Simpan1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/tmblSimpanAktif.png"))); // NOI18N
        Simpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Simpan1ActionPerformed(evt);
            }
        });
        editData.getContentPane().add(Simpan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 130, -1));

        IsiNama1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        IsiNama1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        IsiNama1.setToolTipText("Username");
        IsiNama1.setAlignmentX(1.0F);
        IsiNama1.setAlignmentY(1.0F);
        IsiNama1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 174, 152), 2));
        IsiNama1.setCaretColor(new java.awt.Color(30, 174, 152));
        IsiNama1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        IsiNama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsiNama1ActionPerformed(evt);
            }
        });
        editData.getContentPane().add(IsiNama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 280, 30));

        NamaPoli1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        NamaPoli1.setForeground(new java.awt.Color(30, 174, 152));
        NamaPoli1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPoli/Asset/NamaPoli.png"))); // NOI18N
        NamaPoli1.setText("Nama Poli");
        editData.getContentPane().add(NamaPoli1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 140, 30));

        IsiKode1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        IsiKode1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        IsiKode1.setToolTipText("Username");
        IsiKode1.setAlignmentX(1.0F);
        IsiKode1.setAlignmentY(1.0F);
        IsiKode1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 174, 152), 2));
        IsiKode1.setCaretColor(new java.awt.Color(30, 174, 152));
        IsiKode1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        IsiKode1.setEnabled(false);
        IsiKode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsiKode1ActionPerformed(evt);
            }
        });
        editData.getContentPane().add(IsiKode1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 280, 30));

        KodePoli1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        KodePoli1.setForeground(new java.awt.Color(30, 174, 152));
        KodePoli1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPoli/Asset/KodePoli.png"))); // NOI18N
        KodePoli1.setText("Kode Poli");
        editData.getContentPane().add(KodePoli1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 150, 30));

        header2.setBackground(new Color(0,0,0,0));
        header2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPoli/Asset/edit data.png"))); // NOI18N
        editData.getContentPane().add(header2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 30));

        bg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/BgEditPegawai.png"))); // NOI18N
        bg2.setToolTipText("");
        editData.getContentPane().add(bg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 520));

        PopupSearch.setUndecorated(true);
        PopupSearch.setOpacity(0.0F);
        PopupSearch.setResizable(false);
        PopupSearch.setSize(new java.awt.Dimension(251, 116));
        PopupSearch.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                PopupSearchWindowOpened(evt);
            }
        });
        PopupSearch.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CLOSE3.setBackground(new Color(0,0,0,0));
        CLOSE3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/xOff.png"))); // NOI18N
        CLOSE3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CLOSE3.setBorderPainted(false);
        CLOSE3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CLOSE3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Close.png"))); // NOI18N
        CLOSE3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLOSE3ActionPerformed(evt);
            }
        });
        PopupSearch.getContentPane().add(CLOSE3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 30, 30));

        txtCari.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtCari.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCari.setToolTipText("Cari Berdasarkan Nama");
        txtCari.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 173, 152), 2, true));
        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        PopupSearch.getContentPane().add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 170, 30));

        cari.setBackground(new Color(0,0,0,0));
        cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/SearchAktif.png"))); // NOI18N
        cari.setBorder(null);
        cari.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search.png"))); // NOI18N
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        PopupSearch.getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, 50));

        titleSearch.setFont(new java.awt.Font("SansSerif", 2, 11)); // NOI18N
        titleSearch.setForeground(new java.awt.Color(255, 255, 255));
        titleSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleSearch.setText("Search");
        PopupSearch.getContentPane().add(titleSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 30));

        bg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPembayaran/Asset/SearchPopup.png"))); // NOI18N
        PopupSearch.getContentPane().add(bg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabelPoli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "KodePoli", "NamaPoli"
            }
        ));
        TabelPoli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelPoliMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelPoli);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 860, 420));

        Delete.setBackground(new Color(0,0,0,0));
        Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPoli/Asset/delete.png"))); // NOI18N
        Delete.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Delete.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPoli/Asset/delete huruf.png"))); // NOI18N
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 370, 90, 80));

        Edit.setBackground(new Color(0,0,0,0));
        Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPoli/Asset/edit.png"))); // NOI18N
        Edit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Edit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPoli/Asset/edit huruf.png"))); // NOI18N
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        getContentPane().add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 270, 90, 80));

        Input.setBackground(new Color(0,0,0,0));
        Input.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPoli/Asset/input.png"))); // NOI18N
        Input.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Input.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPoli/Asset/input huruf.png"))); // NOI18N
        Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputActionPerformed(evt);
            }
        });
        getContentPane().add(Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 170, 90, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPoli/Asset/Text.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 75, -1, -1));

        MIN.setBackground(new Color(0,0,0,0));
        MIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/-Off.png"))); // NOI18N
        MIN.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MIN.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Min.png"))); // NOI18N
        MIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MINActionPerformed(evt);
            }
        });
        getContentPane().add(MIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 0, 30, 30));

        MAX.setBackground(new Color(0,0,0,0));
        MAX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/maxOff.png"))); // NOI18N
        MAX.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MAX.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Max.png"))); // NOI18N
        getContentPane().add(MAX, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 0, 30, 30));

        CLOSE.setBackground(new Color(0,0,0,0));
        CLOSE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/xOff.png"))); // NOI18N
        CLOSE.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CLOSE.setBorderPainted(false);
        CLOSE.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CLOSE.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Close.png"))); // NOI18N
        CLOSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLOSEActionPerformed(evt);
            }
        });
        getContentPane().add(CLOSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 0, 30, 30));

        btnPembayaran.setBackground(new Color(0,0,0,0));
        btnPembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/pembayaran.png"))); // NOI18N
        btnPembayaran.setBorder(null);
        btnPembayaran.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/PembayaranAktif.png"))); // NOI18N
        btnPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembayaranActionPerformed(evt);
            }
        });
        getContentPane().add(btnPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 588, -1, -1));

        btnObat.setBackground(new Color(0,0,0,0));
        btnObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Obat.png"))); // NOI18N
        btnObat.setBorder(null);
        btnObat.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/ObatAktif.png"))); // NOI18N
        btnObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObatActionPerformed(evt);
            }
        });
        getContentPane().add(btnObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 514, -1, -1));

        Search.setBackground(new Color(0,0,0,0));
        Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPembayaran/Asset/Search.png"))); // NOI18N
        Search.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Search.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Search.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPembayaran/Asset/seachAktif.png"))); // NOI18N
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SearchMouseEntered(evt);
            }
        });
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 160, 150, 80));

        btnPemeriksaan.setBackground(new Color(0,0,0,0));
        btnPemeriksaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Pemeriksaan.png"))); // NOI18N
        btnPemeriksaan.setBorder(null);
        btnPemeriksaan.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/PemeriksaanAktif.png"))); // NOI18N
        btnPemeriksaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPemeriksaanActionPerformed(evt);
            }
        });
        getContentPane().add(btnPemeriksaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 366, -1, -1));

        btnPoli.setBackground(new Color(0,0,0,0));
        btnPoli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Poli.png"))); // NOI18N
        btnPoli.setBorder(null);
        btnPoli.setSelected(true);
        btnPoli.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/PoliAktif.png"))); // NOI18N
        btnPoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoliActionPerformed(evt);
            }
        });
        getContentPane().add(btnPoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 292, -1, -1));

        btnDokter.setBackground(new Color(0,0,0,0));
        btnDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Dokter.png"))); // NOI18N
        btnDokter.setBorder(null);
        btnDokter.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/DokterAktif.png"))); // NOI18N
        btnDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDokterActionPerformed(evt);
            }
        });
        getContentPane().add(btnDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 218, -1, -1));

        btnPegawai.setBackground(new Color(0,0,0,0));
        btnPegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Pegawai.png"))); // NOI18N
        btnPegawai.setBorder(null);
        btnPegawai.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/PegawaiAktif.png"))); // NOI18N
        btnPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPegawaiActionPerformed(evt);
            }
        });
        getContentPane().add(btnPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 144, -1, -1));

        btnPendaftaran.setBackground(new Color(0,0,0,0));
        btnPendaftaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Pendaftaran.png"))); // NOI18N
        btnPendaftaran.setBorder(null);
        btnPendaftaran.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/PendaftaranAktif.png"))); // NOI18N
        btnPendaftaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendaftaranActionPerformed(evt);
            }
        });
        getContentPane().add(btnPendaftaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 70, -1, -1));

        btnJadwalPraktek.setBackground(new Color(0,0,0,0));
        btnJadwalPraktek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/JadwalPraktek.png"))); // NOI18N
        btnJadwalPraktek.setBorder(null);
        btnJadwalPraktek.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/JadwalPraktekAktif.png"))); // NOI18N
        btnJadwalPraktek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalPraktekActionPerformed(evt);
            }
        });
        getContentPane().add(btnJadwalPraktek, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 440, -1, -1));

        btnHome.setBackground(new Color(0,0,0,0));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hospital.png"))); // NOI18N
        btnHome.setToolTipText("Home");
        btnHome.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hospitalAktif.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 20, -1, -1));

        txtUser.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtUser.setText("Hi!, User");
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 40, 200, 20));

        btnUser.setBackground(new Color(0,0,0,0));
        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/akun.png"))); // NOI18N
        btnUser.setToolTipText("Log Out");
        btnUser.setBorder(null);
        btnUser.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/akun1.png"))); // NOI18N
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 34, -1, -1));

        userPanel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        userPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dokter/Asset/Acc (1).png"))); // NOI18N
        userPanel.setToolTipText("");
        getContentPane().add(userPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 27, -1, -1));

        navi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/navi.png"))); // NOI18N
        getContentPane().add(navi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/header.png"))); // NOI18N
        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPoli/Asset/BG.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     private void tampilData(){
        //untuk mengahapus baris setelah input
        int row = TabelPoli.getRowCount();
        for(int a = 0 ; a < row ; a++){
            table.removeRow(0);
        }
        
        String query = 
                "SELECT * FROM poli ";
        
        try{
            Connection connect = Koneksi.getKoneksi();//memanggil koneksi
            Statement sttmnt = connect.createStatement();//membuat statement
            ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
            
            while (rslt.next()){
                //menampung data sementara
                   
                    String kode = rslt.getString("KodePoli");
                    String nama = rslt.getString("NamaPoli");
                    
                //masukan semua data kedalam array
                String[] data = {kode,nama};
                //menambahakan baris sesuai dengan data yang tersimpan diarray
                table.addRow(data);
            }
                //mengeset nilai yang ditampung agar muncul di table
                TabelPoli.setModel(table);
            
        }catch(Exception e){
            System.out.println(e);
        }
       
    }
        private void hapusData(){
        //ambill data no pendaftaran
           
        Connection connect = Koneksi.getKoneksi();
        int baris = TabelPoli.getSelectedRow();
        int jawab;
        String kode = table.getValueAt(baris,0).toString();
        
        String query = "DELETE FROM poli WHERE KodePoli = '"+kode+"';";
        try{
            if ((jawab = JOptionPane.showConfirmDialog(null, "Ingin menghapus data?", "konfirmasi", JOptionPane.YES_NO_OPTION)) == 0) {
            PreparedStatement ps = (PreparedStatement) connect.prepareStatement(query);
            ps.execute();
            JOptionPane.showMessageDialog(null , "Data Berhasil Dihapus");
        }
        }catch(SQLException | HeadlessException e){
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Data Gagal Dihapus");
        }finally{
            tampilData();
        }
        
    }
            private void LoadData(){      
        String query = "SELECT * FROM poli WHERE KodePoli = '"+GlobalVar.KodePoli+"' ";
        
        try{
            Connection connect = Koneksi.getKoneksi();//memanggil koneksi
            Statement sttmnt = connect.createStatement();//membuat statement
            ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
            
            while (rslt.next()){
                String Nama = rslt.getString("NamaPoli");
                String Kode = rslt.getString("KodePoli");
                IsiKode1.setText(Kode);
                IsiNama1.setText(Nama);
            } 
        }catch(Exception e){
            
            System.out.println(e);
        } 
    }
        private void UpdateData(){
        
        String Kode = GlobalVar.KodePoli;
        String Nama = IsiNama1.getText();
                        //panggil koneksi
            Connection connect = Koneksi.getKoneksi();
        
            String query2 = "UPDATE poli SET NamaPoli = '"+Nama+"' WHERE KodePoli = '"+Kode+"'";

            try{
                PreparedStatement ps = (PreparedStatement) connect.prepareStatement(query2);
                ps.executeUpdate(query2);
                JOptionPane.showMessageDialog(null , "Data  Berhasil diUpdate");
            }catch(SQLException | HeadlessException e){
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "Data Gagal diUpdate");
            }finally{
                editData.dispose();
                IsiKode1.setText(null);
                IsiNama1.setText(null);
                tampilData();
            }
        }
        private void cari(){
        int row = TabelPoli.getRowCount();
        for(int a = 0 ; a < row ; a++){
            table.removeRow(0);
        }
        
        String cari = txtCari.getText();
        
        String query = 
                    "SELECT KodePoli,NamaPoli FROM poli WHERE NamaPoli LIKE '%"+cari+"%'";
                
       try{
           Connection connect = Koneksi.getKoneksi();//memanggil koneksi
           Statement sttmnt = connect.createStatement();//membuat statement
           ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
           
           while (rslt.next()){
                //menampung data sementara
                   
                    String kode = rslt.getString("KodePoli");
                    String nama = rslt.getString("NamaPoli");
                    
                //masukan semua data kedalam array
                String[] data = {kode,nama};
                //menambahakan baris sesuai dengan data yang tersimpan diarray
                table.addRow(data);
            }
                //mengeset nilai yang ditampung agar muncul di table
                TabelPoli.setModel(table);
           
        
        }catch(Exception e){
               System.out.println(e);
        }
    }

    private void MINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MINActionPerformed
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_MINActionPerformed

    private void CLOSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLOSEActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CLOSEActionPerformed

    private void btnPendaftaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendaftaranActionPerformed
        // TODO add your handling code here:
        new Pendaftaran.DataPasien().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPendaftaranActionPerformed

    private void btnPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPegawaiActionPerformed
        // TODO add your handling code here:
        new MenuPegawai.MenuPegawai().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPegawaiActionPerformed

    private void btnDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDokterActionPerformed
        // TODO add your handling code here:
        new Dokter.MenuDokter().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDokterActionPerformed

    private void btnPoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPoliActionPerformed

    private void btnPemeriksaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPemeriksaanActionPerformed
        // TODO add your handling code here:
        new MenuPemeriksaan.Pemeriksaan().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPemeriksaanActionPerformed

    private void btnJadwalPraktekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadwalPraktekActionPerformed
        // TODO add your handling code here:
        new MenuJadwal.MenuJadwal().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnJadwalPraktekActionPerformed

    private void btnObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObatActionPerformed
        // TODO add your handling code here:
        new MenuObat.MenuObat().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnObatActionPerformed

    private void btnPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembayaranActionPerformed
        // TODO add your handling code here:
        new MenuPembayaran.JenisBiaya().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPembayaranActionPerformed

    private void InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputActionPerformed
        // TODO add your handling code here:
        tambahData.setVisible(true);
        tambahData.setBounds(380, 120   , 600, 520);
        kodeotomatis();
    }//GEN-LAST:event_InputActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
        editData.setVisible(true);
        editData.setBounds(380, 120, 600, 520);
        LoadData();
    }//GEN-LAST:event_EditActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        hapusData();
    }//GEN-LAST:event_DeleteActionPerformed

    private void TabelPoliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelPoliMouseClicked
        // TODO add your handling code here:
        String kode = table.getValueAt(TabelPoli.getSelectedRow(),0).toString();
        GlobalVar.KodePoli = kode;
    }//GEN-LAST:event_TabelPoliMouseClicked

    private void MIN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIN1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_MIN1ActionPerformed

    private void CLOSE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLOSE1ActionPerformed
        // TODO add your handling code here:
        IsiNama.setText("Masukan Nama Poli...");
        tambahData.dispose();
    }//GEN-LAST:event_CLOSE1ActionPerformed

    private void BatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalActionPerformed
        // TODO add your handling code here:
        IsiNama.setText("Masukan Nama Poli...");
        tambahData.dispose();
    }//GEN-LAST:event_BatalActionPerformed

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        // TODO add your handling code here:
        InputData();
        tampilData();
    }//GEN-LAST:event_SimpanActionPerformed

    private void IsiNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsiNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IsiNamaActionPerformed

    private void IsiKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsiKodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IsiKodeActionPerformed

    private void tambahDataWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_tambahDataWindowOpened
        // TODO add your handling code here:
        for(double i = 0.0; i <= 1.0; i = i + 0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            //            this.setOpacity(f);
            tambahData.setOpacity(f);
            try{
                Thread.sleep(20);
            }
            catch(Exception e){
            }
        }
    }//GEN-LAST:event_tambahDataWindowOpened

    private void MIN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIN2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MIN2ActionPerformed

    private void CLOSE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLOSE2ActionPerformed
        // TODO add your handling code here:
        editData.dispose();
    }//GEN-LAST:event_CLOSE2ActionPerformed

    private void Batal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Batal1ActionPerformed
        // TODO add your handling code here:
        editData.dispose();
    }//GEN-LAST:event_Batal1ActionPerformed

    private void Simpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Simpan1ActionPerformed
        // TODO add your handling code here:
        UpdateData();
    }//GEN-LAST:event_Simpan1ActionPerformed

    private void IsiNama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsiNama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IsiNama1ActionPerformed

    private void IsiKode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsiKode1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IsiKode1ActionPerformed

    private void editDataWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_editDataWindowOpened
        // TODO add your handling code here:
                for(double i = 0.0; i <= 1.0; i = i + 0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            //            this.setOpacity(f);
            editData.setOpacity(f);
            try{
                Thread.sleep(20);
            }
            catch(Exception e){
            }
        }
    }//GEN-LAST:event_editDataWindowOpened

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
            for(double i = 0.0; i <= 1.0; i = i + 0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(20);
            }
           catch(Exception e){
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        // TODO add your handling code here:
        int opsi = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan keluar?", "Log out!", JOptionPane.YES_NO_OPTION);
        if (opsi == JOptionPane.YES_OPTION){
            new Login.Login().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnUserActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        new MenuUtama().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void IsiNamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IsiNamaFocusGained
        // TODO add your handling code here:
         
    }//GEN-LAST:event_IsiNamaFocusGained

    private void IsiNamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IsiNamaFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_IsiNamaFocusLost

    private void SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseClicked
        // TODO add your handling code here:
        PopupSearch.setVisible(true);
        PopupSearch.setLocation(930, 240);
    }//GEN-LAST:event_SearchMouseClicked

    private void SearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchMouseEntered

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    private void CLOSE3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLOSE3ActionPerformed
        // TODO add your handling code here:
        tampilData();
        PopupSearch.setVisible(false);
    }//GEN-LAST:event_CLOSE3ActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
        cari();
        PopupSearch.setVisible(false);
    }//GEN-LAST:event_cariActionPerformed

    private void PopupSearchWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_PopupSearchWindowOpened
        // TODO add your handling code here:
        for(double i = 0.0; i <= 1.0; i = i + 0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            //            this.setOpacity(f);
            PopupSearch.setOpacity(f);
            try{
                Thread.sleep(20);
            }
            catch(Exception e){
            }
        }
    }//GEN-LAST:event_PopupSearchWindowOpened
        private void InputData(){
        String Kode = IsiKode.getText();
        String Nama = IsiNama.getText();
            Connection connect = Koneksi.getKoneksi();
            //query untuk memasukan data
            String query2 = "INSERT INTO poli (KodePoli, NamaPoli) "+"VALUES ('"+Kode+"','"+Nama+"')";

            try{
                //menyiapkan statement untuk di eksekusi

                PreparedStatement ps = (PreparedStatement) connect.prepareStatement(query2);
                ps.executeUpdate(query2);
                JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");

            }catch(SQLException | HeadlessException e){
                System.out.println(e);
                JOptionPane.showMessageDialog(null,"Data Gagal Disimpan");

            }finally{
                tambahData.dispose();
                IsiKode.setText(null);
                IsiNama.setText(null);
                tampilData();
            }
    }
        private void kodeotomatis(){
        String query = "SELECT * FROM poli ORDER BY KodePoli DESC ";
        try{
            Connection connect = Koneksi.getKoneksi();//memanggil koneksi
            Statement sttmnt = connect.createStatement();//membuat statement
            ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
            
            if (rslt.next()){
                String kode_poli = rslt.getString("KodePoli").substring(1);
                String AN = "" + (Integer.parseInt(kode_poli)+1);
                String NOL = "";
                if(AN.length()==1){
                    NOL = "000";
                }else if(AN.length()==2){
                    NOL = "00";
                }else if(AN.length()==3){
                    NOL = "0";
                }else if(AN.length()==4){
                    NOL = "";
                }
                IsiKode.setText("P" + NOL + AN);
            }else{
                IsiKode.setText("P0001");
            }
        rslt.close();
        connect.close();
        }catch(Exception e){
            System.out.println(e);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPoli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPoli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPoli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPoli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPoli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Batal;
    private javax.swing.JButton Batal1;
    private javax.swing.JButton CLOSE;
    private javax.swing.JButton CLOSE1;
    private javax.swing.JButton CLOSE2;
    private javax.swing.JButton CLOSE3;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Edit;
    private javax.swing.JButton Input;
    private javax.swing.JTextField IsiKode;
    private javax.swing.JTextField IsiKode1;
    private javax.swing.JTextField IsiNama;
    private javax.swing.JTextField IsiNama1;
    private javax.swing.JLabel KodePoli;
    private javax.swing.JLabel KodePoli1;
    private javax.swing.JButton MAX;
    private javax.swing.JButton MAX1;
    private javax.swing.JButton MAX2;
    private javax.swing.JButton MIN;
    private javax.swing.JButton MIN1;
    private javax.swing.JButton MIN2;
    private javax.swing.JLabel NamaPoli;
    private javax.swing.JLabel NamaPoli1;
    private javax.swing.JDialog PopupSearch;
    private javax.swing.JButton Search;
    private javax.swing.JButton Simpan;
    private javax.swing.JButton Simpan1;
    private javax.swing.JTable TabelPoli;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bg1;
    private javax.swing.JLabel bg2;
    private javax.swing.JLabel bg3;
    private javax.swing.JButton btnDokter;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnJadwalPraktek;
    private javax.swing.JButton btnObat;
    private javax.swing.JButton btnPegawai;
    private javax.swing.JButton btnPembayaran;
    private javax.swing.JButton btnPemeriksaan;
    private javax.swing.JButton btnPendaftaran;
    private javax.swing.JButton btnPoli;
    private javax.swing.JButton btnUser;
    private javax.swing.JButton cari;
    private javax.swing.JDialog editData;
    private javax.swing.JLabel header;
    private javax.swing.JLabel header1;
    private javax.swing.JLabel header2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel navi;
    private javax.swing.JDialog tambahData;
    private javax.swing.JLabel titleSearch;
    private javax.swing.JTextField txtCari;
    private javax.swing.JLabel txtUser;
    private javax.swing.JLabel userPanel;
    // End of variables declaration//GEN-END:variables
}
