/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MenuPembayaran;

import Pendaftaran.*;
import MenuPegawai.*;
import MenuUtama.*;
import Koneksi.GlobalVar;
import MenuObat.MenuObat;
import java.awt.Color;
import java.awt.Frame;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author donih
 */
public class JenisBiaya extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    DefaultTableModel table = new DefaultTableModel();
    public JenisBiaya() {
        initComponents();
        TabelJenisBiaya.setModel(table);
        table.addColumn("Id Jenis Biaya");
        table.addColumn("Nama Biaya");
        table.addColumn("Tarif");
        tampilData();
        txtUser.setText("Hi!, "+ GlobalVar.nama);
        this.setBackground(new Color(0,0,0,0));
        if(Koneksi.GlobalVar.hak_akses.equals("Pegawai")){
            btnPegawai.setEnabled(false);
            btnDokter.setEnabled(false);
            btnPemeriksaan.setEnabled(false);
        }else if(Koneksi.GlobalVar.hak_akses.equals("Dokter")){
            btnPegawai.setEnabled(false);
            btnPendaftaran.setEnabled(false);
            btnDokter.setEnabled(false);
            btnPoli.setEnabled(false);
            btnObat.setEnabled(false);
            btnPembayaran.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tambahJenisBiaya = new javax.swing.JDialog();
        tarifjenis = new javax.swing.JTextField();
        MIN1 = new javax.swing.JButton();
        MAX1 = new javax.swing.JButton();
        CLOSE1 = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        alamat = new javax.swing.JLabel();
        namajenis = new javax.swing.JTextField();
        nama = new javax.swing.JLabel();
        lock = new javax.swing.JLabel();
        idjenis = new javax.swing.JTextField();
        NIP = new javax.swing.JLabel();
        header1 = new javax.swing.JLabel();
        bg1 = new javax.swing.JLabel();
        editJenisBiaya = new javax.swing.JDialog();
        namajenis1 = new javax.swing.JTextField();
        nama2 = new javax.swing.JLabel();
        lock2 = new javax.swing.JLabel();
        idjenis1 = new javax.swing.JTextField();
        NIP2 = new javax.swing.JLabel();
        alamat2 = new javax.swing.JLabel();
        tarifjenis1 = new javax.swing.JTextField();
        MIN3 = new javax.swing.JButton();
        MAX3 = new javax.swing.JButton();
        CLOSE3 = new javax.swing.JButton();
        btnBatal1 = new javax.swing.JButton();
        btnSimpan1 = new javax.swing.JButton();
        header2 = new javax.swing.JLabel();
        bg2 = new javax.swing.JLabel();
        PopupSearch = new javax.swing.JDialog();
        CLOSE4 = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        cari = new javax.swing.JButton();
        titleSearch = new javax.swing.JLabel();
        bg3 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnInput = new javax.swing.JButton();
        MIN = new javax.swing.JButton();
        MAX = new javax.swing.JButton();
        CLOSE = new javax.swing.JButton();
        btnPembayaran = new javax.swing.JButton();
        btnObat = new javax.swing.JButton();
        btnJadwalPraktek = new javax.swing.JButton();
        btnPemeriksaan = new javax.swing.JButton();
        btnPoli = new javax.swing.JButton();
        btnDokter = new javax.swing.JButton();
        btnPegawai = new javax.swing.JButton();
        btnPendaftaran = new javax.swing.JButton();
        btnSubPembayaran = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        btnSubJenisBiaya = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        navi = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        btnUser = new javax.swing.JButton();
        txtUser = new javax.swing.JLabel();
        userPanel = new javax.swing.JLabel();
        Table = new javax.swing.JScrollPane();
        TabelJenisBiaya = new javax.swing.JTable();
        BgPanel = new javax.swing.JLabel();
        BgSubMenu = new javax.swing.JLabel();
        editDataPasien = new javax.swing.JLabel();

        tambahJenisBiaya.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        tambahJenisBiaya.setUndecorated(true);
        tambahJenisBiaya.setOpacity(0.0F);
        tambahJenisBiaya.setSize(new java.awt.Dimension(600, 600));
        tambahJenisBiaya.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                tambahJenisBiayaWindowOpened(evt);
            }
        });
        tambahJenisBiaya.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tarifjenis.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tarifjenis.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tarifjenis.setToolTipText("Tarif");
        tarifjenis.setAlignmentX(1.0F);
        tarifjenis.setAlignmentY(1.0F);
        tarifjenis.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 174, 152), 2, true));
        tarifjenis.setCaretColor(new java.awt.Color(30, 174, 152));
        tarifjenis.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tarifjenis.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tarifjenisFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tarifjenisFocusLost(evt);
            }
        });
        tarifjenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarifjenisActionPerformed(evt);
            }
        });
        tambahJenisBiaya.getContentPane().add(tarifjenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 280, 30));

        MIN1.setBackground(new Color(0,0,0,0));
        MIN1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/-Off.png"))); // NOI18N
        MIN1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MIN1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Min.png"))); // NOI18N
        MIN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIN1ActionPerformed(evt);
            }
        });
        tambahJenisBiaya.getContentPane().add(MIN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 30, 30));

        MAX1.setBackground(new Color(0,0,0,0));
        MAX1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/maxOff.png"))); // NOI18N
        MAX1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MAX1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Max.png"))); // NOI18N
        tambahJenisBiaya.getContentPane().add(MAX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 30, 30));

        CLOSE1.setBackground(new Color(0,0,0,0));
        CLOSE1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/xOff.png"))); // NOI18N
        CLOSE1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CLOSE1.setBorderPainted(false);
        CLOSE1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CLOSE1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Close.png"))); // NOI18N
        CLOSE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLOSE1ActionPerformed(evt);
            }
        });
        tambahJenisBiaya.getContentPane().add(CLOSE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 30, 30));

        btnBatal.setBackground(new Color (0,0,0,0));
        btnBatal.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnBatal.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/TmblBatal.png"))); // NOI18N
        btnBatal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBatal.setBorderPainted(false);
        btnBatal.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/TmblBatalAktif.png"))); // NOI18N
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        tambahJenisBiaya.getContentPane().add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 130, -1));

        btnSimpan.setBackground(new Color (0,0,0,0));
        btnSimpan.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/tmblSimpan.png"))); // NOI18N
        btnSimpan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSimpan.setBorderPainted(false);
        btnSimpan.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/tmblSimpanAktif.png"))); // NOI18N
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        tambahJenisBiaya.getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 130, -1));

        alamat.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        alamat.setForeground(new java.awt.Color(30, 174, 152));
        alamat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPembayaran/Asset/Tarif.png"))); // NOI18N
        alamat.setText("Tarif");
        tambahJenisBiaya.getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 140, 30));

        namajenis.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        namajenis.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        namajenis.setToolTipText("Nama Biaya");
        namajenis.setAlignmentX(1.0F);
        namajenis.setAlignmentY(1.0F);
        namajenis.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 174, 152), 2, true));
        namajenis.setCaretColor(new java.awt.Color(30, 174, 152));
        namajenis.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        namajenis.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                namajenisFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                namajenisFocusLost(evt);
            }
        });
        namajenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namajenisActionPerformed(evt);
            }
        });
        tambahJenisBiaya.getContentPane().add(namajenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 280, 30));

        nama.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        nama.setForeground(new java.awt.Color(30, 174, 152));
        nama.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPembayaran/Asset/Nama.png"))); // NOI18N
        nama.setText("Nama Biaya");
        tambahJenisBiaya.getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 140, 30));

        lock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pendaftaran/Asset/lock.png"))); // NOI18N
        tambahJenisBiaya.getContentPane().add(lock, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 30, 30));

        idjenis.setEditable(false);
        idjenis.setBackground(new java.awt.Color(204, 204, 204));
        idjenis.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        idjenis.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        idjenis.setToolTipText("Nomor Pasien");
        idjenis.setActionCommand("<Not Set>");
        idjenis.setAlignmentX(1.0F);
        idjenis.setAlignmentY(1.0F);
        idjenis.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 174, 152), 2, true));
        idjenis.setCaretColor(new java.awt.Color(30, 174, 152));
        idjenis.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        idjenis.setSelectedTextColor(new java.awt.Color(255, 204, 0));
        idjenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idjenisActionPerformed(evt);
            }
        });
        tambahJenisBiaya.getContentPane().add(idjenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 280, 30));

        NIP.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        NIP.setForeground(new java.awt.Color(30, 174, 152));
        NIP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pendaftaran/Asset/nopasIcon.png"))); // NOI18N
        NIP.setText("ID Jenis Biaya");
        tambahJenisBiaya.getContentPane().add(NIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 180, 30));

        header1.setBackground(new Color(0,0,0,0));
        header1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pendaftaran/Asset/headerTambah.png"))); // NOI18N
        tambahJenisBiaya.getContentPane().add(header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 30));

        bg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/BgEditPegawai.png"))); // NOI18N
        bg1.setToolTipText("");
        tambahJenisBiaya.getContentPane().add(bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 520));

        editJenisBiaya.setBackground(new java.awt.Color(255, 255, 255));
        editJenisBiaya.setUndecorated(true);
        editJenisBiaya.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                editJenisBiayaWindowOpened(evt);
            }
        });
        editJenisBiaya.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namajenis1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        namajenis1.setForeground(new java.awt.Color(102, 102, 102));
        namajenis1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        namajenis1.setToolTipText("Nama Pasien");
        namajenis1.setAlignmentX(1.0F);
        namajenis1.setAlignmentY(1.0F);
        namajenis1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 174, 152), 2, true));
        namajenis1.setCaretColor(new java.awt.Color(30, 174, 152));
        namajenis1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        namajenis1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                namajenis1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                namajenis1FocusLost(evt);
            }
        });
        namajenis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namajenis1ActionPerformed(evt);
            }
        });
        editJenisBiaya.getContentPane().add(namajenis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 280, 30));

        nama2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        nama2.setForeground(new java.awt.Color(30, 174, 152));
        nama2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPembayaran/Asset/Nama.png"))); // NOI18N
        nama2.setText("Nama Biaya");
        editJenisBiaya.getContentPane().add(nama2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 140, 30));

        lock2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pendaftaran/Asset/lock.png"))); // NOI18N
        editJenisBiaya.getContentPane().add(lock2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 30, 30));

        idjenis1.setEditable(false);
        idjenis1.setBackground(new java.awt.Color(204, 204, 204));
        idjenis1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        idjenis1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        idjenis1.setToolTipText("Nomor Pasien");
        idjenis1.setActionCommand("<Not Set>");
        idjenis1.setAlignmentX(1.0F);
        idjenis1.setAlignmentY(1.0F);
        idjenis1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 174, 152), 2, true));
        idjenis1.setCaretColor(new java.awt.Color(30, 174, 152));
        idjenis1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        idjenis1.setSelectedTextColor(new java.awt.Color(255, 204, 0));
        idjenis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idjenis1ActionPerformed(evt);
            }
        });
        editJenisBiaya.getContentPane().add(idjenis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 280, 30));

        NIP2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        NIP2.setForeground(new java.awt.Color(30, 174, 152));
        NIP2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pendaftaran/Asset/nopasIcon.png"))); // NOI18N
        NIP2.setText("ID Jenis Biaya");
        editJenisBiaya.getContentPane().add(NIP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 180, 30));

        alamat2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        alamat2.setForeground(new java.awt.Color(30, 174, 152));
        alamat2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPembayaran/Asset/Tarif.png"))); // NOI18N
        alamat2.setText("Tarif");
        editJenisBiaya.getContentPane().add(alamat2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 140, 30));

        tarifjenis1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tarifjenis1.setForeground(new java.awt.Color(102, 102, 102));
        tarifjenis1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tarifjenis1.setToolTipText("Nama Pasien");
        tarifjenis1.setAlignmentX(1.0F);
        tarifjenis1.setAlignmentY(1.0F);
        tarifjenis1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 174, 152), 2, true));
        tarifjenis1.setCaretColor(new java.awt.Color(30, 174, 152));
        tarifjenis1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tarifjenis1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tarifjenis1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tarifjenis1FocusLost(evt);
            }
        });
        tarifjenis1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarifjenis1ActionPerformed(evt);
            }
        });
        editJenisBiaya.getContentPane().add(tarifjenis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 280, 30));

        MIN3.setBackground(new Color(0,0,0,0));
        MIN3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/-Off.png"))); // NOI18N
        MIN3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MIN3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Min.png"))); // NOI18N
        MIN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIN3ActionPerformed(evt);
            }
        });
        editJenisBiaya.getContentPane().add(MIN3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 30, 30));

        MAX3.setBackground(new Color(0,0,0,0));
        MAX3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/maxOff.png"))); // NOI18N
        MAX3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MAX3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Max.png"))); // NOI18N
        MAX3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MAX3ActionPerformed(evt);
            }
        });
        editJenisBiaya.getContentPane().add(MAX3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 30, 30));

        CLOSE3.setBackground(new Color(0,0,0,0));
        CLOSE3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/xOff.png"))); // NOI18N
        CLOSE3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CLOSE3.setBorderPainted(false);
        CLOSE3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CLOSE3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Close.png"))); // NOI18N
        CLOSE3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLOSE3ActionPerformed(evt);
            }
        });
        editJenisBiaya.getContentPane().add(CLOSE3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 30, 30));

        btnBatal1.setBackground(new Color (0,0,0,0));
        btnBatal1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnBatal1.setForeground(new java.awt.Color(255, 255, 255));
        btnBatal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/TmblBatal.png"))); // NOI18N
        btnBatal1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnBatal1.setBorderPainted(false);
        btnBatal1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/TmblBatalAktif.png"))); // NOI18N
        btnBatal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatal1ActionPerformed(evt);
            }
        });
        editJenisBiaya.getContentPane().add(btnBatal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 130, -1));

        btnSimpan1.setBackground(new Color (0,0,0,0));
        btnSimpan1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        btnSimpan1.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/tmblSimpan.png"))); // NOI18N
        btnSimpan1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSimpan1.setBorderPainted(false);
        btnSimpan1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/tmblSimpanAktif.png"))); // NOI18N
        btnSimpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpan1ActionPerformed(evt);
            }
        });
        editJenisBiaya.getContentPane().add(btnSimpan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 130, -1));

        header2.setBackground(new Color(0,0,0,0));
        header2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pendaftaran/Asset/headerEdit.png"))); // NOI18N
        editJenisBiaya.getContentPane().add(header2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 30));

        bg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/BgEditPegawai.png"))); // NOI18N
        bg2.setToolTipText("");
        editJenisBiaya.getContentPane().add(bg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 520));

        PopupSearch.setUndecorated(true);
        PopupSearch.setOpacity(0.0F);
        PopupSearch.setResizable(false);
        PopupSearch.setSize(new java.awt.Dimension(251, 116));
        PopupSearch.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                PopupSearchWindowOpened(evt);
            }
        });
        PopupSearch.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CLOSE4.setBackground(new Color(0,0,0,0));
        CLOSE4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/xOff.png"))); // NOI18N
        CLOSE4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CLOSE4.setBorderPainted(false);
        CLOSE4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CLOSE4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Close.png"))); // NOI18N
        CLOSE4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLOSE4ActionPerformed(evt);
            }
        });
        PopupSearch.getContentPane().add(CLOSE4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 30, 30));

        txtCari.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtCari.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCari.setToolTipText("Cari Berdasarkan Nama");
        txtCari.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 173, 152), 2, true));
        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        PopupSearch.getContentPane().add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 170, 30));

        cari.setBackground(new Color(0,0,0,0));
        cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/SearchAktif.png"))); // NOI18N
        cari.setBorder(null);
        cari.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search.png"))); // NOI18N
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        PopupSearch.getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, 50));

        titleSearch.setFont(new java.awt.Font("SansSerif", 2, 11)); // NOI18N
        titleSearch.setForeground(new java.awt.Color(255, 255, 255));
        titleSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleSearch.setText("Search");
        PopupSearch.getContentPane().add(titleSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 30));

        bg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPembayaran/Asset/SearchPopup.png"))); // NOI18N
        PopupSearch.getContentPane().add(bg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 730));
        setUndecorated(true);
        setOpacity(0.0F);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDelete.setBackground(new Color(0,0,0,0));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/delete.png"))); // NOI18N
        btnDelete.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnDelete.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/deleteaktif.png"))); // NOI18N
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 350, 90, 80));

        btnEdit.setBackground(new Color(0,0,0,0));
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/edit.png"))); // NOI18N
        btnEdit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnEdit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/editaktif.png"))); // NOI18N
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 270, 90, 80));

        btnInput.setBackground(new Color(0,0,0,0));
        btnInput.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/input.png"))); // NOI18N
        btnInput.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnInput.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/inputaktif.png"))); // NOI18N
        btnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputActionPerformed(evt);
            }
        });
        getContentPane().add(btnInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 190, 90, 80));

        MIN.setBackground(new Color(0,0,0,0));
        MIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/-Off.png"))); // NOI18N
        MIN.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MIN.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Min.png"))); // NOI18N
        MIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MINActionPerformed(evt);
            }
        });
        getContentPane().add(MIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 0, 30, 30));

        MAX.setBackground(new Color(0,0,0,0));
        MAX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/maxOff.png"))); // NOI18N
        MAX.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MAX.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Max.png"))); // NOI18N
        getContentPane().add(MAX, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 0, 30, 30));

        CLOSE.setBackground(new Color(0,0,0,0));
        CLOSE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/xOff.png"))); // NOI18N
        CLOSE.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CLOSE.setBorderPainted(false);
        CLOSE.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CLOSE.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Close.png"))); // NOI18N
        CLOSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLOSEActionPerformed(evt);
            }
        });
        getContentPane().add(CLOSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 0, 30, 30));

        btnPembayaran.setBackground(new Color(0,0,0,0));
        btnPembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/pembayaran.png"))); // NOI18N
        btnPembayaran.setBorder(null);
        btnPembayaran.setSelected(true);
        btnPembayaran.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/PembayaranAktif.png"))); // NOI18N
        btnPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembayaranActionPerformed(evt);
            }
        });
        getContentPane().add(btnPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 588, -1, -1));

        btnObat.setBackground(new Color(0,0,0,0));
        btnObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Obat.png"))); // NOI18N
        btnObat.setBorder(null);
        btnObat.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/ObatAktif.png"))); // NOI18N
        btnObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObatActionPerformed(evt);
            }
        });
        getContentPane().add(btnObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 514, -1, -1));

        btnJadwalPraktek.setBackground(new Color(0,0,0,0));
        btnJadwalPraktek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/JadwalPraktek.png"))); // NOI18N
        btnJadwalPraktek.setBorder(null);
        btnJadwalPraktek.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/JadwalPraktekAktif.png"))); // NOI18N
        btnJadwalPraktek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalPraktekActionPerformed(evt);
            }
        });
        getContentPane().add(btnJadwalPraktek, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 440, -1, -1));

        btnPemeriksaan.setBackground(new Color(0,0,0,0));
        btnPemeriksaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Pemeriksaan.png"))); // NOI18N
        btnPemeriksaan.setBorder(null);
        btnPemeriksaan.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/PemeriksaanAktif.png"))); // NOI18N
        btnPemeriksaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPemeriksaanActionPerformed(evt);
            }
        });
        getContentPane().add(btnPemeriksaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 366, -1, -1));

        btnPoli.setBackground(new Color(0,0,0,0));
        btnPoli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Poli.png"))); // NOI18N
        btnPoli.setBorder(null);
        btnPoli.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/PoliAktif.png"))); // NOI18N
        btnPoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoliActionPerformed(evt);
            }
        });
        getContentPane().add(btnPoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 292, -1, -1));

        btnDokter.setBackground(new Color(0,0,0,0));
        btnDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Dokter.png"))); // NOI18N
        btnDokter.setBorder(null);
        btnDokter.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/DokterAktif.png"))); // NOI18N
        btnDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDokterActionPerformed(evt);
            }
        });
        getContentPane().add(btnDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 218, -1, -1));

        btnPegawai.setBackground(new Color(0,0,0,0));
        btnPegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Pegawai.png"))); // NOI18N
        btnPegawai.setBorder(null);
        btnPegawai.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/PegawaiAktif.png"))); // NOI18N
        btnPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPegawaiActionPerformed(evt);
            }
        });
        getContentPane().add(btnPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 144, -1, -1));

        btnPendaftaran.setBackground(new Color(0,0,0,0));
        btnPendaftaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Pendaftaran.png"))); // NOI18N
        btnPendaftaran.setBorder(null);
        btnPendaftaran.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/PendaftaranAktif.png"))); // NOI18N
        btnPendaftaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendaftaranActionPerformed(evt);
            }
        });
        getContentPane().add(btnPendaftaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 70, -1, -1));

        btnSubPembayaran.setBackground(new Color(0,0,0,0));
        btnSubPembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPembayaran/Asset/LogoPembayar.png"))); // NOI18N
        btnSubPembayaran.setBorder(null);
        btnSubPembayaran.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/PembayaranAktif.png"))); // NOI18N
        btnSubPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubPembayaranActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 196, -1, 40));

        Search.setBackground(new Color(0,0,0,0));
        Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPembayaran/Asset/Search.png"))); // NOI18N
        Search.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Search.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Search.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPembayaran/Asset/seachAktif.png"))); // NOI18N
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SearchMouseEntered(evt);
            }
        });
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 170, 150, 80));

        btnSubJenisBiaya.setBackground(new Color(0,0,0,0));
        btnSubJenisBiaya.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPembayaran/Asset/LogoJenis.png"))); // NOI18N
        btnSubJenisBiaya.setBorder(null);
        btnSubJenisBiaya.setSelected(true);
        btnSubJenisBiaya.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPembayaran/Asset/SelectLogoJenis.png"))); // NOI18N
        btnSubJenisBiaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubJenisBiayaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSubJenisBiaya, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 147, -1, 40));

        btnHome.setBackground(new Color(0,0,0,0));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hospital.png"))); // NOI18N
        btnHome.setToolTipText("Home");
        btnHome.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hospitalAktif.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 20, -1, -1));

        Title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPembayaran/Asset/JENIS BIAYA.png"))); // NOI18N
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 90, -1, -1));

        navi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/navi.png"))); // NOI18N
        getContentPane().add(navi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/header.png"))); // NOI18N
        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnUser.setBackground(new Color(0,0,0,0));
        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/akun.png"))); // NOI18N
        btnUser.setToolTipText("Log Out");
        btnUser.setBorder(null);
        btnUser.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/akun1.png"))); // NOI18N
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 34, -1, -1));

        txtUser.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtUser.setText("Hi!, User");
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 40, 200, 20));

        userPanel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        userPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dokter/Asset/Acc (1).png"))); // NOI18N
        userPanel.setToolTipText("");
        getContentPane().add(userPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 27, -1, -1));

        TabelJenisBiaya.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        TabelJenisBiaya.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelJenisBiayaMouseClicked(evt);
            }
        });
        Table.setViewportView(TabelJenisBiaya);

        getContentPane().add(Table, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 247, 830, 420));

        BgPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/panel.png"))); // NOI18N
        BgPanel.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(BgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 171, 980, -1));

        BgSubMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BgSubMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPembayaran/Asset/SubJenisBiaya.png"))); // NOI18N
        BgSubMenu.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BgSubMenu.setPreferredSize(new java.awt.Dimension(150, 651));
        getContentPane().add(BgSubMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 65, 160, 650));

        editDataPasien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/bgmenupegawai.png"))); // NOI18N
        getContentPane().add(editDataPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tampilData(){
        //untuk mengahapus baris setelah input
        int row = TabelJenisBiaya.getRowCount();
        for(int a = 0 ; a < row ; a++){
            table.removeRow(0);
        }
        
        String query = 
                "SELECT *FROM jenisbiaya";
                
        
        try{
            Connection connect = Koneksi.Koneksi.getKoneksi();//memanggil koneksi
            Statement sttmnt = connect.createStatement();//membuat statement
            ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
            
            while (rslt.next()){
                //menampung data sementara
                   
                    String idbiaya = rslt.getString("IDJenisBiaya");
                    String namabiaya = rslt.getString("NamaBiaya");
                    String tarif = rslt.getString("Tarif");
                    
                    
                //masukan semua data kedalam array
                String[] data = {idbiaya,namabiaya,tarif};
                //menambahakan baris sesuai dengan data yang tersimpan diarray
                table.addRow(data);
            }
                //mengeset nilai yang ditampung agar muncul di table
                TabelJenisBiaya.setModel(table);
            
        }catch(Exception e){
            System.out.println(e);
        }
       
    }
    
    private void hapusData(){
        //ambill data no pendaftaran
           
        Connection connect = Koneksi.Koneksi.getKoneksi();
        int baris = TabelJenisBiaya.getSelectedRow();
        int jawab;
        String kode = table.getValueAt(baris,0).toString();
        
        String query = "DELETE FROM jenisbiaya WHERE IDJenisBiaya = '"+kode+"';";
        try{
            if ((jawab = JOptionPane.showConfirmDialog(null, "Ingin menghapus data?", "konfirmasi", JOptionPane.YES_NO_OPTION)) == 0) {
            PreparedStatement ps = (PreparedStatement) connect.prepareStatement(query);
            ps.execute();
            JOptionPane.showMessageDialog(null , "Data Berhasil Dihapus");
        }
        }catch(SQLException | HeadlessException e){
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Data Gagal Dihapus");
        }finally{
            tampilData();
        }
        
    }
    
    private void tambahData(){
    
        String idbiaya = idjenis.getText();
        String nama = namajenis.getText();
        String tarif = tarifjenis.getText();
        
        
        Connection connect = Koneksi.Koneksi.getKoneksi();
        
        String query = "INSERT INTO jenisbiaya (IDJenisBiaya, NamaBiaya, Tarif ) "
                         + "VALUES ('"+idbiaya+"', '"+nama+"','"+tarif+"')";
        
                       
        try{
            PreparedStatement ps = (PreparedStatement) connect.prepareStatement(query);
            ps.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
        }catch(Exception e){
            System.out.println(e);
        }finally{
            tambahJenisBiaya.dispose();
            idjenis.setText(null);
            namajenis.setText(null);
            tarifjenis.setText(null);
        }
    }

    
    private void LoadData(){      
        String query = "SELECT *FROM jenisbiaya WHERE IDJenisBiaya = '"+Koneksi.GlobalVar.idbiaya+"' ";
        
        try{
            Connection connect = Koneksi.Koneksi.getKoneksi();//memanggil koneksi
            Statement sttmnt = connect.createStatement();//membuat statement
            ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
            
            while (rslt.next()){
                String id = rslt.getString("IDJenisBiaya");
                String nama = rslt.getString("NamaBiaya");
                String tarif = rslt.getString("Tarif");
                
                idjenis1.setText(id);
                namajenis1.setText(nama);
                tarifjenis1.setText(tarif);
            } 
        }catch(Exception e){
            
            System.out.println(e);
        } 
    }
  
    private void UpdateData(){
        
        String id = idjenis1.getText();
        String nama = namajenis1.getText();
        String tarif = tarifjenis1.getText();
                 
        Connection connect = Koneksi.Koneksi.getKoneksi();
        
            String query2 = "UPDATE jenisbiaya SET NamaBiaya = '"+nama+"', Tarif = '"+tarif+"'"
                    + "WHERE IDJenisBiaya = '"+id+"';";
            

            try{
                PreparedStatement ps = (PreparedStatement) connect.prepareStatement(query2);
                ps.executeUpdate(query2);
                JOptionPane.showMessageDialog(null , "Data  Berhasil diUpdate");
            }catch(SQLException | HeadlessException e){
                System.out.println(e);
                JOptionPane.showMessageDialog(null, "Data Gagal diUpdate");
            }finally{
                editJenisBiaya.dispose();
                idjenis1.setText(null);
                namajenis1.setText(null);
                tarifjenis1.setText(null);
                
                tampilData();
            }
    }
    
    private void kodeotomatis(){
        String query = "SELECT * FROM jenisbiaya ORDER BY IDJenisBiaya DESC ";
        try{
            Connection connect = Koneksi.Koneksi.getKoneksi();//memanggil koneksi
            Statement sttmnt = connect.createStatement();//membuat statement
            ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
            
            if (rslt.next()){
                String Id = rslt.getString("IDJenisBiaya").substring(1);
                String AN = "" + (Integer.parseInt(Id)+1);
                String NOL = "";
                if(AN.length()==1){
                    NOL = "000";
                }else if(AN.length()==2){
                    NOL = "00";
                }else if(AN.length()==3){
                    NOL = "0";
                }else if(AN.length()==4){
                    NOL = "";
                }
                idjenis.setText("T" + NOL + AN);
            }else{
                idjenis.setText("T0001");
            }
        rslt.close();
        connect.close();
        }catch(Exception e){
            System.out.println(e);
        }
    }
        private void cari(){
        int row = TabelJenisBiaya.getRowCount();
        for(int a = 0 ; a < row ; a++){
            table.removeRow(0);
        }
        
        String cari = txtCari.getText();
        
        String query = 
                    "SELECT IDJenisBiaya,NamaBiaya,Tarif FROM jenisbiaya WHERE NamaBiaya LIKE '%"+cari+"%'";
                
       try{
           Connection connect = Koneksi.Koneksi.getKoneksi();//memanggil koneksi
           Statement sttmnt = connect.createStatement();//membuat statement
           ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
           
           while (rslt.next()){
                //menampung data sementara
                   
                    String kode = rslt.getString("IDJenisBiaya");
                    String nama = rslt.getString("NamaBiaya");
                    String harga = rslt.getString("Tarif");
                    
                //masukan semua data kedalam array
                String[] data = {kode,nama,harga};
                //menambahakan baris sesuai dengan data yang tersimpan diarray
                table.addRow(data);
            }
                //mengeset nilai yang ditampung agar muncul di table
                TabelJenisBiaya.setModel(table);
           
        
        }catch(Exception e){
               System.out.println(e);
        }
    }
    private void MINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MINActionPerformed
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_MINActionPerformed

    private void CLOSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLOSEActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CLOSEActionPerformed

    private void btnPendaftaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendaftaranActionPerformed
        // TODO add your handling code here:
        new Pendaftaran.DataPasien().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPendaftaranActionPerformed

    private void btnPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPegawaiActionPerformed
        // TODO add your handling code here:
        new MenuPegawai().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPegawaiActionPerformed

    private void btnDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDokterActionPerformed
        // TODO add your handling code here:
        new Dokter.MenuDokter().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDokterActionPerformed

    private void btnPoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoliActionPerformed
        // TODO add your handling code here:
        new MenuPoli.MenuPoli().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPoliActionPerformed

    private void btnPemeriksaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPemeriksaanActionPerformed
        // TODO add your handling code here:
        new MenuPemeriksaan.Pemeriksaan().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPemeriksaanActionPerformed

    private void btnJadwalPraktekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadwalPraktekActionPerformed
        // TODO add your handling code here:
        new MenuJadwal.MenuJadwal().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnJadwalPraktekActionPerformed

    private void btnObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObatActionPerformed
        // TODO add your handling code here:
        new MenuObat().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnObatActionPerformed

    private void btnPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPembayaranActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        editJenisBiaya.setVisible(true);
        editJenisBiaya.setBounds(450, 120, 600, 520);
        LoadData();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        hapusData();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        for(double i = 0.0; i <= 1.0; i = i + 0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(20);
            }
           catch(Exception e){
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void MIN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIN1ActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_MIN1ActionPerformed

    private void CLOSE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLOSE1ActionPerformed
        // TODO add your handling code here:
        namajenis.setText(null);
        tarifjenis.setText(null);
        tambahJenisBiaya.dispose();
    }//GEN-LAST:event_CLOSE1ActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        namajenis.setText(null);
        tarifjenis.setText(null);
        tambahJenisBiaya.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        tambahData();
        tampilData();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void namajenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namajenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namajenisActionPerformed

    private void idjenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idjenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idjenisActionPerformed

    private void tambahJenisBiayaWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_tambahJenisBiayaWindowOpened
        // TODO add your handling code here:
        for(double i = 0.0; i <= 1.0; i = i + 0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            //this.setOpacity(f);
            tambahJenisBiaya.setOpacity(f);
            try{
                Thread.sleep(20);
            }
           catch(Exception e){
            }
        }
    }//GEN-LAST:event_tambahJenisBiayaWindowOpened

    private void btnBatal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatal1ActionPerformed
        // TODO add your handling code here:
        editJenisBiaya.dispose();
    }//GEN-LAST:event_btnBatal1ActionPerformed

    private void btnSimpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpan1ActionPerformed
        // TODO add your handling code here:
        UpdateData();
        tampilData();
    }//GEN-LAST:event_btnSimpan1ActionPerformed

    private void MIN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIN3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_MIN3ActionPerformed

    private void CLOSE3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLOSE3ActionPerformed
        // TODO add your handling code here:
        editJenisBiaya.dispose();
    }//GEN-LAST:event_CLOSE3ActionPerformed

    private void MAX3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MAX3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MAX3ActionPerformed

    private void editJenisBiayaWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_editJenisBiayaWindowOpened
        // TODO add your handling code here:
                for(double i = 0.0; i <= 1.0; i = i + 0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            //            this.setOpacity(f);
            editJenisBiaya.setOpacity(f);
            try{
                Thread.sleep(20);
            }
            catch(Exception e){
            }
        }
    }//GEN-LAST:event_editJenisBiayaWindowOpened

    private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputActionPerformed
        // TODO add your handling code here:
        tambahJenisBiaya.setVisible(true);
        tambahJenisBiaya.setBounds(450, 120, 600, 520);
        kodeotomatis();
    }//GEN-LAST:event_btnInputActionPerformed

    private void TabelJenisBiayaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelJenisBiayaMouseClicked
        // TODO add your handling code here:
        String kode = table.getValueAt(TabelJenisBiaya.getSelectedRow(),0).toString();
        GlobalVar.idbiaya = kode;
    }//GEN-LAST:event_TabelJenisBiayaMouseClicked

    private void btnSubJenisBiayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubJenisBiayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSubJenisBiayaActionPerformed

    private void btnSubPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubPembayaranActionPerformed
        // TODO add your handling code here:        
        new MenuPembayaran.Pembayaran().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSubPembayaranActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        // TODO add your handling code here:
        int opsi = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan keluar?", "Log out!", JOptionPane.YES_NO_OPTION);
        if (opsi == JOptionPane.YES_OPTION){
            new Login.Login().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnUserActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        new MenuUtama().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void namajenisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namajenisFocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_namajenisFocusGained
    
    private void namajenisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namajenisFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_namajenisFocusLost

    private void tarifjenisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tarifjenisFocusGained
        // TODO add your handling code here:
       
    }//GEN-LAST:event_tarifjenisFocusGained
   
    private void tarifjenisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tarifjenisFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tarifjenisFocusLost

    private void tarifjenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarifjenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarifjenisActionPerformed

    private void idjenis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idjenis1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idjenis1ActionPerformed

    private void namajenis1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namajenis1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_namajenis1FocusGained

    private void namajenis1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_namajenis1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_namajenis1FocusLost

    private void namajenis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namajenis1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namajenis1ActionPerformed

    private void tarifjenis1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tarifjenis1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_tarifjenis1FocusGained

    private void tarifjenis1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tarifjenis1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_tarifjenis1FocusLost

    private void tarifjenis1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarifjenis1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarifjenis1ActionPerformed

    private void SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseClicked
        // TODO add your handling code here:
        PopupSearch.setVisible(true);
        PopupSearch.setLocation(930, 240);
    }//GEN-LAST:event_SearchMouseClicked

    private void SearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchMouseEntered

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    private void CLOSE4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLOSE4ActionPerformed
        // TODO add your handling code here:
        tampilData();
        PopupSearch.setVisible(false);
    }//GEN-LAST:event_CLOSE4ActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
        cari();
        PopupSearch.setVisible(false);
    }//GEN-LAST:event_cariActionPerformed

    private void PopupSearchWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_PopupSearchWindowOpened
        // TODO add your handling code here:
        for(double i = 0.0; i <= 1.0; i = i + 0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            //            this.setOpacity(f);
            PopupSearch.setOpacity(f);
            try{
                Thread.sleep(20);
            }
            catch(Exception e){
            }
        }
    }//GEN-LAST:event_PopupSearchWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JenisBiaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JenisBiaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JenisBiaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JenisBiaya.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JenisBiaya().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BgPanel;
    private javax.swing.JLabel BgSubMenu;
    private javax.swing.JButton CLOSE;
    private javax.swing.JButton CLOSE1;
    private javax.swing.JButton CLOSE3;
    private javax.swing.JButton CLOSE4;
    private javax.swing.JButton MAX;
    private javax.swing.JButton MAX1;
    private javax.swing.JButton MAX3;
    private javax.swing.JButton MIN;
    private javax.swing.JButton MIN1;
    private javax.swing.JButton MIN3;
    private javax.swing.JLabel NIP;
    private javax.swing.JLabel NIP2;
    private javax.swing.JDialog PopupSearch;
    private javax.swing.JButton Search;
    private javax.swing.JTable TabelJenisBiaya;
    private javax.swing.JScrollPane Table;
    private javax.swing.JLabel Title;
    private javax.swing.JLabel alamat;
    private javax.swing.JLabel alamat2;
    private javax.swing.JLabel bg1;
    private javax.swing.JLabel bg2;
    private javax.swing.JLabel bg3;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnBatal1;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDokter;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnInput;
    private javax.swing.JButton btnJadwalPraktek;
    private javax.swing.JButton btnObat;
    private javax.swing.JButton btnPegawai;
    private javax.swing.JButton btnPembayaran;
    private javax.swing.JButton btnPemeriksaan;
    private javax.swing.JButton btnPendaftaran;
    private javax.swing.JButton btnPoli;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnSimpan1;
    private javax.swing.JButton btnSubJenisBiaya;
    private javax.swing.JButton btnSubPembayaran;
    private javax.swing.JButton btnUser;
    private javax.swing.JButton cari;
    private javax.swing.JLabel editDataPasien;
    private javax.swing.JDialog editJenisBiaya;
    private javax.swing.JLabel header;
    private javax.swing.JLabel header1;
    private javax.swing.JLabel header2;
    private javax.swing.JTextField idjenis;
    private javax.swing.JTextField idjenis1;
    private javax.swing.JLabel lock;
    private javax.swing.JLabel lock2;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nama2;
    private javax.swing.JTextField namajenis;
    private javax.swing.JTextField namajenis1;
    private javax.swing.JLabel navi;
    private javax.swing.JDialog tambahJenisBiaya;
    private javax.swing.JTextField tarifjenis;
    private javax.swing.JTextField tarifjenis1;
    private javax.swing.JLabel titleSearch;
    private javax.swing.JTextField txtCari;
    private javax.swing.JLabel txtUser;
    private javax.swing.JLabel userPanel;
    // End of variables declaration//GEN-END:variables
}
