/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MenuJadwal;

import MenuUtama.*;
import Koneksi.GlobalVar;
import Koneksi.Koneksi;
import java.awt.Color;
import java.awt.Frame;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author donih
 */
public class MenuJadwal extends javax.swing.JFrame {
    /**
     * Creates new form MenuUtama
     */
    DefaultTableModel table = new DefaultTableModel();
    String KodeDokter;
    public MenuJadwal() {
        initComponents();
        TabelJadwal.setModel(table);
        table.addColumn("Kode Jadwal");
        table.addColumn("Kode Dokter");
        table.addColumn("Nama Dokter");
        table.addColumn("Hari");
        table.addColumn("Jam Mulai");
        table.addColumn("Jam Selesai");
        tampilData();
        addcombo();
       
        txtUser.setText("Hi!, " + GlobalVar.nama);
        this.setBackground(new Color(0,0,0,0));
        if(GlobalVar.hak_akses.equals("Pegawai")){
            btnPegawai.setEnabled(false);
            btnDokter.setEnabled(false);
            btnPemeriksaan.setEnabled(false);
        }else if(GlobalVar.hak_akses.equals("Dokter")){
            btnPegawai.setEnabled(false);
            btnPendaftaran.setEnabled(false);
            btnDokter.setEnabled(false);
            btnPoli.setEnabled(false);
            btnObat.setEnabled(false);
            btnPembayaran.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tambahData = new javax.swing.JDialog();
        NamaDokter = new javax.swing.JComboBox<>();
        JamSelesai = new javax.swing.JTextField();
        Jselesai = new javax.swing.JLabel();
        JamMulai = new javax.swing.JTextField();
        Jmulai = new javax.swing.JLabel();
        Hari = new javax.swing.JTextField();
        HariJad = new javax.swing.JLabel();
        NamaDok = new javax.swing.JLabel();
        MIN1 = new javax.swing.JButton();
        MAX1 = new javax.swing.JButton();
        CLOSE1 = new javax.swing.JButton();
        Batal = new javax.swing.JButton();
        Simpan = new javax.swing.JButton();
        KodeJadwal = new javax.swing.JTextField();
        KodeJad = new javax.swing.JLabel();
        header1 = new javax.swing.JLabel();
        bg1 = new javax.swing.JLabel();
        editData = new javax.swing.JDialog();
        JamSelesai1 = new javax.swing.JTextField();
        Jselesai1 = new javax.swing.JLabel();
        JamMulai1 = new javax.swing.JTextField();
        Jmulai1 = new javax.swing.JLabel();
        Hari1 = new javax.swing.JTextField();
        HariJad1 = new javax.swing.JLabel();
        NamaDok1 = new javax.swing.JLabel();
        NamaDokter1 = new javax.swing.JComboBox<>();
        KodeJadwal1 = new javax.swing.JTextField();
        KodeJad1 = new javax.swing.JLabel();
        MIN2 = new javax.swing.JButton();
        MAX2 = new javax.swing.JButton();
        CLOSE2 = new javax.swing.JButton();
        Batal1 = new javax.swing.JButton();
        Simpan1 = new javax.swing.JButton();
        header2 = new javax.swing.JLabel();
        bg2 = new javax.swing.JLabel();
        PopupSearch = new javax.swing.JDialog();
        CLOSE4 = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        cari = new javax.swing.JButton();
        titleSearch = new javax.swing.JLabel();
        bg3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelJadwal = new javax.swing.JTable();
        Delete = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        Input = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        MIN = new javax.swing.JButton();
        MAX = new javax.swing.JButton();
        CLOSE = new javax.swing.JButton();
        btnPembayaran = new javax.swing.JButton();
        btnObat = new javax.swing.JButton();
        btnJadwalPraktek = new javax.swing.JButton();
        btnPemeriksaan = new javax.swing.JButton();
        btnPoli = new javax.swing.JButton();
        Search = new javax.swing.JButton();
        btnDokter = new javax.swing.JButton();
        btnPegawai = new javax.swing.JButton();
        btnPendaftaran = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        txtUser = new javax.swing.JLabel();
        btnUser = new javax.swing.JButton();
        userPanel = new javax.swing.JLabel();
        navi = new javax.swing.JLabel();
        header = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        tambahData.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        tambahData.setUndecorated(true);
        tambahData.setOpacity(0.0F);
        tambahData.setSize(new java.awt.Dimension(600, 600));
        tambahData.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                tambahDataWindowOpened(evt);
            }
        });
        tambahData.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NamaDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaDokterActionPerformed(evt);
            }
        });
        tambahData.getContentPane().add(NamaDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 162, 280, 30));

        JamSelesai.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        JamSelesai.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        JamSelesai.setToolTipText("Username");
        JamSelesai.setAlignmentX(1.0F);
        JamSelesai.setAlignmentY(1.0F);
        JamSelesai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 174, 152), 2));
        JamSelesai.setCaretColor(new java.awt.Color(30, 174, 152));
        JamSelesai.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        JamSelesai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JamSelesaiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JamSelesaiFocusLost(evt);
            }
        });
        JamSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JamSelesaiActionPerformed(evt);
            }
        });
        tambahData.getContentPane().add(JamSelesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 280, 30));

        Jselesai.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Jselesai.setForeground(new java.awt.Color(30, 174, 152));
        Jselesai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuJadwal/Asset/Jam.png"))); // NOI18N
        Jselesai.setText("Jam Selesai");
        tambahData.getContentPane().add(Jselesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 150, 30));

        JamMulai.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        JamMulai.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        JamMulai.setToolTipText("Username");
        JamMulai.setAlignmentX(1.0F);
        JamMulai.setAlignmentY(1.0F);
        JamMulai.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 174, 152), 2));
        JamMulai.setCaretColor(new java.awt.Color(30, 174, 152));
        JamMulai.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        JamMulai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                JamMulaiFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                JamMulaiFocusLost(evt);
            }
        });
        JamMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JamMulaiActionPerformed(evt);
            }
        });
        tambahData.getContentPane().add(JamMulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 280, 30));

        Jmulai.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Jmulai.setForeground(new java.awt.Color(30, 174, 152));
        Jmulai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuJadwal/Asset/Jam.png"))); // NOI18N
        Jmulai.setText("Jam Mulai");
        tambahData.getContentPane().add(Jmulai, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 150, 30));

        Hari.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Hari.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Hari.setToolTipText("Username");
        Hari.setAlignmentX(1.0F);
        Hari.setAlignmentY(1.0F);
        Hari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 174, 152), 2));
        Hari.setCaretColor(new java.awt.Color(30, 174, 152));
        Hari.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Hari.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                HariFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                HariFocusLost(evt);
            }
        });
        Hari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HariActionPerformed(evt);
            }
        });
        tambahData.getContentPane().add(Hari, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 280, 30));

        HariJad.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        HariJad.setForeground(new java.awt.Color(30, 174, 152));
        HariJad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuJadwal/Asset/Hari.png"))); // NOI18N
        HariJad.setText("Hari");
        tambahData.getContentPane().add(HariJad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 150, 30));

        NamaDok.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        NamaDok.setForeground(new java.awt.Color(30, 174, 152));
        NamaDok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/Asset/bx_bxs-user.png"))); // NOI18N
        NamaDok.setText("Nama Dokter");
        tambahData.getContentPane().add(NamaDok, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 160, 30));

        MIN1.setBackground(new Color(0,0,0,0));
        MIN1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/-Off.png"))); // NOI18N
        MIN1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MIN1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Min.png"))); // NOI18N
        MIN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIN1ActionPerformed(evt);
            }
        });
        tambahData.getContentPane().add(MIN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 30, 30));

        MAX1.setBackground(new Color(0,0,0,0));
        MAX1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/maxOff.png"))); // NOI18N
        MAX1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MAX1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Max.png"))); // NOI18N
        tambahData.getContentPane().add(MAX1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 30, 30));

        CLOSE1.setBackground(new Color(0,0,0,0));
        CLOSE1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/xOff.png"))); // NOI18N
        CLOSE1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CLOSE1.setBorderPainted(false);
        CLOSE1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CLOSE1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Close.png"))); // NOI18N
        CLOSE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLOSE1ActionPerformed(evt);
            }
        });
        tambahData.getContentPane().add(CLOSE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 30, 30));

        Batal.setBackground(new Color (0,0,0,0));
        Batal.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        Batal.setForeground(new java.awt.Color(255, 255, 255));
        Batal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/TmblBatal.png"))); // NOI18N
        Batal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Batal.setBorderPainted(false);
        Batal.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/TmblBatalAktif.png"))); // NOI18N
        Batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BatalActionPerformed(evt);
            }
        });
        tambahData.getContentPane().add(Batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 130, -1));

        Simpan.setBackground(new Color (0,0,0,0));
        Simpan.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        Simpan.setForeground(new java.awt.Color(255, 255, 255));
        Simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/tmblSimpan.png"))); // NOI18N
        Simpan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Simpan.setBorderPainted(false);
        Simpan.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/tmblSimpanAktif.png"))); // NOI18N
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });
        tambahData.getContentPane().add(Simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 130, -1));

        KodeJadwal.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        KodeJadwal.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        KodeJadwal.setToolTipText("Username");
        KodeJadwal.setAlignmentX(1.0F);
        KodeJadwal.setAlignmentY(1.0F);
        KodeJadwal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 174, 152), 2));
        KodeJadwal.setCaretColor(new java.awt.Color(30, 174, 152));
        KodeJadwal.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        KodeJadwal.setEnabled(false);
        KodeJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KodeJadwalActionPerformed(evt);
            }
        });
        tambahData.getContentPane().add(KodeJadwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 280, 30));

        KodeJad.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        KodeJad.setForeground(new java.awt.Color(30, 174, 152));
        KodeJad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPoli/Asset/KodePoli.png"))); // NOI18N
        KodeJad.setText("Kode Jadwal");
        tambahData.getContentPane().add(KodeJad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 170, 30));

        header1.setBackground(new Color(0,0,0,0));
        header1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPoli/Asset/Tambah Data (1).png"))); // NOI18N
        tambahData.getContentPane().add(header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 30));

        bg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/BgEditPegawai.png"))); // NOI18N
        bg1.setToolTipText("");
        tambahData.getContentPane().add(bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 530));

        editData.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        editData.setUndecorated(true);
        editData.setOpacity(0.0F);
        editData.setSize(new java.awt.Dimension(600, 600));
        editData.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                editDataWindowOpened(evt);
            }
        });
        editData.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JamSelesai1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        JamSelesai1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        JamSelesai1.setToolTipText("Username");
        JamSelesai1.setAlignmentX(1.0F);
        JamSelesai1.setAlignmentY(1.0F);
        JamSelesai1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 174, 152), 2));
        JamSelesai1.setCaretColor(new java.awt.Color(30, 174, 152));
        JamSelesai1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        JamSelesai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JamSelesai1ActionPerformed(evt);
            }
        });
        editData.getContentPane().add(JamSelesai1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 280, 30));

        Jselesai1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Jselesai1.setForeground(new java.awt.Color(30, 174, 152));
        Jselesai1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuJadwal/Asset/Jam.png"))); // NOI18N
        Jselesai1.setText("Jam Selesai");
        editData.getContentPane().add(Jselesai1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 150, 30));

        JamMulai1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        JamMulai1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        JamMulai1.setToolTipText("Username");
        JamMulai1.setAlignmentX(1.0F);
        JamMulai1.setAlignmentY(1.0F);
        JamMulai1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 174, 152), 2));
        JamMulai1.setCaretColor(new java.awt.Color(30, 174, 152));
        JamMulai1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        JamMulai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JamMulai1ActionPerformed(evt);
            }
        });
        editData.getContentPane().add(JamMulai1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 280, 30));

        Jmulai1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Jmulai1.setForeground(new java.awt.Color(30, 174, 152));
        Jmulai1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuJadwal/Asset/Jam.png"))); // NOI18N
        Jmulai1.setText("Jam Mulai");
        editData.getContentPane().add(Jmulai1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 150, 30));

        Hari1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        Hari1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Hari1.setToolTipText("Username");
        Hari1.setAlignmentX(1.0F);
        Hari1.setAlignmentY(1.0F);
        Hari1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 174, 152), 2));
        Hari1.setCaretColor(new java.awt.Color(30, 174, 152));
        Hari1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Hari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hari1ActionPerformed(evt);
            }
        });
        editData.getContentPane().add(Hari1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 280, 30));

        HariJad1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        HariJad1.setForeground(new java.awt.Color(30, 174, 152));
        HariJad1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuJadwal/Asset/Hari.png"))); // NOI18N
        HariJad1.setText("Hari");
        editData.getContentPane().add(HariJad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 150, 30));

        NamaDok1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        NamaDok1.setForeground(new java.awt.Color(30, 174, 152));
        NamaDok1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Login/Asset/bx_bxs-user.png"))); // NOI18N
        NamaDok1.setText("Nama Dokter");
        editData.getContentPane().add(NamaDok1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 160, 30));

        NamaDokter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaDokter1ActionPerformed(evt);
            }
        });
        editData.getContentPane().add(NamaDokter1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 162, 280, 30));

        KodeJadwal1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        KodeJadwal1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        KodeJadwal1.setToolTipText("Username");
        KodeJadwal1.setAlignmentX(1.0F);
        KodeJadwal1.setAlignmentY(1.0F);
        KodeJadwal1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(30, 174, 152), 2));
        KodeJadwal1.setCaretColor(new java.awt.Color(30, 174, 152));
        KodeJadwal1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        KodeJadwal1.setEnabled(false);
        KodeJadwal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KodeJadwal1ActionPerformed(evt);
            }
        });
        editData.getContentPane().add(KodeJadwal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 280, 30));

        KodeJad1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        KodeJad1.setForeground(new java.awt.Color(30, 174, 152));
        KodeJad1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPoli/Asset/KodePoli.png"))); // NOI18N
        KodeJad1.setText("Kode Jadwal");
        editData.getContentPane().add(KodeJad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 170, 30));

        MIN2.setBackground(new Color(0,0,0,0));
        MIN2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/-Off.png"))); // NOI18N
        MIN2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MIN2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Min.png"))); // NOI18N
        MIN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIN2ActionPerformed(evt);
            }
        });
        editData.getContentPane().add(MIN2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 30, 30));

        MAX2.setBackground(new Color(0,0,0,0));
        MAX2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/maxOff.png"))); // NOI18N
        MAX2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MAX2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Max.png"))); // NOI18N
        editData.getContentPane().add(MAX2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 30, 30));

        CLOSE2.setBackground(new Color(0,0,0,0));
        CLOSE2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/xOff.png"))); // NOI18N
        CLOSE2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CLOSE2.setBorderPainted(false);
        CLOSE2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CLOSE2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Close.png"))); // NOI18N
        CLOSE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLOSE2ActionPerformed(evt);
            }
        });
        editData.getContentPane().add(CLOSE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 30, 30));

        Batal1.setBackground(new Color (0,0,0,0));
        Batal1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        Batal1.setForeground(new java.awt.Color(255, 255, 255));
        Batal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/TmblBatal.png"))); // NOI18N
        Batal1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Batal1.setBorderPainted(false);
        Batal1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/TmblBatalAktif.png"))); // NOI18N
        Batal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Batal1ActionPerformed(evt);
            }
        });
        editData.getContentPane().add(Batal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 130, -1));

        Simpan1.setBackground(new Color (0,0,0,0));
        Simpan1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        Simpan1.setForeground(new java.awt.Color(255, 255, 255));
        Simpan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/tmblSimpan.png"))); // NOI18N
        Simpan1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Simpan1.setBorderPainted(false);
        Simpan1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/tmblSimpanAktif.png"))); // NOI18N
        Simpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Simpan1ActionPerformed(evt);
            }
        });
        editData.getContentPane().add(Simpan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 130, -1));

        header2.setBackground(new Color(0,0,0,0));
        header2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPoli/Asset/edit data.png"))); // NOI18N
        editData.getContentPane().add(header2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 30));

        bg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPegawai/Asset/BgEditPegawai.png"))); // NOI18N
        bg2.setToolTipText("");
        editData.getContentPane().add(bg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 520));

        PopupSearch.setUndecorated(true);
        PopupSearch.setOpacity(0.0F);
        PopupSearch.setResizable(false);
        PopupSearch.setSize(new java.awt.Dimension(251, 116));
        PopupSearch.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                PopupSearchWindowOpened(evt);
            }
        });
        PopupSearch.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CLOSE4.setBackground(new Color(0,0,0,0));
        CLOSE4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/xOff.png"))); // NOI18N
        CLOSE4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CLOSE4.setBorderPainted(false);
        CLOSE4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CLOSE4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Close.png"))); // NOI18N
        CLOSE4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLOSE4ActionPerformed(evt);
            }
        });
        PopupSearch.getContentPane().add(CLOSE4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 30, 30));

        txtCari.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        txtCari.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCari.setToolTipText("Cari Berdasarkan Nama");
        txtCari.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(30, 173, 152), 2, true));
        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        PopupSearch.getContentPane().add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 170, 30));

        cari.setBackground(new Color(0,0,0,0));
        cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/SearchAktif.png"))); // NOI18N
        cari.setBorder(null);
        cari.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Search.png"))); // NOI18N
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        PopupSearch.getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, -1, 50));

        titleSearch.setFont(new java.awt.Font("SansSerif", 2, 11)); // NOI18N
        titleSearch.setForeground(new java.awt.Color(255, 255, 255));
        titleSearch.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleSearch.setText("Search");
        PopupSearch.getContentPane().add(titleSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 30));

        bg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPembayaran/Asset/SearchPopup.png"))); // NOI18N
        PopupSearch.getContentPane().add(bg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabelJadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        TabelJadwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelJadwalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelJadwal);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 860, 430));

        Delete.setBackground(new Color(0,0,0,0));
        Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPoli/Asset/delete.png"))); // NOI18N
        Delete.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Delete.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPoli/Asset/delete huruf.png"))); // NOI18N
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 370, 90, 80));

        Edit.setBackground(new Color(0,0,0,0));
        Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPoli/Asset/edit.png"))); // NOI18N
        Edit.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Edit.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPoli/Asset/edit huruf.png"))); // NOI18N
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        getContentPane().add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 270, 90, 80));

        Input.setBackground(new Color(0,0,0,0));
        Input.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPoli/Asset/input.png"))); // NOI18N
        Input.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Input.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPoli/Asset/input huruf.png"))); // NOI18N
        Input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputActionPerformed(evt);
            }
        });
        getContentPane().add(Input, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 170, 90, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuJadwal/Asset/DATA JADWAL.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 75, -1, -1));

        MIN.setBackground(new Color(0,0,0,0));
        MIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/-Off.png"))); // NOI18N
        MIN.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MIN.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Min.png"))); // NOI18N
        MIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MINActionPerformed(evt);
            }
        });
        getContentPane().add(MIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 0, 30, 30));

        MAX.setBackground(new Color(0,0,0,0));
        MAX.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/maxOff.png"))); // NOI18N
        MAX.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        MAX.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Max.png"))); // NOI18N
        getContentPane().add(MAX, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 0, 30, 30));

        CLOSE.setBackground(new Color(0,0,0,0));
        CLOSE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/xOff.png"))); // NOI18N
        CLOSE.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        CLOSE.setBorderPainted(false);
        CLOSE.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CLOSE.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Close.png"))); // NOI18N
        CLOSE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLOSEActionPerformed(evt);
            }
        });
        getContentPane().add(CLOSE, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 0, 30, 30));

        btnPembayaran.setBackground(new Color(0,0,0,0));
        btnPembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/pembayaran.png"))); // NOI18N
        btnPembayaran.setBorder(null);
        btnPembayaran.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/PembayaranAktif.png"))); // NOI18N
        btnPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPembayaranActionPerformed(evt);
            }
        });
        getContentPane().add(btnPembayaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 588, -1, -1));

        btnObat.setBackground(new Color(0,0,0,0));
        btnObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Obat.png"))); // NOI18N
        btnObat.setBorder(null);
        btnObat.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/ObatAktif.png"))); // NOI18N
        btnObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObatActionPerformed(evt);
            }
        });
        getContentPane().add(btnObat, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 514, -1, -1));

        btnJadwalPraktek.setBackground(new Color(0,0,0,0));
        btnJadwalPraktek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/JadwalPraktek.png"))); // NOI18N
        btnJadwalPraktek.setBorder(null);
        btnJadwalPraktek.setSelected(true);
        btnJadwalPraktek.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/JadwalPraktekAktif.png"))); // NOI18N
        btnJadwalPraktek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJadwalPraktekActionPerformed(evt);
            }
        });
        getContentPane().add(btnJadwalPraktek, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 440, -1, -1));

        btnPemeriksaan.setBackground(new Color(0,0,0,0));
        btnPemeriksaan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Pemeriksaan.png"))); // NOI18N
        btnPemeriksaan.setBorder(null);
        btnPemeriksaan.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/PemeriksaanAktif.png"))); // NOI18N
        btnPemeriksaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPemeriksaanActionPerformed(evt);
            }
        });
        getContentPane().add(btnPemeriksaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 366, -1, -1));

        btnPoli.setBackground(new Color(0,0,0,0));
        btnPoli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Poli.png"))); // NOI18N
        btnPoli.setBorder(null);
        btnPoli.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/PoliAktif.png"))); // NOI18N
        btnPoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPoliActionPerformed(evt);
            }
        });
        getContentPane().add(btnPoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 292, -1, -1));

        Search.setBackground(new Color(0,0,0,0));
        Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPembayaran/Asset/Search.png"))); // NOI18N
        Search.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Search.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Search.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPembayaran/Asset/seachAktif.png"))); // NOI18N
        Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SearchMouseEntered(evt);
            }
        });
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        getContentPane().add(Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 160, 150, 80));

        btnDokter.setBackground(new Color(0,0,0,0));
        btnDokter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Dokter.png"))); // NOI18N
        btnDokter.setBorder(null);
        btnDokter.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/DokterAktif.png"))); // NOI18N
        btnDokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDokterActionPerformed(evt);
            }
        });
        getContentPane().add(btnDokter, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 218, -1, -1));

        btnPegawai.setBackground(new Color(0,0,0,0));
        btnPegawai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Pegawai.png"))); // NOI18N
        btnPegawai.setBorder(null);
        btnPegawai.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/PegawaiAktif.png"))); // NOI18N
        btnPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPegawaiActionPerformed(evt);
            }
        });
        getContentPane().add(btnPegawai, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 144, -1, -1));

        btnPendaftaran.setBackground(new Color(0,0,0,0));
        btnPendaftaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/Pendaftaran.png"))); // NOI18N
        btnPendaftaran.setBorder(null);
        btnPendaftaran.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/PendaftaranAktif.png"))); // NOI18N
        btnPendaftaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPendaftaranActionPerformed(evt);
            }
        });
        getContentPane().add(btnPendaftaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 70, -1, -1));

        btnHome.setBackground(new Color(0,0,0,0));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hospital.png"))); // NOI18N
        btnHome.setToolTipText("Home");
        btnHome.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hospitalAktif.png"))); // NOI18N
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 20, -1, -1));

        txtUser.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        txtUser.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtUser.setText("Hi!, User");
        getContentPane().add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 40, 200, 20));

        btnUser.setBackground(new Color(0,0,0,0));
        btnUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/akun.png"))); // NOI18N
        btnUser.setToolTipText("Log Out");
        btnUser.setBorder(null);
        btnUser.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/akun1.png"))); // NOI18N
        btnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 34, -1, -1));

        userPanel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        userPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Dokter/Asset/Acc (1).png"))); // NOI18N
        userPanel.setToolTipText("");
        getContentPane().add(userPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 27, -1, -1));

        navi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/navi.png"))); // NOI18N
        getContentPane().add(navi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, -1, -1));

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuUtama/Asset/header.png"))); // NOI18N
        getContentPane().add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MenuPoli/Asset/BG.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

     private void tampilData(){
        //untuk mengahapus baris setelah input
        int row = TabelJadwal.getRowCount();
        for(int a = 0 ; a < row ; a++){
            table.removeRow(0);
        }
        
        String query = 
                "SELECT KodeJadwal,dokter.KodeDokter,NmDokter,Hari,JamMulai,JamSelesai FROM jadwalpraktek\n" +
                "INNER JOIN dokter ON jadwalpraktek.KodeDokter = dokter.KodeDokter ORDER BY KodeJadwal";
        
        try{
            Connection connect = Koneksi.getKoneksi();//memanggil koneksi
            Statement sttmnt = connect.createStatement();//membuat statement
            ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
            
            while (rslt.next()){
                //menampung data sementara
                String kodejad = rslt.getString("KodeJadwal");
                String kodedok = rslt.getString("KodeDokter");
                String nama = rslt.getString("NmDokter");
                String hari = rslt.getString("Hari");
                String jmulai = rslt.getString("JamMulai");
                String jselesai = rslt.getString("JamSelesai");
                
                String[] data = {kodejad,kodedok,nama,hari,jmulai,jselesai};
                //menambahakan baris sesuai dengan data yang tersimpan diarray
                table.addRow(data);
            }
                //mengeset nilai yang ditampung agar muncul di table
                TabelJadwal.setModel(table);
            
        }catch(Exception e){
            System.out.println(e);
        }
       
    }
        private void hapusData(){
        //ambill data no pendaftaran
           
        Connection connect = Koneksi.getKoneksi();
        int baris = TabelJadwal.getSelectedRow();
        int jawab;
        String kode = table.getValueAt(baris,0).toString();
        
        String query = "DELETE FROM jadwalpraktek WHERE KodeJadwal = '"+kode+"';";
        try{
            if ((jawab = JOptionPane.showConfirmDialog(null, "Ingin menghapus data?", "konfirmasi", JOptionPane.YES_NO_OPTION)) == 0) {
            PreparedStatement ps = (PreparedStatement) connect.prepareStatement(query);
            ps.execute();
            JOptionPane.showMessageDialog(null , "Data Berhasil Dihapus");
        }
        }catch(SQLException | HeadlessException e){
            System.out.println(e);
            JOptionPane.showMessageDialog(null, "Data Gagal Dihapus");
        }finally{
            tampilData();
        }
        
    }
            private void LoadData(){      
        String query = "SELECT * FROM jadwalpraktek WHERE KodeJadwal = '"+GlobalVar.KodeJadwal+"' ";
        
        try{
            Connection connect = Koneksi.getKoneksi();//memanggil koneksi
            Statement sttmnt = connect.createStatement();//membuat statement
            ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
            
            while (rslt.next()){
                String Kode = rslt.getString("KodeJadwal");
                String Har = rslt.getString("Hari");
                String Jmulai = rslt.getString("JamMulai");
                String Jselesai = rslt.getString("JamSelesai");
                
                KodeJadwal1.setText(Kode);
                Hari1.setText(Har);
                JamMulai1.setText(Jmulai);
                JamSelesai1.setText(Jselesai);
            } 
        }catch(Exception e){
            
            System.out.println(e);
        } 
    }
        private void UpdateData(){
        String Kode = KodeJadwal1.getText();
        String Har = Hari1.getText();
        String Mulai = JamMulai1.getText();
        String Selesai = JamSelesai1.getText();
        String nmdok = (String)NamaDokter1.getSelectedItem();
        
        String query = "SELECT * FROM dokter WHERE NmDokter = '"+nmdok+"' ";
                
        try{
            Connection connect = Koneksi.getKoneksi();//memanggil koneksi
            Statement sttmnt = connect.createStatement();//membuat statement
            ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query

            while (rslt.next()){
                KodeDokter = rslt.getString("KodeDokter");   
             }
        }catch(Exception e){
            System.out.println(e);
        }finally{
            Connection connect = Koneksi.getKoneksi();
            //query untuk memasukan data
            String query2 = "UPDATE jadwalpraktek SET KodeDokter = '"+KodeDokter+"' ,Hari= '"+Har+"' ,"
                    + "JamMulai = '"+Mulai+"' ,JamSelesai= '"+Selesai+"' WHERE KodeJadwal = '"+Kode+"';";
            try{
                //menyiapkan statement untuk di eksekusi
                PreparedStatement ps = (PreparedStatement) connect.prepareStatement(query2);
                ps.executeUpdate(query2);
                JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");

            }catch(SQLException | HeadlessException e){
                System.out.println(e);
                JOptionPane.showMessageDialog(null,"Data Gagal Disimpan");

            }finally{
                editData.dispose();
                KodeJadwal1.setText(null);
                Hari1.setText(null);
                JamMulai1.setText(null);
                JamSelesai1.setText(null);
            }
        }
    }
        private void kodeotomatis(){
        String query = "SELECT * FROM jadwalpraktek ORDER BY KodeJadwal DESC ";
        try{
            Connection connect = Koneksi.getKoneksi();//memanggil koneksi
            Statement sttmnt = connect.createStatement();//membuat statement
            ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
            
            if (rslt.next()){
                String kode_jadwal = rslt.getString("KodeJadwal").substring(1);
                String AN = "" + (Integer.parseInt(kode_jadwal)+1);
                String NOL = "";
                if(AN.length()==1){
                    NOL = "000";
                }else if(AN.length()==2){
                    NOL = "00";
                }else if(AN.length()==3){
                    NOL = "0";
                }else if(AN.length()==4){
                    NOL = "";
                }
                KodeJadwal.setText("J" + NOL + AN);
            }else{
                KodeJadwal.setText("J0001");
            }
        rslt.close();
        connect.close();
        }catch(Exception e){
            System.out.println(e);
        }
    }
        private void cari(){
        int row = TabelJadwal.getRowCount();
        for(int a = 0 ; a < row ; a++){
            table.removeRow(0);
        }
        
        String cari = txtCari.getText();
        
        String query = 
                        "SELECT KodeJadwal,dokter.KodeDokter,NmDokter,Hari,JamMulai,JamSelesai FROM jadwalpraktek\n" +
                        "INNER JOIN dokter ON jadwalpraktek.KodeDokter = dokter.KodeDokter\n "+
                        "WHERE NmDokter LIKE '%"+cari+"%'ORDER BY KodeJadwal ";
//                    "SELECT KodeDokter,KodePoli,TelpPeg,TglLhrPeg,JnsKelPeg,AlmPeg FROM pegawai WHERE NamaPeg LIKE '%"+cari+"%'";
                
       try{
           Connection connect = Koneksi.getKoneksi();//memanggil koneksi
           Statement sttmnt = connect.createStatement();//membuat statement
           ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
           
           while (rslt.next()){
                //menampung data sementara
                   
                    String kode = rslt.getString("KodeJadwal");
                    String kodedok = rslt.getString("KodeDokter");
                    String namadok = rslt.getString("NmDokter");
                    String har = rslt.getString("Hari");
                    String jmulai = rslt.getString("JamMulai");
                    String jselesai = rslt.getString("JamSelesai");
                    
                //masukan semua data kedalam array
                String[] data = {kode,kodedok,namadok,har,jmulai,jselesai};
                //menambahakan baris sesuai dengan data yang tersimpan diarray
                table.addRow(data);
            }
                //mengeset nilai yang ditampung agar muncul di table
                TabelJadwal.setModel(table);
           
        
        }catch(Exception e){
               System.out.println(e);
        }
    }
    private void MINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MINActionPerformed
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_MINActionPerformed

    private void CLOSEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLOSEActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_CLOSEActionPerformed

    private void btnPendaftaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPendaftaranActionPerformed
        // TODO add your handling code here:
        new Pendaftaran.DataPasien().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPendaftaranActionPerformed

    private void btnPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPegawaiActionPerformed
        // TODO add your handling code here:
        new MenuPegawai.MenuPegawai().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPegawaiActionPerformed

    private void btnDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDokterActionPerformed
        // TODO add your handling code here:
        new Dokter.MenuDokter().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnDokterActionPerformed

    private void btnPoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPoliActionPerformed
        // TODO add your handling code here:
        new MenuPoli.MenuPoli().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPoliActionPerformed

    private void btnPemeriksaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPemeriksaanActionPerformed
        // TODO add your handling code here:
        new MenuPemeriksaan.Pemeriksaan().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPemeriksaanActionPerformed

    private void btnJadwalPraktekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJadwalPraktekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJadwalPraktekActionPerformed

    private void btnObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObatActionPerformed
        // TODO add your handling code here:
        new MenuObat.MenuObat().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnObatActionPerformed

    private void btnPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPembayaranActionPerformed
        // TODO add your handling code here:
        new MenuPembayaran.JenisBiaya().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnPembayaranActionPerformed

    private void InputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputActionPerformed
        // TODO add your handling code here:
        kodeotomatis();
        tambahData.setVisible(true);
        tambahData.setBounds(380, 120   , 600, 520);
    }//GEN-LAST:event_InputActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
        editData.setVisible(true);
        editData.setBounds(380, 120, 600, 520);
        LoadData();
        addcombo();
    }//GEN-LAST:event_EditActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        hapusData();
    }//GEN-LAST:event_DeleteActionPerformed

    private void MIN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIN1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_MIN1ActionPerformed

    private void CLOSE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLOSE1ActionPerformed
        // TODO add your handling code here:
        Hari.setText(null);
        JamMulai.setText(null);
        JamSelesai.setText(null);
        tambahData.dispose();
    }//GEN-LAST:event_CLOSE1ActionPerformed

    private void BatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BatalActionPerformed
        // TODO add your handling code here:
        Hari.setText(null);
        JamMulai.setText(null);
        JamSelesai.setText(null);
        tambahData.dispose();
    }//GEN-LAST:event_BatalActionPerformed

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        // TODO add your handling code here:
        InputData();
        tampilData();
    }//GEN-LAST:event_SimpanActionPerformed

    private void KodeJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KodeJadwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KodeJadwalActionPerformed

    private void tambahDataWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_tambahDataWindowOpened
        // TODO add your handling code here:
        for(double i = 0.0; i <= 1.0; i = i + 0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            //            this.setOpacity(f);
            tambahData.setOpacity(f);
            try{
                Thread.sleep(20);
            }
            catch(Exception e){
            }
        }
    }//GEN-LAST:event_tambahDataWindowOpened

    private void MIN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIN2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MIN2ActionPerformed

    private void CLOSE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLOSE2ActionPerformed
        // TODO add your handling code here:
        editData.dispose();
    }//GEN-LAST:event_CLOSE2ActionPerformed

    private void Batal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Batal1ActionPerformed
        // TODO add your handling code here:
        editData.dispose();
    }//GEN-LAST:event_Batal1ActionPerformed

    private void Simpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Simpan1ActionPerformed
        // TODO add your handling code here:
        UpdateData();
        tampilData();
    }//GEN-LAST:event_Simpan1ActionPerformed

    private void editDataWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_editDataWindowOpened
        // TODO add your handling code here:
                for(double i = 0.0; i <= 1.0; i = i + 0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            //            this.setOpacity(f);
            editData.setOpacity(f);
            try{
                Thread.sleep(20);
            }
            catch(Exception e){
            }
        }
    }//GEN-LAST:event_editDataWindowOpened

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
            for(double i = 0.0; i <= 1.0; i = i + 0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            this.setOpacity(f);
            try{
                Thread.sleep(20);
            }
           catch(Exception e){
            }
        }
    }//GEN-LAST:event_formWindowOpened

    private void HariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HariActionPerformed

    private void JamMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JamMulaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JamMulaiActionPerformed

    private void TabelJadwalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelJadwalMouseClicked
        // TODO add your handling code here:
        String kode = table.getValueAt(TabelJadwal.getSelectedRow(),0).toString();
        GlobalVar.KodeJadwal = kode;
    }//GEN-LAST:event_TabelJadwalMouseClicked

    private void JamSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JamSelesaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JamSelesaiActionPerformed

    private void NamaDokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaDokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaDokterActionPerformed

    private void KodeJadwal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KodeJadwal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KodeJadwal1ActionPerformed

    private void NamaDokter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaDokter1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaDokter1ActionPerformed

    private void Hari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hari1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hari1ActionPerformed

    private void JamMulai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JamMulai1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JamMulai1ActionPerformed

    private void JamSelesai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JamSelesai1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JamSelesai1ActionPerformed

    private void btnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserActionPerformed
        // TODO add your handling code here:
        int opsi = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan keluar?", "Log out!", JOptionPane.YES_NO_OPTION);
        if (opsi == JOptionPane.YES_OPTION){
            new Login.Login().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnUserActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        new MenuUtama().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void HariFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_HariFocusGained
        // TODO add your handling code here:
         
    }//GEN-LAST:event_HariFocusGained

    private void HariFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_HariFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_HariFocusLost

    private void JamMulaiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JamMulaiFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JamMulaiFocusGained

    private void JamMulaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JamMulaiFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JamMulaiFocusLost

    private void JamSelesaiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JamSelesaiFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_JamSelesaiFocusGained

    private void JamSelesaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_JamSelesaiFocusLost
        // TODO add your handling code here:
       
    }//GEN-LAST:event_JamSelesaiFocusLost

    private void SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseClicked
        // TODO add your handling code here:
        PopupSearch.setVisible(true);
        PopupSearch.setLocation(930, 240);
    }//GEN-LAST:event_SearchMouseClicked

    private void SearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchMouseEntered

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    private void CLOSE4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLOSE4ActionPerformed
        // TODO add your handling code here:
        tampilData();
        PopupSearch.setVisible(false);
    }//GEN-LAST:event_CLOSE4ActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
        cari();
        PopupSearch.setVisible(false);
    }//GEN-LAST:event_cariActionPerformed

    private void PopupSearchWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_PopupSearchWindowOpened
        // TODO add your handling code here:
        for(double i = 0.0; i <= 1.0; i = i + 0.1){
            String val = i+ "";
            float f = Float.valueOf(val);
            //            this.setOpacity(f);
            PopupSearch.setOpacity(f);
            try{
                Thread.sleep(20);
            }
            catch(Exception e){
            }
        }
    }//GEN-LAST:event_PopupSearchWindowOpened
        private void InputData(){
        String Kode = KodeJadwal.getText();
        String Har = Hari.getText();
        String Mulai = JamMulai.getText();
        String Selesai = JamSelesai.getText();
        String nmdok = (String)NamaDokter.getSelectedItem();
        
        String query = "SELECT * FROM dokter WHERE NmDokter = '"+nmdok+"' ";
                
        try{
            Connection connect = Koneksi.getKoneksi();//memanggil koneksi
            Statement sttmnt = connect.createStatement();//membuat statement
            ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query

            while (rslt.next()){
                KodeDokter = rslt.getString("KodeDokter");   
             }
        }catch(Exception e){
            System.out.println(e);
        }finally{
            Connection connect = Koneksi.getKoneksi();
            //query untuk memasukan data
            String query2 = "INSERT INTO jadwalpraktek (KodeJadwal, KodeDokter, Hari, JamMulai, JamSelesai ) "
                         + "VALUES ('"+Kode+"', '"+KodeDokter+"','"+Har+"', '"+Mulai+"', '"+Selesai+"')";
            try{
                //menyiapkan statement untuk di eksekusi
                PreparedStatement ps = (PreparedStatement) connect.prepareStatement(query2);
                ps.executeUpdate(query2);
                JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");

            }catch(SQLException | HeadlessException e){
                System.out.println(e);
                JOptionPane.showMessageDialog(null,"Data Gagal Disimpan");

            }finally{
                tambahData.dispose();
                KodeJadwal.setText(null);
                Hari.setText(null);
                JamMulai.setText(null);
                JamSelesai.setText(null);
            }
        }
        }
    private void addcombo(){
        String query = "SELECT *FROM dokter";
        
        try{
            Connection connect = Koneksi.getKoneksi();//memanggil koneksi
            Statement sttmnt = connect.createStatement();//membuat statement
            ResultSet rslt = sttmnt.executeQuery(query);//menjalanakn query
            
            while (rslt.next()){
                String nama = rslt.getString("NmDokter");
                NamaDokter.addItem(nama);
                NamaDokter1.addItem(nama);
            }
        }catch(Exception e){
            System.out.println(e);
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuJadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuJadwal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Batal;
    private javax.swing.JButton Batal1;
    private javax.swing.JButton CLOSE;
    private javax.swing.JButton CLOSE1;
    private javax.swing.JButton CLOSE2;
    private javax.swing.JButton CLOSE4;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Edit;
    private javax.swing.JTextField Hari;
    private javax.swing.JTextField Hari1;
    private javax.swing.JLabel HariJad;
    private javax.swing.JLabel HariJad1;
    private javax.swing.JButton Input;
    private javax.swing.JTextField JamMulai;
    private javax.swing.JTextField JamMulai1;
    private javax.swing.JTextField JamSelesai;
    private javax.swing.JTextField JamSelesai1;
    private javax.swing.JLabel Jmulai;
    private javax.swing.JLabel Jmulai1;
    private javax.swing.JLabel Jselesai;
    private javax.swing.JLabel Jselesai1;
    private javax.swing.JLabel KodeJad;
    private javax.swing.JLabel KodeJad1;
    private javax.swing.JTextField KodeJadwal;
    private javax.swing.JTextField KodeJadwal1;
    private javax.swing.JButton MAX;
    private javax.swing.JButton MAX1;
    private javax.swing.JButton MAX2;
    private javax.swing.JButton MIN;
    private javax.swing.JButton MIN1;
    private javax.swing.JButton MIN2;
    private javax.swing.JLabel NamaDok;
    private javax.swing.JLabel NamaDok1;
    private javax.swing.JComboBox<String> NamaDokter;
    private javax.swing.JComboBox<String> NamaDokter1;
    private javax.swing.JDialog PopupSearch;
    private javax.swing.JButton Search;
    private javax.swing.JButton Simpan;
    private javax.swing.JButton Simpan1;
    private javax.swing.JTable TabelJadwal;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel bg1;
    private javax.swing.JLabel bg2;
    private javax.swing.JLabel bg3;
    private javax.swing.JButton btnDokter;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnJadwalPraktek;
    private javax.swing.JButton btnObat;
    private javax.swing.JButton btnPegawai;
    private javax.swing.JButton btnPembayaran;
    private javax.swing.JButton btnPemeriksaan;
    private javax.swing.JButton btnPendaftaran;
    private javax.swing.JButton btnPoli;
    private javax.swing.JButton btnUser;
    private javax.swing.JButton cari;
    private javax.swing.JDialog editData;
    private javax.swing.JLabel header;
    private javax.swing.JLabel header1;
    private javax.swing.JLabel header2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel navi;
    private javax.swing.JDialog tambahData;
    private javax.swing.JLabel titleSearch;
    private javax.swing.JTextField txtCari;
    private javax.swing.JLabel txtUser;
    private javax.swing.JLabel userPanel;
    // End of variables declaration//GEN-END:variables
}
